### ISSUE TITLE
container Failing to start

### ISSUE THREAD

**Issue by majinding** [SonarSource/docker-sonarqube#101]
I have the same problem #25 
running with raw "`docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube`" is ok
but running "`docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 -e SONARQUBE_JDBC_USERNAME=root -e SONARQUBE_JDBC_PASSWORD=root -e SONARQUBE_JDBC_URL=jdbc:mysql://192.168.1.29:3306/sonarqube sonarqube`" was not work,The container cannot start,
When you build the mirror using the dockerfile installation, it is also successful
But when i start the container, prompt run.sh can't find

**Comment by majinding** [comment]
now I running with raw "docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube" is ok
but when I command `"docker exec -it sonarqube bash"` was error `"rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"bash\": executable file not found in $PATH""`


![default](https://user-images.githubusercontent.com/2681645/29310684-3ea5c712-81e1-11e7-8f2b-23ca63d02b98.png)

**Comment by patrickmslatteryvt** [comment]
What I found when I used a MySQL DB was that the database name had to be "sonar", so that might be hardcoded somewhere, I didn't dig into it too far.
For your other error used `sh` instead of `bash` as Alpine Linux does not include bash by default:
```diff
- docker exec -it sonarqube bash
+ docker exec -it sonarqube sh
```

**Comment by Godin** [comment]
@patrickmslatteryvt First of all thank you for helping here! This is very much appreciated! :heart: 

You're right about `bash` and Alpine image. :thumbsup:

However as shown below, I cannot reproduce any of problems with MySQL that were mentioned here including

> when used a MySQL DB was that the database name had to be sonar, so that might be hardcoded somewhere

Maybe this was about default user and password for DB that are both `sonar` - see 
https://github.com/SonarSource/docker-sonarqube/blob/c6aa0bbe967999f37cfa64522b3ae6ff0fda04de/5.6.6/Dockerfile#L7-L8

---

After creation of MySQL with database named `sq`:

```
docker run --rm \
    --name db \
    -e MYSQL_DATABASE=sq \
    -e MYSQL_ROOT_PASSWORD=root-password \
    -e MYSQL_USER=user \
    -e MYSQL_PASSWORD=user-password \
    mysql
```

SonarQube succesfully connects to it:

```
docker run --rm \
    --link db:db \
    -e SONARQUBE_JDBC_URL="jdbc:mysql://db/sq?useUnicode=true&characterEncoding=utf8" \
    -e SONARQUBE_JDBC_USERNAME=user \
    -e SONARQUBE_JDBC_PASSWORD=user-password \
    sonarqube
```

as log shows:

```
...
2017.08.15 18:29:50 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:mysql://db/sq?useUnicode=true&characterEncoding=utf8
...
2017.08.15 18:29:52 INFO  web[][DbMigrations] Executing DB migrations...
2017.08.15 18:29:52 INFO  web[][DbMigrations] #1 'Create initial schema'...
2017.08.15 18:29:53 INFO  web[][DbMigrations] #1 'Create initial schema': success | time=1698ms
2017.08.15 18:29:53 INFO  web[][DbMigrations] #2 'Populate initial schema'...
...
```

---

@majinding

> was not work

what was in log?

**Comment by majinding** [comment]
I'm sorry, I didn't know how to check the log before the container started

Now the reason for the problem has been found, because the mysql5.1 version is too low
![image](https://user-images.githubusercontent.com/2681645/29343942-08eb8400-8267-11e7-8152-7a326356881d.png)


Thanks @patrickmslatteryvt , @Godin
