### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by noyessie** [SonarSource/docker-sonarqube#105]
When i run docker, It still loading and i get this error in my dev console:

![image](https://user-images.githubusercontent.com/9568083/29917443-f0eeba82-8e39-11e7-9ee1-17abae33465b.png)

Please someone can't help me.

I have Centos 7 , docker-ce 1.12.6

**Comment by Godin** [comment]
This is an issue tracker of a Docker image and this doesn't look like a problem with image. For the general questions about SonarQube please follow https://www.sonarqube.org/community/feedback/
