### ISSUE TITLE
add an old version

### ISSUE THREAD

**Issue by sbuisson** [SonarSource/docker-sonarqube#110]
Hello, can you add the 4.5 version of sonarQube?

**Comment by Godin** [comment]
No, this repository maintains only `Dockerfile`s for current LTS that is 5.6.7 and for latest 6.5.
However you can grab pre-built historical image from https://hub.docker.com/r/library/sonarqube/tags/ as
```
docker run sonarqube:4.5.7
```
or built it on your own based on current `Dockerfile`s, or from past commits - https://github.com/SonarSource/docker-sonarqube/commit/e09a66a5a2e6337e2852c4f36659632ea505fdb1
