### ISSUE TITLE
Please add SonarQube Version 6.7

### ISSUE THREAD

**Issue by ohartl** [SonarSource/docker-sonarqube#118]
self-explanatory..

**Comment by JorritSalverda** [comment]
Would be nice to make this part of your release process so you can't forget about it. Thanks for an awesome product, btw!

**Comment by Godin** [comment]
This wasn't forgotten. Please relax the pressure and be a bit more patient.
For the incredibly impatient people, who can't wait more than one-two days - feel free to build your own image out of any released artifacts of your choice.

**Comment by Godin** [comment]
Done in #119 , will be available from Docker library once https://github.com/docker-library/official-images/pull/3687 is merged
