### ISSUE TITLE
Error 413 when jenkins tries to upload zipped report over 1 megabyte in size

### ISSUE THREAD

**Issue by davidacarter** [SonarSource/docker-sonarqube#120]
Using version 6.6 of this sonarqube container.

See log snippet below. This configuration was working great end to end, until the "zip size" on that second line grew past the  1 MB threshold. Now I get an nginx error 413. Went inside the container hoping to find a conf file I can manipulate, my best guess is that nginx needs a increase to its client_max_body_size configuration parameter, but it does not look like a standard issue nginx running here.

Spend a lot of cycles trying to trace this today, and searched through existing issues with no luck. Fairly surprised others are not seeing the same symptom, given the small size of the project being scanned. Help?

[INFO] Analysis report generated in 2463ms, dir size=2 MB
[INFO] Analysis reports compressed in 1685ms, zip size=1 MB
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:54 min
[INFO] Finished at: 2017-11-09T07:56:57Z
[INFO] Final Memory: 86M/1091M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar (default-cli) on project missioncontrol: Failed to upload report - 413: <html>
[ERROR] <head><title>413 Request Entity Too Large</title></head>
[ERROR] <body bgcolor="white">
[ERROR] <center><h1>413 Request Entity Too Large</h1></center>
[ERROR] <hr><center>nginx/1.11.10</center>
[ERROR] </body>
[ERROR] </html>

**Comment by Godin** [comment]
This is an issue tracker of a Docker image and this doesn't look like a problem with image. For the general questions about SonarQube please follow https://www.sonarqube.org/community/feedback/

P.S. Seems that you're using nginx, so check whether it has a defined limit or not.

**Comment by davidacarter** [comment]
I put the version of the Docker container I am using in the first line of my question, it is 6.6, @Godin 

Apologies if the misunderstanding is my own.

**Comment by davidacarter** [comment]
It is possible that the nginx problem is at the kubernetes level though, I think that may be where the issue lies.
