### ISSUE TITLE
issue executing sonarqube 5.6.7

### ISSUE THREAD

**Issue by kihyunsung** [SonarSource/docker-sonarqube#121]
hi there,
I am having issues running Sonarqube .5.6.7 LTS - here are the steps I took.

1) downloaded the Dockerfile along with the run.sh 
2) docker build . -t sonarqube
3) docker run -it --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube
**Error: Unable to access jarfile lib/sonar-application-5.6.7.jar**

It looks like the it unzips and then deletes itself again. The lib folder doesn't exist.

note that if I run in detached mode the container simply exits immediately.
docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube 

I must also mention that I removed all references to gpg public key related stuff in the dockerfile, and changed URLs to local repositories for the sonarqube.zip download.
This is because I am working in an airgapped environment with no internet.

Any help would be much appreciated!

**Comment by Godin** [comment]
Can't reproduce:
```
$ wget --quiet https://raw.githubusercontent.com/SonarSource/docker-sonarqube/4ea09231a5a1ce4af97dd62c9c9bf30588324f57/5.6.7/Dockerfile

$ wget --quiet https://raw.githubusercontent.com/SonarSource/docker-sonarqube/4ea09231a5a1ce4af97dd62c9c9bf30588324f57/5.6.7/run.sh

$ chmod a+x run.sh

$ docker build -t test .
...

$ docker run -it --rm test
...
2017.11.29 17:52:18 INFO  app[o.s.p.m.Monitor] Process[web] is up
```

> I must also mention that I removed all references to gpg public key related stuff in the dockerfile, and changed URLs to local repositories for the sonarqube.zip download.

Check that zip is not corrupted, official distribution has following checksum:
```
$ sha256sum sonarqube-5.6.7.zip
a1537843d8b2ad5d4a15c2a48142b9154775064eecb6c6fb9a9786f394cb4288  sonarqube-5.6.7.zip
```

But in general if you're building image on your own and especially from your own `sonarqube.zip` and with modifications in `Dockerfile` instead of using pre-built image from https://hub.docker.com/_/sonarqube/ , then sorry but you're pretty much on your own as there is no way to reproduce your environment and modifications.
