### ISSUE TITLE
Version (6.7) crashes after a while 

### ISSUE THREAD

**Issue by hellothisisjon** [SonarSource/docker-sonarqube#125]
Seems like the same issue as here https://github.com/SonarSource/docker-sonarqube/issues/116
I can login to the SonarQube admin UI but once I scan a project I breaks.
```
INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
```

**Comment by Sabaum** [comment]
It's crashing on start here.

> 2017.11.29 12:58:11 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
2017.11.29 12:58:11 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143
2017.11.29 12:58:11 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
2017.11.29 12:58:11 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped

**Comment by Godin** [comment]
First of all note that #116 has been fixed a long time ago by #115 , so please make sure that you're using correct image:
```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
sonarqube           6.7                 c1637bd4502f        2 weeks ago         934MB
```

Secondly #116 has nothing to do with
> scan a project

If it constantly dies after analysis of project, then maybe there is not enough memory for SonarQube processes (specifically for compute engine) and you need to change configuration to increase it?

And finally - it's impossible to analyze your problem, given such a small amount of details, especially absence of a **full** log.

**Comment by hellothisisjon** [comment]
@Godin Thanks! I'll look into trying to increase the memory for the processes.

**Comment by makelkal** [comment]
I'm still struggling with the memory setting. Can you post here your settings? I cannot get it keep up... :(

**Comment by hellothisisjon** [comment]
The only thing I did was remove everything and ran `docker system prune -a` and redownloaded the images. after that it just started working... Don't know why...
