### ISSUE TITLE
sonarqube:latest fails to start with MariaDB 10

### ISSUE THREAD

**Issue by only-andy** [SonarSource/docker-sonarqube#127]
I'm using sonarqube:latest image with the Docker package on a Synology NAS. The MariaDB install is 10 (mysql  Ver 15.1 Distrib 10.0.31-MariaDB). The container fails to start, giving an error like:

`ERROR web[][o.s.s.p.Platform] Web server startup failed: Unsupported mysql version: 5.5. Minimal supported version is 5.6.`

Anyone seen this before? Anything I can do?

**Comment by Godin** [comment]
As per https://docs.sonarqube.org/display/SONAR/Requirements supported MySQL versions are 5.6 and 5.7.
