### ISSUE TITLE
Issue using Oracle DB 12c

### ISSUE THREAD

**Issue by kihyunsung** [SonarSource/docker-sonarqube#129]
Hi there,
First of all, let me say that I am fairly new to Docker and also I have very little knowledge of Oracle DBs (or databases in general)

I am trying to use Oracle DB 12c instead of H2, so I have made a little addition to the Dockerfile to download the ojdbc8.jar file from my Artifactory instance to the required directory.

The below is my addition in the docker file.
`curl -o /opt/sonarqube/extensions/jdbc-driver/oracle/ojdbc8.jar http://[my repository]/artifactory/files-local/ojdbc8.jar`

And I have also setup an oracle db 12c, and created a user called c##sonar, and granted it rights to connect.

This is using sqlplus in the oracle DB server.

**Create user**
```
SQL> create user c##sonar
  2  identified by "sonar"
  3  temporary tablespace temp
  4  default tablespace users;
User created.
```

**Grant connection privilege**
```
SQL> grant connect, resource to c##sonar;
Grant succeeded.
```

This is the command that I use to run the image.

`docker run -d --name sonarqube -p 9000:9000 -e SONARQUBE_JDBC_USERNAME=c##sonar -e SONARQUBE_JDBC_PASSWORD=sonar -e SONARQUBE_JDBC_URL=jdbc:oracle:thin:@[my ip address]:1521:ORCLCDB sonarqube`

The container starts up and runs fine. 
However, when I browse to sonarqube, it just hangs and eventually times out after a long time waiting.

When I use the default H2 database sonarqube is accessible without issues..

Can anyone point out what I could be doing wrong here? I suspect that it could be something that I didn't setup in Oracle DB, and/or something wrong with my docker run command??

Thanks!

**Comment by Godin** [comment]
@kihyunsung Nothing suspicious in your commands. You need to check container logs by using `docker log`, or start it in a non-daemon mode, i.e. without `-d`.
