### ISSUE TITLE
some problems about The docker image of sonarqebe(version6.7.1)

### ISSUE THREAD

**Issue by jamesz2011** [SonarSource/docker-sonarqube#135]
Q1.   If I add some jar into  /opt/sonarqube/extensions/plugins,**how restart the service of sonarqube.**

------------------------------

Q2.If I use the command that "# docker restart $(docker ps -a -q)",After some miuntes,I can't visit the page of Sonarqube.
![default](https://user-images.githubusercontent.com/16397200/34825825-02091c5c-f70f-11e7-97a1-4eac8eac6729.png)

**Comment by Godin** [comment]
First of all - this is not a Q/A forum. For questions please use other channels to reach wider audience that can help/answer/participate your questions, there is SonarQube Google Group, Stackoverflow, etc - see https://www.sonarqube.org/community/

Q1: This repository provides SonarQube image. The way you extend it, use and manage is up to you and your specific environment. AFAIK usual `docker restart` works as for any other Docker containers/images, of course as for any other container given that you properly manage data e.g. with help of volumes/mounts.

Q2: Check the logs to find the reason.
