### ISSUE TITLE
sonar.exclusions does not work

### ISSUE THREAD

**Issue by burtsevyg** [SonarSource/docker-sonarqube#136]
I tried analyse my project with frontend-maven-plugin and angular.

In my pom.xml I have
```
  <properties>
    <sonar.exclusions>dist/**/*,node_modules/**/*,dll/**/*,targer/**/*</sonar.exclusions>
    <sonar.sources>.</sonar.sources>
  </properties>
```
In Jenkinsfile:
```
            stage('SonarQube analysis') {
              withSonarQubeEnv('SonarQube') {
                sh "mvn -e -X org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.0.905:sonar -Dsonar.branch=${env.BRANCH_NAME}"
              }
            }

```
In log strange message:
[DEBUG] 14:03:52.780 'target/frontend-0.1-SNAPSHOT/inline.bundle.js' indexed with language 'js'

And error log:
https://gist.github.com/burtsevyg/bb5ffb670c0022154b57c2b2c039c7d9

sonar 6.7.1 in docker with JS, TypeScript, Java, CSS, SCSS plugins installed.

**Comment by nixel2007** [comment]
You misspelled. targer

**Comment by Godin** [comment]
@burtsevyg This is an issue tracker of a Docker image. In future for the general questions about SonarQube and its usage please follow https://www.sonarqube.org/community/

**Comment by burtsevyg** [comment]
Ok thank you guys!
