### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by wjy1100** [SonarSource/docker-sonarqube#137]
hello, I have a question, how to running on MySQL。

**Comment by Godin** [comment]
First of all - this is not a Q/A forum. For questions please use other channels to reach wider audience that can help/answer/participate your questions, there is SonarQube Google Group, Stackoverflow, etc - see https://www.sonarqube.org/community/

https://github.com/SonarSource/docker-sonarqube/issues/134#issuecomment-356290853 contains example of connection to MySQL database.
