### ISSUE TITLE
Missing rules after container restart

### ISSUE THREAD

**Issue by poznachowski** [SonarSource/docker-sonarqube#138]
I set up SonarQube 6.7.1 on AWS with Elastic Containers and RDS (PostgreSQL).

It initialized fine. I've updated few plugins (SonarJava, SonarJS, etc.) then I killed the container and let AWS ECS Service to recreate it.
It started, but there are no rules available (in logs I see lot of `Disable rule` INFO statements)

I see that only `/data` folder is mounted: `VOLUME "$SONARQUBE_HOME/data"`. Shouldn't `/extensions` folder be mounted as well? It looks to me like it is the cause. After container restart Sonar shows no plugins installed. When i added SonarJava I have my rules back (and SonarJava plugin file located in the `/extensions` folder).

**Comment by Godin** [comment]
@poznachowski see 80366e3419d698b4bba4447f153418ef64b3b705 and linked discussions about why `extensions` and other directories like e.g. `conf` are not explicitly declared as volume. Depending on how you update image - volume might be needed or not. Thus if you wanna do so, then do it on your own - this doesn't require modifications in image and can be done simply as `docker run -v ...`, whereas explicit declaration of volume in image can't be undone as per mentioned discussions.

**Comment by poznachowski** [comment]
Thank you, it's clear now.
