### ISSUE TITLE
Exited of CONTAINER use mysql jdbc

### ISSUE THREAD

**Issue by trockxi** [SonarSource/docker-sonarqube#139]
docker run -d --name sonarqube \
	-p 9000:9000 -p 9092:9092 \
	-e SONARQUBE_JDBC_USERNAME=sonar \
	-e SONARQUBE_JDBC_PASSWORD=sonar \
	-e SONARQUBE_JDBC_URL=jdbc:mysql://10.72.8.97/sonar \
	sonarqube

![image](https://user-images.githubusercontent.com/28647418/35209543-8f6f9094-ff89-11e7-991d-857714cb1cb4.png)

[root@vm128 ~]# docker logs b60adf56c559
Exception in thread "main" org.sonar.process.MessageException: JDBC URL must have the property 'useUnicode=true'
help ,please!

**Comment by burtsevyg** [comment]
Try something like this:
`jdbc:mysql://localhost:3306/sonar?useUnicode=true&amp;characterEncoding=utf8`
