### ISSUE TITLE
How to modify existing rule or add custom rules

### ISSUE THREAD

**Issue by dipindas** [SonarSource/docker-sonarqube#141]
Hi all, I have installed Sonarqube by docker-compose. But I couldn't find a way to update the existing rules, also there is no option to add any custom rules. Please help. Also what is the credentials for admin login?

**Comment by Godin** [comment]
This is an issue tracker of a Docker image. For the general questions about SonarQube, its usage and etc please follow https://www.sonarqube.org/community/feedback/
