### ISSUE TITLE
 Process exited with exit value [es]: 1

### ISSUE THREAD

**Issue by klsanju369** [SonarSource/docker-sonarqube#143]
![image](https://user-images.githubusercontent.com/35989944/35610342-ebdadb46-0686-11e8-92e7-1d71b42b17c5.png)
 Please help me

**Comment by Godin** [comment]
This is an issue tracker of a Docker image. For the general questions about SonarQube please follow https://www.sonarqube.org/community/feedback/

Hint: check logs in directory `D:\sonarqube-6.7.1\logs`
