### ISSUE TITLE
Why you dont persist /opt/sonarqube directory entirely?

### ISSUE THREAD

**Issue by Novitoll** [SonarSource/docker-sonarqube#148]
That's so stupid and utter crap that in official Dockerfiles, you dont persist profiles and plugins. More over, in your ENTYRPOINT's you use script in `bin/run.sh` and it tries to start `lib/sonar-xxx.jar` which is located in one parent dir upper.

I will tell you how crappy the current Dockerfiles are:
- If I will try to extend it in order to persist `/opt/sonarqube/extensions` etc., I will need to create N-more mounting points like

```
FROM sonarqube:lts-alpine

VOLUME /opt/sonarqube/extensions
VOLUME /opt/sonarqube/lib
....
```
therefore, I will need to get managed them on my host N-times, that is so anti-logical

**Comment by Godin** [comment]
First of all - "that's so stupid and utter crap" to not be polite.

> Why you dont persist /opt/sonarqube directory entirely?

Discussion about volumes with docker-library maintainers - https://github.com/docker-library/official-images/pull/2437

> bin/run.sh and it tries to start lib/sonar-xxx.jar which is located in one parent dir upper.

`./bin/run.sh` executed from `/opt/sonarqube` that is `WORKDIR`

If provided image doesn't meet your needs - feel free to create your own.
