### ISSUE TITLE
How to supply http.nonProxyHost

### ISSUE THREAD

**Issue by sruehl** [SonarSource/docker-sonarqube#150]
It seems there is no way to supply the http.nonProxyHost in sonar 6.5.0.27846 (Running in openshift).
I tried:
` RUN echo 'http.nonProxyHost="127.0.0.1|localhost|*.somehost.com"' >> $SONARQUBE_HOME/conf/sonar.properties`
and 
` RUN echo 'sonar.web.javaOpts=-Xmx512m -Xms128m' >> $SONARQUBE_HOME/conf/sonar.properties`
`RUN echo 'sonar.web.javaAdditionalOpts=-Dhttp.nonProxyHost="127.0.0.1|localhost|*.somehost.com"' >> $SONARQUBE_HOME/conf/sonar.properties`

but sonar seems to ignore all of this. Even the sonar.web.javaOpts are completly ommited. I checked my env variables and only the JDBC Params are set. What I'm doing wrong here?

**Comment by Godin** [comment]
run script in Docker image contains following lines

https://github.com/SonarSource/docker-sonarqube/blob/fc89d1c1786137cb1ab98b338a61898ac5b54ae4/6.7.1/run.sh#L16-L17

therefore do

```
docker run -it --rm \
    -e SONARQUBE_WEB_JVM_OPTS=-Dhttp.nonProxyHost="127.0.0.1|localhost|*.somehost.com" \
    sonarqube:6.7.1-alpine
```

or

```
docker run -it --rm \
    sonarqube:6.7.1-alpine \
    -Dsonar.web.javaAdditionalOpts="-Dhttp.nonProxyHost=\"127.0.0.1|localhost|*.somehost.com\""
```

and log shows that they take effect

```
...
2018.02.23 12:36:07 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/opt/sonarqube]: /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Dhttp.nonProxyHost=127.0.0.1|localhost|*.somehost.com -Djava.security.egd=file:/dev/./urandom -cp ./lib/common/*:./lib/server/*:/opt/sonarqube/lib/jdbc/h2/h2-1.3.176.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process7051249755319146524properties
...
```
