### ISSUE TITLE
Execution permission is not set by default

### ISSUE THREAD

**Issue by vishalkirandesai** [SonarSource/docker-sonarqube#152]
If you build an image using the `Dockerfile` and `run.sh` provided for 7.0 alpine, the run.sh file copied does not have permission for execution `-rw-r--r--`. But, it seems the image uploaded to Docker hub has the permissions set and works well. Perhaps a `chmod` command is missing in the `Dockerfile` that is on github. I would love to be wrong in this situation, In that case, something very interesting is happening and I would be glad to learn from it. Thank you.

**Comment by Godin** [comment]
@vishalkirandesai here is my local build procedure, which is identical (not counting tag name) to build in Travis and for Docker hub:

```
$ git clone https://github.com/SonarSource/docker-sonarqube.git
$ cd docker-sonarqube/7.0-alpine
$ docker build -t test .
```

Source file `run.sh` has executable bit after clone:
```
$ ls -lA run.sh
-rwxr-xr-x 1 godin godin 477 Mar  5 21:47 run.sh
```

And thus also has executable bit inside container:

```
$ docker run -it --rm test bash

bash-4.4# ls /opt/sonarqube/bin/
total 4
-rwxr-xr-x    1 root     root           477 Mar  5 20:47 run.sh
```

Wild guess - are you building on Windows?

**Comment by vishalkirandesai** [comment]
Aha! I didn't clone the repo rather made a file on my local and copied the contents from the run.sh file, and it apparently did not have execution permissions. 
Not on Windows :), Using HS 10.13.2
Thank you so much.
