### ISSUE TITLE
6.7.2-alpine version not found as per documentation

### ISSUE THREAD

**Issue by arulrajnet** [SonarSource/docker-sonarqube#153]
The document said 6.7.2-alpine is available. 

![image](https://user-images.githubusercontent.com/834529/37513914-623da896-292c-11e8-983f-94cec31ca040.png)

But there is no such tag in docker. 

![image](https://user-images.githubusercontent.com/834529/37513978-946aaa08-292c-11e8-8eef-21161c1a8fd4.png)

**Comment by Godin** [comment]
Questions about inconsistencies in UI of hub.docker.com should be addressed to its maintainers.
And right now all is fine:

![library_sonarqube_-_docker_hub](https://user-images.githubusercontent.com/138671/37520522-b801b402-291d-11e8-9ac4-2402b693c149.png)

**Comment by arulrajnet** [comment]
@Godin Seems that version of docker image not pushed to hub.docker.com. That's why its not showing in docker hub. Now everything is fine after you pushed the image with that tag. Thanks

**Comment by arulrajnet** [comment]
@Godin Got it. Thanks for the clarification.
