### ISSUE TITLE
Support for docker secrets

### ISSUE THREAD

**Issue by dotslashme** [SonarSource/docker-sonarqube#156]
Not sure if this is already supported, but I would love to have support for docker secrets in Sonarqube. Having to specify the database user/password directly in my compose file, prevents me from using versioning software.

**Comment by simonbrandhof** [comment]
I may be wrong but Docker secrets are supported by the swarm mode only, so they are out of the scope of this image. The best alternative is that you build your own image.

**Comment by zaazi** [comment]
Secrets are supported both my Docker compose and Docker swarm, but afaik compose only supports internal secrets. However, a mechanism to support docker secrets is not hard to implement and it only requires fetching the value from a file mounted under /run/secrets/<secret_name> and then exposing it like an environmental variable like so:
<secret_name>=<value_from_file>

I do it myself with a small bash script like this:
`#!/usr/bin/env bash

pass=$(cat /run/secrets/sonar-db-password)
export SONARQUBE_JDBC_PASSWORD="$pass"

exec "$@"`

However, it would be nice if I didn't have to extend the image myself, but rather the entrypoint of the image could take an argument that would read such a file instead.

**Comment by michal-duda-sonarsource** [comment]
Versioning docker-compose files is still possible with the current image. Instead of passing the environment variables you can mount the `conf` directory which contains full SQ configuration in `sonar.properties` file.

**Comment by dotslashme** [comment]
> Versioning docker-compose files is still possible with the current image. Instead of passing the environment variables you can mount the conf directory which contains full SQ configuration in sonar.properties file.

Yes, but then where do I store the config files? The whole point of the ticket is to be able to have all my configs in versioning software and keep secrets specifically out of it.

**Comment by nixel2007** [comment]
ansible vault?

**Comment by johnqa** [comment]
are there any updates on this? I saw there is a pull request on this but I don't think is integrated in any version.

**Comment by khooz** [comment]
Please consider both docker configs and docker secrets as these will help creating cleaner compose files AND images.

> Docker swarm service configs allow you to store non-sensitive information, such as configuration files, outside a service’s image or running containers. This allows you to keep your images as generic as possible, without the need to bind-mount configuration files into the containers or use environment variables.
_ [Store configuration data using Docker Configs](https://docs.docker.com/engine/swarm/configs/)

> You can use secrets to manage any sensitive data which a container needs at runtime but you don’t want to store in the image or in source control
_ [Manage sensitive data with Docker secrets](https://docs.docker.com/engine/swarm/secrets/)

**Comment by rprodan** [comment]
@sonarcloud is there any reflection or progress on this topic?

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi all,
we have created [DOCKER-2](https://jira.sonarsource.com/browse/DOCKER-2) to track this and will close this issue for now
