### ISSUE TITLE
Fail to unzip plugin [csharp]

### ISSUE THREAD

**Issue by yooouuri** [SonarSource/docker-sonarqube#157]
Im getting this error with all versions

> java.lang.IllegalStateException: Fail to unzip plugin [csharp] /opt/sonarqube/extensions/plugins/sonar-csharp-plugin-6.5.0.3766.jar to /opt/sonarqube/temp/ce-exploded-plugins/csharp
> at org.sonar.ce.container.CePluginJarExploder.explode(CePluginJarExploder.java:56)
> at org.sonar.core.platform.PluginLoader.defineClassloaders(PluginLoader.java:92)
> at org.sonar.core.platform.PluginLoader.load(PluginLoader.java:72)
> at org.sonar.ce.container.CePluginRepository.start(CePluginRepository.java:73)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110)
> at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89)
> at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
> at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
> at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
> at org.picocontainer.behaviors.Stored.start(Stored.java:110)
> at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
> at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
> at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
> at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:134)
> at org.sonar.ce.container.ComputeEngineContainerImpl.start(ComputeEngineContainerImpl.java:182)
> at org.sonar.ce.ComputeEngineImpl.startup(ComputeEngineImpl.java:45)
> at org.sonar.ce.app.CeServer$CeMainThread.startup(CeServer.java:167)
> at org.sonar.ce.app.CeServer$CeMainThread.attemptStartup(CeServer.java:154)
> at org.sonar.ce.app.CeServer$CeMainThread.run(CeServer.java:141)
> Caused by: java.nio.channels.ClosedByInterruptException: null
> at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
> at sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:315)
> at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:1142)
> at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1091)
> at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038)
> at org.sonar.ce.container.CePluginJarExploder.explode(CePluginJarExploder.java:52)
> ... 22 common frames omitted

Docker version 17.12.0-ce, build c97c6d6
Mac OS 10.13.3 (17D102)

**Comment by Godin** [comment]
Can't reproduce.
