### ISSUE TITLE
aws recipe

### ISSUE THREAD

**Issue by snoworc** [SonarSource/docker-sonarqube#159]
Using this `Dockerrun.aws.json` file, the elastic beanstalk environment builds. However, it uses H2 db engine and does not utilize the mysql settings
```
{
  "AWSEBDockerrunVersion": "1",
  "Image": {
    "Name": "sonarqube:latest"
  },
  "Ports": [{
    "HostPort": "9000",
    "ContainerPort": "9000"
  }],
  "environment": [{
      "name": "SONARQUBE_JDBC_PASSWORD",
      "value": "***"
    },
    {
      "name": "SONARQUBE_JDBC_URL",
      "value": "jdbc:mysql://***.us-east-1.rds.amazonaws.com:3306/ebdb"
    },
    {
      "name": "SONARQUBE_JDBC_USERNAME",
      "value": "***"
    }
  ]
}
```

```
Database | H2
-- | --
Database Version | 1.3.176 (2014-04-05)
Username | SONAR
URL | jdbc:h2:tcp://127.0.0.1:9092/sonar
Driver | H2 JDBC Driver
Driver Version | 1.3.176 (2014-04-05)
```

I verified and can connect to the jdbc URL w/ these credentials using Sequel Pro

I am using a single docker container (AWSEBDockerrunVersion: "1"). Do I need to use a multi-container setup? Anyone have a working recipe example if so?

**Comment by Godin** [comment]
This is not a Q/A forum. Please use https://www.sonarqube.org/community/feedback/ for access to wider audiences of people who can help/answer than watchers of this repository. Thank you for your understanding.
