### ISSUE TITLE
document volumes

### ISSUE THREAD

**Issue by magnus919** [SonarSource/docker-sonarqube#16]
The current Dockerfile defines two different volumes. I saw a question on Docker Hub about whether or not there are volumes on this image, so it's probably worth having some doc around that.

**Comment by Godin** [comment]
Docs for Docker Hub are located in https://github.com/docker-library/docs/tree/master/sonarqube Feel free to open PR and suggest change.

**Comment by dhoer** [comment]
Can those volumes be removed from the Dockerfile and replaced with docker and docker-compose examples on how to mount using volumes in the readme.  Having volumes defined in the Dockerfile makes a trivial task of adding plugins complex.

**Comment by Godin** [comment]
@dhoer hm, your proposal conflicts with what other people propose - #44 , #56 
As a maintainer of this repository I'm fine to accept either of solutions, given good argumentation for it.
So feel free to elaborate more here about Docker best practices about this subject and provide patch.

**Comment by LorenzoBettini** [comment]
I'm kind of a newbie with Docker, but how would volumes defined in the Dockerfile get in your way when using mounted directories or when using docker-compose? As far as I know, the ones defined in the docker-compose would still work and if you mount a local directory that would take the precedence... or am I missing something?

**Comment by Godin** [comment]
See some advices for SonarQube image from @tianon about volumes in https://github.com/docker-library/official-images/pull/2437#issuecomment-266573937

**Comment by pierre-guillot-sonarsource** [comment]
we updated the doc month ago
