### ISSUE TITLE
SONARQUBE_HOME environment variable ignored

### ISSUE THREAD

**Issue by maxhov** [SonarSource/docker-sonarqube#162]
When running SonarQube (7.0-alpine) on Azure AppServices, I cannot persist extensions. The SONARQUBE_HOME environment variable seems to be ignored, which causes plugins to be installed in /opt/sonarqube/extensions/plugins instead of $SONARQUBE_HOME/extensions/plugins. Azure AppServices require that all data that needs to be persisted is placed inside the /home folder. I would expect the $SONARQUBE_HOME parameter to be the base folder for all files/folders (such as conf/ data/ extensions/), as described here: https://docs.sonarqube.org/display/SONAR/Installing+a+Plugin.

Please advice how to set the extensions/plugins folder to a (sub) directory of /home.

**Comment by snehamahesh** [comment]
Here is a workaround that worked to install a plugin:
- `export SONARQUBE_HOME=<your-dir>`
-  `mkdir -p ${SONARQUBE_HOME}/extensions/plugin`
- `cp your-desired-plugin.jar ${SONARQUBE_HOME}/extensions/plugin/.`
-  include volume mount to the docker run as:
 `-v ${SONARQUBE_HOME}/extensions:/opt/sonarqube/extensions:z`

**Comment by pierre-guillot-sonarsource** [comment]
I'm closing this since there has been no update for a while. Please retry with the latest SQ version and create a new issue if needed, with more details and logs.
