### ISSUE TITLE
How is the right way to run it?

### ISSUE THREAD

**Issue by albertorm95** [SonarSource/docker-sonarqube#166]
Hello, I'm trying to use this software for the first time, I'm running it on a RedHat VM with Docker, and I can access the service thru the browser but I don't know how to start using it, I want to use it with Jenkins, any document that I can use?, my project is on NodeJS

**Comment by Godin** [comment]
Hello, excuse me, but http://lmgtfy.com/?q=sonarqube+documentation => https://docs.sonarqube.org/
