### ISSUE TITLE
SonarQube terminates after attempted handshake with ELS with no information

### ISSUE THREAD

**Issue by jwitko** [SonarSource/docker-sonarqube#167]
Hello,  I am having an issue getting SonarQube to run inside a docker container.  I have tried with both versions `lts` and `latest`, both report the same issue.  I enabled TRACE logging globally but it does not provide any useful information.   From the logs I would think it is telling me its failing on the handshake but I have confirmed (many times at this point) that traffic can freely flow from the container to the elasticsearch server.  Any help you could provide would be appreciated.

sonar.properties:
```
[root@us-east-1d-prod-swarm-general-slave14290 ~]# cat sonar.properties
sonar.search.port=9200
sonar.search.host=us-east-1-prod-els1
sonar.log.level=TRACE
```

network connection OK:
```
[root@us-east-1d-prod-swarm-general-slave14290 ~]# telnet us-east-1-prod-els1 9200
Trying 10.0.134.213...
Connected to us-east-1-prod-els1.throtledmp.internal.
Escape character is '^]'.
^]
telnet> quit
Connection closed.
```

Sonar Trace Logs:
https://gist.githubusercontent.com/jwitko/2986f357432d46efcb3ac459ba39ab28/raw/4ad8ba4c4a274594e31b56fc01f9f259b6b8df86/sonarqube.log

**Comment by jwitko** [comment]
Does sonarqube require a minimum version of ELS maybe ?

**Comment by simonbrandhof** [comment]
The errors are missing from your logs. Please have a look at the file `logs/es.log`.

**Comment by jwitko** [comment]
The concept was to use an elasticsearch external to the container, but there is no longer a need from this on my end.  I'll close this issue.

**Comment by simonbrandhof** [comment]
Thanks. And I confirm that anyway connecting to a remote Elasticsearch instance is not supported.
