### ISSUE TITLE
Dockerfile 7.1-alpine fails when building

### ISSUE THREAD

**Issue by SleepingTalent** [SonarSource/docker-sonarqube#170]
The docker file for the 7.1-alpine version is failing when I try to build it.
 
Looks like it is failing at the following line
```
    && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys F1182E81C792928921DBCAB4CFCA4A29D26468DE \

```
With the output
```+ gpg --keyserver ha.pool.sks-keyservers.net --recv-keys F1182E81C792928921DBCAB4CFCA4A29D26468DE
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: keyserver receive failed: End of file
```
Any ideas how I would resolve this?

I am not behind a firewall and I am able to hit in a browser
```
http://ha.pool.sks-keyservers.net/
```

**Comment by Godin** [comment]
Despite name being `ha` (high availability) this pool sometimes gives unavailable servers, to overcome - run build several times, or simply use prebuilt image - https://hub.docker.com/_/sonarqube/
