### ISSUE TITLE
Cannot run on OpenShift or a secure Kubernetes cluster

### ISSUE THREAD

**Issue by derkoe** [SonarSource/docker-sonarqube#171]
The sonarqube image cannot be run on an OpenShift or a secure Kubernetes cluster (https://kubernetes.io/blog/2016/08/security-best-practices-kubernetes-deployment/). Both run containers as non-root or an arbitrary user. 

For OpenShift the start of the container fails on `chown` in `run.sh`. Another problem is the `gosu` and `su-exec` (for alpine).

It would be great to change this images to support non-root containers.

**Comment by dhongyt** [comment]
@derkoe Were you able to get pass this? I used this image for Openshift,
https://github.com/OpenShiftDemos/sonarqube-openshift-docker

But right now my issue is that after it deploys and its working, I do a #2 deployment and it breaks with ES returning an error 1, saying that ES can't be ran as a non root.

**Comment by derkoe** [comment]
Use the nonroot branch in our fork - https://github.com/porscheinformatik/docker-sonarqube/tree/nonroot

I've also created a repo on DockerHub for this branch: https://hub.docker.com/r/porscheinformatik/sonarqube/
(builds are still running)

**Comment by jimk-osu** [comment]
I'm also rolling a delta built the same as @derkoe's in Kube.

**Comment by janos-ss** [comment]
We've just released official images of SonarQube Community Edition 7.4 and 6.7.6, available on the [hub](https://hub.docker.com/_/sonarqube/). The `run.sh` in those images doesn't do `chown` anymore. Do you still experience issues with these new images?

**Comment by nicbet** [comment]
For me in `OpenShift` cluster running `sonarqube:7.4-community` fails with:

```
2018.11.30 18:16:01 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
--
  | Exception in thread "main" java.nio.file.AccessDeniedException: /opt/sonarqube/temp/README.txt
  | at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
  | at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
  | at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
  | at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
  | at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
  | at java.nio.file.Files.delete(Files.java:1126)
  | at org.sonar.application.AppFileSystem$CleanTempDirFileVisitor.visitFile(AppFileSystem.java:121)
  | at org.sonar.application.AppFileSystem$CleanTempDirFileVisitor.visitFile(AppFileSystem.java:101)
  | at java.nio.file.Files.walkFileTree(Files.java:2670)
  | at org.sonar.application.AppFileSystem.createOrCleanTempDirectory(AppFileSystem.java:96)
  | at org.sonar.application.AppFileSystem.reset(AppFileSystem.java:62)
  | at org.sonar.application.App.start(App.java:55)
  | at org.sonar.application.App.main(App.java:78)
```

**Comment by janos-ss** [comment]
Thanks @derkoe for the additional info. I took a look at your [`nonroot` branch](https://github.com/porscheinformatik/docker-sonarqube/commit/5101a72c04756d02e79a5f64e09f3491e9eed75f), and I can see that with your changes, running with `docker run -u 10101:0 --rm` works. It still doesn't work with `--read-only` (options 1 and 3 in your last message), is that expected?

**Comment by derkoe** [comment]
I updated the branch to also adress this (our cluster does not have readOnlyRootFilesystem).

You should decalare all mutable folders as a volume, see: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#volume

**Comment by tobias-trabelsi-sonarsource** [comment]
This thread is now over 2 years stale, so i will go ahead and close it. for everyone interested in k8s deployments there is also now a [helm chart offered by sonarsource](https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube) that might help
