### ISSUE TITLE
Python doesn't work

### ISSUE THREAD

**Issue by ethans** [SonarSource/docker-sonarqube#174]
I'm running the sonar-scanner from another docker image. This works great for a .java file, but when there's a .py file, it hangs at:
INFO: Quality profile for py: Sonar way
INFO: Sensor Python Squid Sensor [python]

This is even for a python file that contains only:
print "Hello World"

**Comment by Godin** [comment]
This is an issue tracker of a Docker image. For the general questions about SonarQube and its usage please follow https://www.sonarqube.org/community/

**Comment by ethans** [comment]
Since I assume that SonarQube works with Python on the regular distribution - I can only assume that there's something missing in the installation packages of the alpine linux image. That's why I'm opening the bug here.
Please reopen @Godin

**Comment by Godin** [comment]
@ethans Docker image provides SonarQube **server**, while analysis is executed in other environments - clients of this server. Therefore once again - please discuss your inability to execute Python Plugin via https://www.sonarqube.org/community/

**Comment by ethans** [comment]
OK, thank you and sorry for the trouble
