### ISSUE TITLE
failed connection to github 

### ISSUE THREAD

**Issue by sarrazitouni** [SonarSource/docker-sonarqube#177]
hello
i have this error  
wget -O /usr/local/bin/gosu https://github.com/tianon/gosu/releases/download/1.10/gosu-amd64
--2018-05-18 08:26:10--  https://github.com/tianon/gosu/releases/download/1.10/gosu-amd64
failed connection timeout

does anyone knows this issue ? thank you

**Comment by aliaskovski** [comment]
---> Running in c13bee7f8df8
+ dpkg --print-architecture
+ wget -O /usr/local/bin/gosu https://github.com/tianon/gosu/releases/download/1.10/gosu-amd64
--2018-07-09 11:21:36--  https://github.com/tianon/gosu/releases/download/1.10/gosu-amd64
Resolving github.com (github.com)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘github.com’
ERROR: Service 'sonarqube' failed to build: The command '/bin/sh -c set -x     && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/1.10/gosu-$(dpkg --print-architecture)"     && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/1.10/gosu-$(dpkg --print-architecture).asc"     && export GNUPGHOME="$(mktemp -d)"     && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4     && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu     && rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc     && chmod +x /usr/local/bin/gosu     && gosu nobody true' returned a non-zero code: 4

**Comment by Godin** [comment]
All this is about **your network connection**.
