### ISSUE TITLE
sonarqube 7.2

### ISSUE THREAD

**Issue by simbas** [SonarSource/docker-sonarqube#182]
Hello,

Sonarqube 7.2 seems out (https://www.sonarqube.org/sonarqube-7-2/). Is it possible to add this version as a docker image tag?

Thank you

**Comment by Godin** [comment]
Let me quote announcement of SonarQube 7.2 made by @ganncamp at https://community.sonarsource.com/t/sonarqube-7-2-released/302 :

> There’s no Docker image (on purpose, we didn’t forget!) for this version.

Long story short: one of the reasons is that packaging of SonarQube has changed in 7.2 and now it comes in several editions, which raises some questions about SonarQube distribution as a Docker image. These questions first must be answered before making official distribution of the latest SonarQube via Docker.

In the meantime feel free to create your own `Dockerfile` to build image containing version of SonarQube of your choice.

Thank you for your understanding.

**Comment by simbas** [comment]
@Godin thank you!

**Comment by DuAell** [comment]
Would be nice to leave this open so we can have a notification when the docker image is ready

**Comment by sintetico82** [comment]
If someone have a compatible Dockerfile for 7.2 can share please?

**Comment by allustin** [comment]
@Godin 

why so much functionality is turned off last year from the version for the community? squid, docker, ce.workercount, branches, etc

And the prices for the version for developers are such that the uninvolved developers simply can not afford it.

**Comment by simonbrandhof** [comment]
@allustin you misread the answer from @Godin. The new versions of the Docker image will be released later. Please stay tuned.

I suggest to open a thread on http://community.sonarsource.com/ if you want to share your feedback with the community. I will be pleased to answer that squid (at least the squid I know) is SonarJava and is still open-source, and that branches have never really been supported (the old parameter `sonar.branch` was only about changing the project key to avoid conflicts).

**Comment by allustin** [comment]
@simbas https://github.com/jincod/docker-sonarqube 


```
git clone https://github.com/jincod/docker-sonarqube 
cd docker-sonarqube/7.2
docker build -t sonarqube:7.2 .
cd ../7.2-apline
docker build -t sonarqube:7.2-alpine .
```

**Comment by tburow** [comment]
Bump: any update on a 7.2 container release? - thanks

**Comment by janos-ss** [comment]
We've just released official images of SonarQube Community Edition 7.4 and 6.7.6, available on the [hub](https://hub.docker.com/_/sonarqube/).

**Comment by degree** [comment]
@janos-ss How do we get Developer Edition? Community Edition + installed License and "Developer plugin? TIA

**Comment by janos-ss** [comment]
@degree I think, but haven't tested, you could build an image, replacing the download link with that of the Developer Edition (see the [downloads page](https://www.sonarqube.org/downloads/)), and then enter the license. You should not need to install "License" or "Developer" plugins. The zip contains everything needed, ready to use.

**Comment by mwz** [comment]
Hi @janos-ss, it looks like the alpine images haven't been pushed to dockerhub.

**Comment by janos-ss** [comment]
Hi @mwz, we don't support Alpine-based builds. As of today, OpenJDK 8 does not officially support Alpine. As such, we don't know a good base image to build on. We did try the unsupported `openjdk:8-alpine` image as base, and we saw nonsense problems with nonsense workarounds. We've left the recipes for Alpine-based images in the branch named `alpine`, build and use at your own risk.

**Comment by madnight** [comment]
@janos-ss could you tell what kind of bugs occurred?
