### ISSUE TITLE
Cannot allocate memory on container start

### ISSUE THREAD

**Issue by eiriarte-mendez** [SonarSource/docker-sonarqube#185]
can anybody tell me something about this error:

```
$ docker run -p 9000:9000 -p 9092:9092 sonarqube
2018.07.01 19:54:34 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2018.07.01 19:54:34 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2018.07.01 19:54:34 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch -Epath.conf=/opt/sonarqube/temp/conf/es
2018.07.01 19:54:34 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000ea660000, 362414080, 0) failed; error='Cannotallocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 362414080 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /opt/sonarqube/elasticsearch/hs_err_pid22.log
2018.07.01 19:54:34 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 1
2018.07.01 19:54:34 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
2018.07.01 19:54:34 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
```

BTW, Im getting same error with `sonarqube:latest` (`7.1`) and `sonarqube:6.7.4`

```
$ uname -a
Linux ubuntu-xenial 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ docker --version
Docker version 18.03.1-ce, build 9ee9f40
```

other containers seems to be working fine 😢

**Comment by DinoSourcesRex** [comment]
@eiriarte-mendez SonarQube uses Elasticsearch, which by default requires 2GB to memory. I suspect you don't have 2GB of memory left, it says you're missing 362.4mb, so bump up your memory if you can.

I have a similar issue. I am try to setup SonarQube to run with only 1GB of memory, however overwriting the default Java memory limit with an environment variable doesn't seem to work.

Does anyone have any ideas?
`docker run --rm -e ES_JAVA_OPTS="-Xms1g -Xmx1g" --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube` is what I a running.

**Comment by Godin** [comment]
@eiriarte-mendez 

> There is insufficient memory for the Java Runtime Environment to continue.

and so @DinoSourcesRex is right that you don't have enough memory.

----

@DinoSourcesRex 

> SonarQube uses Elasticsearch, which by default requires 2GB to memory

by default SonarQube versions from `6.7` to `7.2` start Elasticsearch with `-Xmx512m` - proof from `logs/es.log`:

```
2018.07.08 13:03:28 INFO  es[][o.e.n.Node] JVM arguments [-XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -Xms512m, -Xmx512m, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/opt/sonarqube/elasticsearch]
```

> however overwriting the default Java memory limit with an environment variable doesn't seem to work

see `conf/sonar.properties` (e.g. its source at https://github.com/SonarSource/sonarqube/blob/7.0/sonar-application/src/main/assembly/conf/sonar.properties#L215 ) for defaults and how to change them, therefore

```
docker run -it --rm sonarqube -Dsonar.search.javaAdditionalOpts=-Xmx1g
```

P.S. this is not Q/A forum - for questions please use https://community.sonarsource.com/ in future

**Comment by DinoSourcesRex** [comment]
@Godin I came here from https://hub.docker.com/_/sonarqube/, where it tells people to come here to get help. That community you referenced isn't on that page. Perhaps it should be added so that others avoid confusion?

For what it's worth that command did not succeed, but I can continue that discussion in the community, thanks.

**Comment by DinoSourcesRex** [comment]
@Godin I didn't want to go into it because, as you said, this is not a Q/A forum.

Since we're getting into it here, though. I am running this on a DigitalOcean Droplet, the lowest tier. When I run the command the container starts, yes, however after a few seconds it exists.

```
docker run -it --rm --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube -Dsonar.search.javaAdditionalOpts=-Xmx512m
Unable to find image 'sonarqube:latest' locally
latest: Pulling from library/sonarqube
0bd44ff9c2cf: Pull complete
047670ddbd2a: Pull complete
ea7d5dc89438: Pull complete
ae7ad5906a75: Pull complete
a71f22008abf: Pull complete
e56f7360809f: Pull complete
f1832923672a: Pull complete
8cb1c4b78c42: Pull complete
4c723e720bda: Pull complete
28d4741c5e5f: Pull complete
424517a91363: Pull complete
1dd072e3f35d: Pull complete
f7cfa3f1dfee: Pull complete
Digest: sha256:dd6d5fa6b0977471bafc4a05524de4fe115dd90d1224cb216ab823f014dacd3f
Status: Downloaded newer image for sonarqube:latest
2018.07.08 17:44:55 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2018.07.08 17:44:55 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2018.07.08 17:44:55 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch -Epath.conf=/opt/sonarqube/temp/conf/es
2018.07.08 17:44:55 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2018.07.08 17:44:56 INFO  app[][o.e.p.PluginsService] no modules loaded
2018.07.08 17:44:56 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2018.07.08 17:45:20 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
2018.07.08 17:45:21 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/opt/sonarqube]: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -cp ./lib/common/*:/opt/sonarqube/lib/jdbc/h2/h2-1.3.176.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process5735665229548596531properties
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000e0000000, 44695552, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 44695552 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /opt/sonarqube/hs_err_pid85.log
2018.07.08 17:45:23 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [web]: 1
2018.07.08 17:45:23 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
2018.07.08 17:45:25 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143
2018.07.08 17:45:25 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
2018.07.08 17:45:25 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
```

**Comment by Godin** [comment]
@DinoSourcesRex as was said in https://github.com/SonarSource/docker-sonarqube/issues/185#issuecomment-403286381 `-Xmx512m` is already default, so you are not changing anything. Also keep in mind that there 2 other JVMs with default `-Xmx512m` - "ce" and "web", and heap is just a part of memory that JVM uses. Default values are already quite low and usually require increase for proper functioning of SonarQube. So rather than reducing them, consider increasing amount of available memory.

**Comment by DinoSourcesRex** [comment]
@Godin I didn't realise there were 2 other JVM's - that's probably where it's slipping up. There's only 1GB of RAM on the machine. Is there any way to configure the other JVM's so that I can get everything within that limit?

**Comment by Godin** [comment]
@DinoSourcesRex 

> Is there any way to configure the other JVM's

as already was mentioned in https://github.com/SonarSource/docker-sonarqube/issues/185#issuecomment-403286381 : please have a **careful** look at `conf/sonar.properties`, which in addition to `sonar.search.javaAdditionalOpts` describes `sonar.web.javaAdditionalOpt`, `sonar.ce.javaAdditionalOpts` and many other things

> so that I can get everything within that limit

IMO this is a way to far more troubles -  https://github.com/SonarSource/docker-sonarqube/issues/185#issuecomment-403305276 :

> Default values are already quite low and usually require increase for proper functioning of SonarQube. So rather than reducing them, consider increasing amount of available memory.

**Comment by DinoSourcesRex** [comment]
It is only for personal use so it isn't going to be getting much load. I'd have thought 1GB would be enough. I was also hoping to be able to do this via environment variables rather than config, but I guess I'll have to take a look.

Thanks for your help.

**Comment by Godin** [comment]
@DinoSourcesRex you are not forced to do this in config file - as was already shown in https://github.com/SonarSource/docker-sonarqube/issues/185#issuecomment-403286381 you can specify all them in command-line :

```
docker run -it --rm sonarqube  -Dsonar.search.javaAdditionalOpts=... -Dsonar.web.javaAdditionalOpt=...
```

**Comment by DinoSourcesRex** [comment]
@Godin I meant more that I would have to look into the file to familiarise myself with what is in there. I am not familiar with the `-D` flag to add / amend options so I need to see what's available.
