### ISSUE TITLE
Running sonarqube in Docker with envoyproxy to https

### ISSUE THREAD

**Issue by Jaff** [SonarSource/docker-sonarqube#188]
Good documentation here https://docs.sonarqube.org/display/SONAR/Securing+the+Server+Behind+a+Proxy for setup (examples for NGINX & apache mod_proxy). We're using https://www.envoyproxy.io/docs/envoy/ and need to configure connection for https. Anyone here done similar setup?

**Comment by Godin** [comment]
This is not a Q/A forum. Please use https://community.sonarsource.com/ for access to wider audiences of people who can help/answer than watchers of this repository. Thank you for your understanding.

P.S. second link shows "404 page not found"
