### ISSUE TITLE
Would it be possible to host the public key in an S3 bucket rather than sks-keyservers.net?

### ISSUE THREAD

**Issue by CameronGo** [SonarSource/docker-sonarqube#201]
That endpoint seems to be very unreliable.  If the public key were pulled from an S3 bucket (or really anywhere else) instead, it would make it easier for others to contribute to the docker image.  Right now its very hit or miss if the build process works or not.

**Comment by pierre-guillot-sonarsource** [comment]
Please can you describe why this store is not reliable ?
