### ISSUE TITLE
Suggestion to change default path for data and extensions to improve volume persistence

### ISSUE THREAD

**Issue by CameronGo** [SonarSource/docker-sonarqube#202]
I'd like to suggest that the /data and /extensions locations be moved outside of the SONARQUBE_HOME path by default as part of the public image.  A preferable location might be /var/lib/sonarqube or alternatively /var/opt/sonarqube with subfolders for ./data and ./extensions. This should make it easier to provision file persistence for these locations using volume mapping to persistent block storage.

My pilot deployment is deployed in an ECS service (AWS) using a storage driver to mount an EBS volume to the sonarqube web service, but I believe the same concept would apply to any container scheduling service that handles volume mapping in a similar way.

In ECS I can define a volume (EBS volume in this case) and mount it to a file system location in the container.  In doing this; however, I can only define the volume and the container path (not an additional file system path in the volume as well).  In this case I have mapped a volume called sonarqube to both /opt/sonarqube/data and also map the same volume to /opt/sonarqube/extensions.  This; however, has the undesirable result of having both the elasticsearch and extension data intermingled in the same hierarchy of folders.

Directory listing as an example:
```
root@94eedac4de18:/opt/sonarqube# ls -alh /opt/sonarqube/data
total 28K
drwx------ 6 sonarqube sonarqube 4.0K Sep 19 17:13 .
drwxr-xr-x 1 sonarqube sonarqube 4.0K Apr 17 08:17 ..
-rw-r--r-- 1 sonarqube sonarqube  115 Apr 17 08:14 README.txt
drwxr-xr-x 2 sonarqube sonarqube 4.0K Sep 19 17:13 downloads
drwxr-xr-x 3 sonarqube sonarqube 4.0K Sep 19 17:08 es5
drwxr-xr-x 2 sonarqube sonarqube 4.0K Sep 19 17:13 plugins
drwxr-xr-x 3 sonarqube sonarqube 4.0K Sep 19 17:08 web
```

Alternative options I've considered:
- Create 2 separate EBS volumes so that they can each be independently mounted to distinct paths (/opt/sonarqube/data and /opt/sonarqube/extensions).  This is potentially acceptable, but seems unnecessarily complicated on the scheduler side as there is one more volume to coordinate access for, mount, provision, backup, etc.  This could also prove challenging if/when there are any other variable data structures that should persist across reboots as each new data structure would need its own volume provisioned to keep them from intermingling in the same path.
- Modify the sonarqube config files to point the elasticsearch and extensions path to the desired location, such as /var/opt/sonarqube and then mount the volume the way I want.  This can work as well, but IMO the most desirable solution is one that allows everyone to use the public official docker image in a production environment without having to customize or maintain the image independently.

Here's some of the relevant meta data about my docker container to demonstrate how it is currently deployed:
```
        "Mounts": [
            {
                "Type": "volume",
                "Name": "sonarqube",
                "Source": "",
                "Destination": "/opt/sonarqube/data",
                "Driver": "rexray/ebs:latest",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "sonarqube",
                "Source": "",
                "Destination": "/opt/sonarqube/extensions",
                "Driver": "rexray/ebs:latest",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "JAVA_HOME=/docker-java-home",
                "JAVA_VERSION=8u181",
                "JAVA_DEBIAN_VERSION=8u181-b13-1~deb9u1",
                "CA_CERTIFICATES_JAVA_VERSION=20170531+nmu1",
                "SONAR_VERSION=7.1",
                "SONARQUBE_HOME=/opt/sonarqube"
            ],

**Comment by janos-ss** [comment]
I must be missing something. With Docker alone, I can map these paths to whatever physical volumes I want, for example:

```
docker run -d --name sonarqube \
    -p 9000:9000 \
    -v /var/lib/sonarqube/data:/opt/sonarqube/data \
    -v /var/lib/sonarqube/extensions:/opt/sonarqube/extensions \
    sonarqube
```

Can't you do the equivalent? I don't see why the paths inside the image are important at all, when they could be mapped to whatever paths outside.

**Comment by CameronGo** [comment]
Sure - the issue isn't with mapping the volume to a local path, but in a prod environment where the hosts are ephemeral, you'd use named volumes rather than a local path.  So, as an example in our environment we create a persistent volume named sonarqube_vol; this volume could be mounted to any host in the environment at run time, but with the docker syntax you can't specify a named volume along with a path.  So, the net result is that the mount points for the container config in prod end up looking like this:
```
      "mountPoints": [
        {
          "readOnly": null,
          "containerPath": "/var/sonarqube",
          "sourceVolume": "sonarqube_vol"
        },
        {
          "readOnly": null,
          "containerPath": "/opt/sonarqube/extensions",
          "sourceVolume": "sonarqube_vol"
        }
      ],
```
Or if you were using docker-compose.yml, here's how a similar config would look:
```
version: '3'

services:
  sonarqube:
    build: ..
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_VOL=/var/sonarqube
    depends_on:
      - db
    links:
      - db
    ports:
      - "9001:9000"
    volumes:
      - sonarqube_vol:/var/sonarqube
      - sonarqube_vol:/opt/sonarqube/extensions

  db:
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar

volumes:
  sonarqube_vol:
```
To be fair - there is an alternative I mentioned above of creating 2 discreet volumes for the data and the extensions, but mounting 2 volumes at runtime and and backing them up independently seems like unnecessary overhead compared to just being able to mount 1 volume and keep those files in separate subfolders.

**Comment by Sviatik** [comment]
Agreed with @CameronGo 
Have the same issue with trying to deploy to azure container instance. It's impossible to mount 2 volume via cli, only via arm, but that raise another problems with network. 
It will be gread to have 1 volume to mount instead two.

**Comment by pierre-guillot-sonarsource** [comment]
sq8 images will be shipped with symlink for mutable folder, allowing users to easily map them to folders or volume.
