### ISSUE TITLE
Configuration file not found: /opt/sonarqube/conf/sonar.properties when mapping volumes for the data persistence

### ISSUE THREAD

**Issue by cqison** [SonarSource/docker-sonarqube#208]
Hi,

I'd like to mapping volumes from docker container to my local for the data persistence, so I run docker command as below:

$ docker run -d --name sq -p 9000:9000 **-v /vol01/sonar_conf:/opt/sonarqube/conf** --link=mysql  -e SONARQUBE_JDBC_USERNAME=sonaruser -e SONARQUBE_JDBC_PASSWORD=sonarpwd -e SONARQUBE_JDBC_URL="jdbc:mysql://mysql:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false" sonarqube:6.7.5

SonarQube6.7.5 is up and working fine, but got the following warn message:
[main] WARN org.sonar.application.config.AppSettingsLoaderImpl - Configuration file not found: /opt/sonarqube/conf/sonar.properties

And $ ls /mnt/sonar_conf, got nothing:
sonar@sonarqube:/vol01/sonarconf> ll
total 0

In container $ ls /opt/sonarqube/conf got nothing either: 
root@71fbeb6ec326:/opt/sonarqube/conf# ls
root@71fbeb6ec326:/opt/sonarqube/conf#

Does anyone met the same problem? please help!

Thanks,
Prince

**Comment by nixel2007** [comment]
You don't map directory from containter to host. you map it *from* host to container.
So when you run docker with this -v setup you overwrite /opt/sonarqube/conf in containter by your empty /vol01/sonar_conf dir

**Comment by cqison** [comment]
Thanks @nixel2007 for the clarification! 
But it's odd that for Mysql docker is working with the same way(the /vol01/mysql folder is empty as well as sonarqube.), when I execute "docker run ... -v /vol01/mysql:/var/lib/mysql ...", it works for me, both container and host have the same directory tree structure(including all files).

**Comment by shyingsheng** [comment]
I have the same problem when I want to start a docker with volumn -v /home/sonar/conf:/opt/sonarqube/conf. I just want to make the /opt/sonarqube/conf easy to access and configure by using volumn.
