### ISSUE TITLE
6.7.6-community fails on kubernetes: mkdir: cannot create directory ‘/scripts’: Permission denied

### ISSUE THREAD

**Issue by arthur-c** [SonarSource/docker-sonarqube#224]
Hi,

I tried to upgrade from 6.7.5 to 6.7.6-community but I have got this error in the logs:

`mkdir: cannot create directory ‘/scripts’: Permission denied
`
and the pod fails to start

It seems related to https://github.com/SonarSource/docker-sonarqube/pull/222

**Comment by kret** [comment]
Happens also for `7.4-community`...

**Comment by FrederikNS** [comment]
I get the same problem in `7.4-community`

**Comment by atolia** [comment]
use the helm version they have fixed that already
https://github.com/helm/charts/tree/master/stable/sonarqube

**Comment by thangbn** [comment]
the helm version is still having this error

**Comment by ahmedig** [comment]
> use the helm version they have fixed that already
> https://github.com/helm/charts/tree/master/stable/sonarqube

Nope they didnt.. the issue is still there.

**Comment by fernandosoaresjr** [comment]
Initially I had the same problem

First of all, update your repo
```
$ helm repo update
```
Than make sure you have the last version **0.10.3**
```
$ helm search sonarqube -l

NAME            	CHART VERSION	APP VERSION	DESCRIPTION                                       
stable/sonarqube	0.10.3       	6.7.6      	Sonarqube is an open sourced code quality scann...
stable/sonarqube	0.10.2       	6.7.6      	Sonarqube is an open sourced code quality scann...
stable/sonarqube	0.10.1       	6.7.3      	Sonarqube is an open sourced code quality scann...
stable/sonarqube	0.9.1        	6.7.3      	Sonarqube is an open sourced code quality scann...
...
```

Now you can install or upgrade
```
$ helm upgrade --values my-values.yaml  sonarqube stable/sonarqube
```

**Comment by pierre-guillot-sonarsource** [comment]
Looks like this is related to Helm and not belongs here
