### ISSUE TITLE
We've integrated SonarQube with teamcity for continues integration. SonarQube is generating reports in XML format. Is there any UI plugin which supports teamcity to import those XML files and present them in html format or any other graphical format?

### ISSUE THREAD

**Issue by ZenqDevSecOps** [SonarSource/docker-sonarqube#226]
Please ensure your issue adheres to the following guidelines: 

- [ ] Please check the problem is not already reported, or a known issue documented in [`develop.md`](develop.md)
- [ ] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs

**Comment by janos-ss** [comment]
I don't see how this is related to our Docker images. For questions about SonarQube's features please use the [Community Forum](https://community.sonarsource.com/).
