### ISSUE TITLE
Docker network

### ISSUE THREAD

**Issue by kilass** [SonarSource/docker-sonarqube#23]
Hi there ! 

Is there any way to make sonarqube and postgreSQL to work in a docker network ? 
I've tried many configurations, but stayed confused on how to make the jdbc connector work inside a network container.

Here is my docker-compose: 

sonarqube-database:
  container_name: sonarqube-db
  image: postgres:9.5.1
  volumes:
    - /home/apside/docker/sonar/postgres-data/:/var/lib/postgresql/data
  environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar
  restart: always
  net: "ic"
  
sonarqube:
  container_name: sonarqube
  image: sonarqube:5.4
  ports:
    - "9000:9000"
    - "5432:5432"
  volumes:
    - /home/apside/docker/sonar/extensions:/opt/sonarqube/extensions
    - /home/apside/docker/sonar/logs:/opt/sonarqube/logs
  dns: 10.1.37.15
  restart: always
  net: "ic"
  links:
    - sonarqube-database
  environment:
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar
    - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-database:5432/sonar

And here is the result of the `docker network inspect ic` command:
[
    {
        "Name": "ic",
        "Id": "f0c1ec62f5c7667d3f0f8b3bac18ab9e7a7ec3c55a3bb890c2970f46f016e4a4",
        "Scope": "local",
        "Driver": "bridge",
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1/16"
                }
            ]
        },
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true"
        }
    }
]

As you can see, i've tried enabling icc, and ip_masquerade, just in case, but with no real succes.

The problem is that the sonarqube container crash, as it can't connect to the database. 
Here is the exception sonarqube returns : 

 Exception sending context initialized event to listener instance of class org.sonar.server.platform.PlatformServletContextListener
java.lang.IllegalStateException: Can not connect to database. Please check connectivity and settings (see the properties prefixed by 'sonar.jdbc.').

Maybe something i didn't understood about docker networks ?

**Comment by Godin** [comment]
@kilass you can find working example in https://github.com/SonarSource/docker-sonarqube/blob/master/recipes.md
