### ISSUE TITLE
Docker images switches to sonarqube user that make problem to use image in CIs

### ISSUE THREAD

**Issue by romani** [SonarSource/docker-sonarqube#230]
Update to use sonarqube user in docker image as added here -https://github.com/SonarSource/docker-sonarqube/commit/03360969e395af585971e43971a84202baa87321#diff-307b06a48dc2efa670325c80f3729a15L24

I am not sure it is related to alpine update, probably was just extra refactoring.
That look ok on first site, BUT.

No it is a problem to use such docker images in web CIs, as they tend to add to docker instance their own folders for CI purposes.

Is it possible to return Docker files to execute all under root ?

Problem is found at: https://github.com/checkstyle/sonar-checkstyle/issues/175 , https://github.com/checkstyle/sonar-checkstyle/pull/165

**Comment by romani** [comment]
There is additional problem with Dockerfile: `$HOME` variable is defined as `/home/sonarqube` but there is no such folder. This create extra problems for Circle CI.

Workaround: https://github.com/checkstyle/sonar-checkstyle/commit/2980560415750e487b9525210afb364a4066993f

But it would be better to avoid such hacking of sonarqube image.

**Comment by janos-ss** [comment]
> No it is a problem to use such docker images in web CIs, as they tend to add to docker instance their own folders for CI purposes.
>
> Is it possible to return Docker files to execute all under root ?

Can you please be more specific? What exactly is the problem with using `USER sonarqube` in `Dockerfile` to execute the image's `run.sh` script?

**Comment by romani** [comment]
> Can you please be more specific?

to see a problem, please try to use latest docker images in wercker CI and circle CI.

wercker CI will fail to execute on preparation of build - because try to create folder `/pipeline` to inject all required shell scripts, but there is access to `/` , as sonarqube's docker is running under `sonarqube` user.

circleCI will fail as it inject shell file that try to put ssh keys in HOME folder, in sonarqube's docker HOMe folder is defined but there is no such folder so it results in failure.

Example of workaround for circleci - https://github.com/checkstyle/sonar-checkstyle/commit/2980560415750e487b9525210afb364a4066993f 

no workaround for wercker ci.

=======

All worked fine before mentioned update in sonarqube docker file.
you can review logs of CIs:
https://app.wercker.com/checkstyle/sonar-checkstyle/runs
https://circleci.com/gh/checkstyle/sonar-checkstyle/tree/master

**Comment by LeandroPT** [comment]
@janos-ss The problem for instance is that you cannot add certificates to the java keystore among other tweaks.

**Comment by simonbrandhof** [comment]
I wonder what is the need for starting a SonarQube server from a CI service like CircleCI. Could you please clarify?

**Comment by romani** [comment]
>starting a SonarQube server from a CI service like CircleCI. Could you please clarify?

SonarQube plugin development.
Start server with snapshot version of plugin, start validation of test project, verify no errors/exceptions in logs. Very simple and useful test.

**Comment by romani** [comment]
>SonarQube server from a JUnit test.

Thanks a lot for link, but it is better to have a test that start server in form close to how users will do this. To catch all possible nuances.

**Comment by simonbrandhof** [comment]
As you want. Note that Orchestrator starts the server exactly as users do.

**Comment by romani** [comment]
By shell file ?

**Comment by simonbrandhof** [comment]
It runs exactly the same command as in sonar.sh. I strongly believe it's good in the context of plugin tests. It is used at SonarSource for all our integration tests.
