### ISSUE TITLE
Alpine version for 6.7.6 and 7.4

### ISSUE THREAD

**Issue by arulrajnet** [SonarSource/docker-sonarqube#231]
The alpine flavored containers are missing for 6.7.6 and 7.4 versions. Could you add the same..?

**Comment by janos-ss** [comment]
Please see the FAQ section in [`develop.md`](https://github.com/SonarSource/docker-sonarqube/blob/master/develop.md). It explains why we don't provide Alpine-based images.

**Comment by arulrajnet** [comment]
@janos-ss thanks for the update. How to migrate from alpine based images to 6.7.6 community images?

**Comment by janos-ss** [comment]
@arulrajnet If you were using `6.7.5-alpine`, change it to `6.7.6-community`.

**Comment by arulrajnet** [comment]
Yes I am using `6.7.5-alpine`. After change that to `6.7.6-community` sonar never started. 

```
2019.01.10 16:04:59 INFO  app[][o.e.p.PluginsService] no modules loaded
2019.01.10 16:04:59 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2019.01.10 16:05:00 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 1

```

The full log is here https://pastebin.com/raw/B7bP8buT

**Comment by janosgyerik** [comment]
@arulrajnet Can you share how your Dockerfile / compose details?

**Comment by arulrajnet** [comment]
@janosgyerik Here its my [docker-compose.yaml](https://pastebin.com/raw/S2FXqURu)
