### ISSUE TITLE
cant change $SONARCUBE_HOME

### ISSUE THREAD

**Issue by fenchu** [SonarSource/docker-sonarqube#235]
If you change $SONARCUBE_HOME in Dockerfile container complains:
```
$ docker run -ti --name sonarqube -p 9000:9000 sonarqube:v7.5
Error: Unable to access jarfile lib/sonar-application-7.5.jar
```
```
ENV SONAR_VERSION=7.5 \
    SONARQUBE_HOME=/dist/sonarqube \
    SONARQUBE_JDBC_USERNAME=sonar \
    SONARQUBE_JDBC_PASSWORD=sonar \
    SONARQUBE_JDBC_URL=
```

Still lots of stuff in /opt/sonarcube:
```
sonarqube@d9d608f7145b:/dist/sonarqube$ ls -l /opt/sonarqube/
total 44
-rw-r--r-- 1 sonarqube sonarqube 7651 Dec 18 09:58 COPYING
drwxr-xr-x 8 sonarqube sonarqube 4096 Dec 18 09:58 bin
drwxr-xr-x 2 sonarqube sonarqube 4096 Dec 18 09:58 conf
drwxr-xr-x 2 sonarqube sonarqube 4096 Dec 18 09:58 data
drwxr-xr-x 7 sonarqube sonarqube 4096 Dec 18 09:58 elasticsearch
drwxr-xr-x 4 sonarqube sonarqube 4096 Dec 18 09:58 extensions
drwxr-xr-x 6 sonarqube sonarqube 4096 Dec 18 10:03 lib
drwxr-xr-x 2 sonarqube sonarqube 4096 Dec 18 09:58 logs
drwxr-xr-x 2 sonarqube sonarqube 4096 Dec 18 09:58 temp
drwxr-xr-x 9 sonarqube sonarqube 4096 Dec 18 10:03 web
```
This worked fine in older versions like 7.0 which I'm upgrading from.

**Comment by simonbrandhof** [comment]
Could you please describe the need for changing the installation dir? Thanks

**Comment by mwodtke** [comment]
SONARQUBE_HOME is declared as an environment variable in the docker file, this suggests that you can change the directory to suit your needs and environment.
However, the environment variable is only used for part of the configuration in the Dockerfile, so starting the container fails.
On the other hand, the environment variable SONARQUBE_HOME is not mentioned in the documentation and should not be used.

**Comment by pierre-guillot-sonarsource** [comment]
As @mwodtke says, the environment variable `SONARQUBE_HOME` is not mentioned in the docker documentation and should not be used. The fact that an environment variable exist doesn't mean that everything will be fine if you change it. If you have a valid use case of changing the installation dir, please reopen the ticket with a functional motivation.
