### ISSUE TITLE
How do you assign default values to admin general settings?

### ISSUE THREAD

**Issue by mxmichael** [SonarSource/docker-sonarqube#238]
I have followed the guidance on how to create a customized sonarqube docker image. I have this image building and running on my machine just fine. What I want to do next is to have some values, such as `sonar.core.serverBaseURL` assigned when I run my image (that's the stated key on the settings screen).

I'm not sure if I'm misunderstanding how to do this, I assume this can be placed within the sonar.properties file, however this seems to have no effect on the value.

**sonar.properties file:**
`sonar.core.serverBaseURL=https://sonar.mycompany.com`

<hr>

My guess is one of the following, but I'm not sure:

1. The setting cannot be assigned a default value from within the sonar.properties file. If so, how can it be set with a default value?
2. The value is not formed properly within my sonar.properties file?
3. I have placed the sonar.properties file in the wrong place? I have placed it under `/opt/sonarqube/conf/`.
4. I have to do something special to tell sonarqube to use the sonar.properties file?
5. Something else???

**Comment by expressionlibre** [comment]
Hi,
Not sure but might need to use environment variables as for others sonar.properties like jdbc url...
That helped me a lot with sonarqube 7.7
Also  /opt/sonarqube/conf/ volume is mounted from a named volume (overlay2 driver by default).
So container's "sonar.properties" is copied into volume at start.

**Comment by pierre-guillot-sonarsource** [comment]
Looks like you override your sonar.properties when the volume get mounted. I'm closing this since there has been no update for a while. Please retry with the latest SQ version and create a new issue if needed, with more details and logs.
