### ISSUE TITLE
Sonarqube to RDS Postgresql

### ISSUE THREAD

**Issue by rahul2810** [SonarSource/docker-sonarqube#241]
Hi, I'm new to docker.
trying to connect this with my postgresql db on aws rds instead of the regular h2 storage/starting a postgresql instance within the container. 

tried modifing yaml:
.added the path to my db with credentials under **services** and **db**
still no luck keeps exiting with code 0
**can anyone help?**

**Comment by pierre-guillot-sonarsource** [comment]
I'm closing this since there has been no update for a while. Please retry with the latest SQ version and create a new issue if needed, with more details, your docker-compose, and logs.
