### ISSUE TITLE
Default user credentilas "admin/admin" do not work

### ISSUE THREAD

**Issue by lukitroe** [SonarSource/docker-sonarqube#244]
I'm using a Windows 10 PC. I execute the following commands into my PowerShell:
* docker pull sonarqube
* docker run -d --name sonarqube -p 9000:9000 sonarqube
* I start a browser and enter "localhost:9000" into the adress bar
* SonarQube starts up
* Afterwards I want to log in with the user credentials "admin/admin", however SonarQube constantly tells me, that this credentials are wrong

But which credentials should I use? The logs of the docker container show, that SonarQube uses the default H2 database (which is sufficient for my evaluation purposes right now).
Thanks for your help!
Best regards

**Comment by lukitroe** [comment]
Hi!

I think I found the solution:
* As I tried to login to SonarQube, I was using the Opera Browser. With Opera, it never succeeded

My very last desperate attempt was to switch to Chrome and voilà the default credentials "admin/admin" worked.

**Comment by simonbrandhof** [comment]
Thanks for the follow-up.
Note that authentication on Opera 58.0 works perfectly with SonarQube 7.6. I didn't test any other versions.
