### ISSUE TITLE
Oficial Docker Images is unnder Matenance

### ISSUE THREAD

**Issue by Juancarlosmartin10** [SonarSource/docker-sonarqube#248]
Hi all, 

When I try to deploy a Dokcer istance of SonarQube al least version 7.0 the prinncipal page says as follows:

>

>  SonarQube
> 
>  is under maintenance
> 
> While waiting, you might want to investigate new plugins to extend the current functionality.
> 
> If you are an administrator and have no idea why this message is being shown, you should read the upgrade guide

.

**Comment by konstantinblaesi** [comment]
go to `/setup` and migrate your db and see if that helps

**Comment by Juancarlosmartin10** [comment]
When I go to /setup docker shows  this message:
> Migration not supported
> 
> Migration is not supported on embedded databases.

**Comment by simonbrandhof** [comment]
Could you please try with a recent version of SonarQube? The image was deeply refactored in version 7.5.

**Comment by nixel2007** [comment]
@Juancarlosmartin10 did you see bit red splash at the buttom of the screen that says you must not use embedded database to production instances and that it doesn't support upgrading of SQ version?

**Comment by pierre-guillot-sonarsource** [comment]
@nixel2007 answered your question i guess :)
