### ISSUE TITLE
sonarQube

### ISSUE THREAD

**Issue by gkdba87** [SonarSource/docker-sonarqube#249]
Hi 
i have few doubts  can any one please clarify me.( i will plan to deploy Sonar on kubernates platform)
- SonarQube is opensource r not ?
-  Opensource Sonar Gives Enterprise features or not.
- Opensource Sonar is enough for Code coverage?

Thanks

**Comment by nixel2007** [comment]
> SonarQube is opensource r not ?

community edition is open source

> Opensource Sonar Gives Enterprise features or not.

no

> Opensource Sonar is enough for Code coverage?

yes.

**Comment by gkdba87** [comment]
Hi Thank U for update.
For Enterprise edition how much?

**Comment by nixel2007** [comment]
https://www.sonarsource.com/plans-and-pricing/

**Comment by gkdba87** [comment]
Thanks
