### ISSUE TITLE
Failing to start - 

### ISSUE THREAD

**Issue by johndoran** [SonarSource/docker-sonarqube#25]
Im having trouble starting my container. Im using the standard setup. Has anyone else seen this issue?
Appreciate any tips.

Using sonarqube/5.4 container

2016.04.13 16:59:41 WARN  web[o.a.c.l.WebappClassLoaderBase] The web application [ROOT] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
 com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43)
2016.04.13 16:59:41 INFO  web[o.a.c.h.Http11NioProtocol] Stopping ProtocolHandler ["http-nio-0.0.0.0-9000"]
2016.04.13 16:59:42 INFO  web[o.a.c.h.Http11NioProtocol] Destroying ProtocolHandler ["http-nio-0.0.0.0-9000"]
2016.04.13 16:59:42 INFO  web[o.s.s.a.TomcatAccessLog] Web server is stopped
2016.04.13 16:59:42 INFO  app[o.s.p.m.Monitor] Process[web] is stopped
2016.04.13 16:59:42 INFO  app[o.s.p.m.Monitor] Process[search] is stopping

**Comment by Godin** [comment]
@johndoran this doesn't look like full log, so could you please provide full log, including command, which was used to start container? Also - do you experience the same problem with other versions?

**Comment by johndoran** [comment]
Hi, full stack attached. I'm using ecs to deploy the container - here is my task definition.

```
 def sonar(self, container_version):
        return {
            "cpu": 3076,
            "essential": True,
           "image": "sonarqube:{}".format(container_version if container_version else "latest"),
            "memory": 4096,
            "portMappings": [
                {
                    'containerPort': 9000,
                    'hostPort': 9000,
                    'protocol': 'tcp'
                },
                {
                    'containerPort': 9092,
                    'hostPort': 9092,
                    'protocol': 'tcp'
                }
            ],
            "name": "sonar",
            "environment": [{"name": "SONARQUBE_JDBC_USERNAME", "value": "sonar"},
                            {"name": "SONARQUBE_JDBC_PASSWORD", "value": "MY_SONAR_PW"},
                            {"name": "SONARQUBE_JDBC_URL", "value": "jdbc:mysql://MY_URL/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance"}
                            ],
        }
[stack.txt](https://github.com/SonarSource/docker-sonarqube/files/219146/stack.txt)

**Comment by johndoran** [comment]
I ran the 4.5.7 docker container and here is the stacktrace 
[stack-4.5.7.txt](https://github.com/SonarSource/docker-sonarqube/files/219165/stack-4.5.7.txt)

**Comment by Godin** [comment]
@johndoran I have strong feeling that attempt with 4.5.7 is not a cold start - it seems that during startup something requesting non-existing in this version component. Possible causes:
* non-empty db - probably the same as you used for 5.4, but SQ doesn't support downgrade of data in DB
* non-empty data directories (some installed plugin is not compatible with this version and/or ElasticSearch indexes are corrupted)

Please try cold start.

Log for 5.4 looks strange and unhelpful, but I will also recommend to do cold start. This way we can determine - whether problem comes from state of data, or due to SQ+Docker.

**Comment by johndoran** [comment]
running with raw docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube
I suspect its something with my jdbc connection or something else. I will close the ticket thanks

**Comment by jasonrhaas** [comment]
I'm having this issue as well.  Ever figure out what the problem was @johndoran ?
