### ISSUE TITLE
Error while redeploying the sonarqube container

### ISSUE THREAD

**Issue by saikirandusari** [SonarSource/docker-sonarqube#250]
I have provisioned Sonarqube on OpenShift platform, the first deployment is always successful when I create using the Sonarqube template (Sonarqube and Postgres containers will spin up with no errors), only when the container restarts/when redeployed it fails with below error. Please help. Stuck for a while now.

java.lang.IllegalStateException: ClusterService was close during health call
--
  | at org.elasticsearch.action.admin.cluster.health.TransportClusterHealthAction$3.onClusterServiceClose(TransportClusterHealthAction.java:180)
  | at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onClusterServiceClose(ClusterStateObserver.java:304)
  | at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onClose(ClusterStateObserver.java:224)
  | at org.elasticsearch.cluster.service.ClusterService.doStop(ClusterService.java:230)
  | at org.elasticsearch.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:88)
  | at org.elasticsearch.node.Node.stop(Node.java:787)
  | at org.elasticsearch.node.Node.close(Node.java:809)
  | at org.apache.lucene.util.IOUtils.close(IOUtils.java:89)
  | at org.apache.lucene.util.IOUtils.close(IOUtils.java:76)
  | at org.elasticsearch.bootstrap.Bootstrap$4.run(Bootstrap.java:209)
  | 2019.02.23 00:04:21 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143
  | 2019.02.23 00:04:21 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
  | 2019.02.23 00:04:21 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped

**Comment by likka7** [comment]
Hello!

I have got the same issue. Is any update here?

Thank in advance!

**Comment by pierre-guillot-sonarsource** [comment]
Hello, at the moment there is no healcheck on the image. We plan to add one this week, see https://jira.sonarsource.com/browse/MMF-1777
