### ISSUE TITLE
Unable to get sonarqube7.6 run 

### ISSUE THREAD

**Issue by JyothsnaGuduri** [SonarSource/docker-sonarqube#251]
I see following logs on the service startup 
20:57:20.883 [main] WARN org.sonar.application.config.AppSettingsLoaderImpl - Configuration file not found: /opt/sonarqube/conf/sonar.properties
2019.02.28 20:57:21 INFO app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2019.02.28 20:57:21 INFO app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2019.02.28 20:57:21 INFO app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch -Epath.conf=/opt/sonarqube/temp/conf/es
2019.02.28 20:57:21 INFO app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2019.02.28 20:57:21 INFO app[][o.e.p.PluginsService] no modules loaded
2019.02.28 20:57:21 INFO app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2019.02.28 20:57:22 WARN app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 1
2019.02.28 20:57:22 INFO app[][o.s.a.SchedulerImpl] Process [es] is stopped
2019.02.28 20:57:22 INFO app[][o.s.a.SchedulerImpl] SonarQube is stopped

**Comment by Zhang21** [comment]
You should look the es's log(`es.log`), in the same dir.

The logs will tell you what's going wrong.

**Comment by JyothsnaGuduri** [comment]
I couldn't find the log location, can share me with the directory location?

**Comment by nixel2007** [comment]
/opt/sonarqube/logs

**Comment by pierre-guillot-sonarsource** [comment]
I'm closing this since there has been no update for a while. Please retry with the latest SQ version and create a new issue if needed, with more details and logs.
