### ISSUE TITLE
the /opt/sonarqube/conf/sonar.properties does not work in Docker

### ISSUE THREAD

**Issue by Hanhan1989** [SonarSource/docker-sonarqube#253]
Sonarqube does not catch the configuration files in /opt/sonarqube/conf . I had to use global variables to set the database. The version is 7.6.0.21501.

<pre>
# Sonarqube JDBC
SONARQUBE_JDBC_USERNAME=sonar
SONARQUBE_JDBC_PASSWORD=sonar
SONARQUBE_JDBC_URL=jdbc:mysql://sonarqube_mysql:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
</pre>

Any solution?

**Comment by dmbloch** [comment]
I am running into the same issue with 6.7.6.
My Dockerfile is simple, followed the instructions [here](https://github.com/docker-library/docs/tree/master/sonarqube#option-4-customized-image).

```
FROM sonarqube:6.7.6-community
COPY sonar.properties /opt/sonarqube/conf/
```

Also tried `COPY --chown=sonarqube:sonarqube sonar.properties /opt/sonarqube/conf/` but no dice.

The file is getting copied to the correct location in the container, I can see it when looking in the built container. But it is not being recognized, and sonarqube is starting up with the default database.

**Comment by simonbrandhof** [comment]
Note that versions 6.7 and 7.x of the Docker images are completely different. The latter has been much refactored.

**Comment by ftier-tech** [comment]
I have the latest 7.7 and it ignores the sonar.properties, I had to use docker -e to set my database variables.

**Comment by darkebe** [comment]
I have the same problem with the latest 7.7 but just the parameter database are ignored.

**Comment by yangyang9966** [comment]
I am running into the same issue with 7.7 . So How I can solve this problems? When I  set variables, 
![image](https://user-images.githubusercontent.com/17893900/58307783-54579000-7e32-11e9-9951-bf0d501db595.png)

**Comment by Longbow98** [comment]
The entrypoint script overrides the database variables (from the Configuration file) with environment variables. If the environment variables for the database do not exist, sonarqube runs into a fallback and creates an H2.

**Comment by DaiZero** [comment]
same problem

**Comment by neiltingley3** [comment]
Have a read of https://jira.sonarsource.com/browse/SONAR-11818

From what I can see you can only set a few properties, all others ignored. No log messages to tell you this. 

So there's no way to automate the spin up sonar with say the Azure AD plugin settings.

IMHO an absolute joke.

**Comment by simonbrandhof** [comment]
> IMHO an absolute joke.

This sentence is not needed for helping things to be improved. Thanks.

**Comment by neiltingley3** [comment]
> > IMHO an absolute joke.
> 
> This sentence is not needed for helping things to be improved. Thanks.

Why remove the ability to set properties for the Azure AD plugin for example?  It means we can't spin up a sonarqube with plugins like this configured ? If there's a good reason then perhaps you should add it to the above ticket. But from a devops perspective sonarqube deployments can't be fully automated and this is never a good thing.

**Comment by simonbrandhof** [comment]
Different topics have been raised in comments. To sum-up the initial problem, the database parameters can't be set in `sonar.properties` when using the configuration approach 4 "[Customized Image](https://github.com/docker-library/docs/tree/master/sonarqube#option-4-customized-image)". Other parameters are taken into account. Correct?

**Comment by simonbrandhof** [comment]
@neiltingley3 your point is valid but out-of-scope this thread. Note that SONAR-11818 is still open and under discussion. Feel free to drop a comment on it or to open a thread on https://community.sonarsource.com. Thanks for your understanding.
