### ISSUE TITLE
AccessDeniedException: /opt/sonarqube/temp/README.txt

### ISSUE THREAD

**Issue by KatoneVi** [SonarSource/docker-sonarqube#254]
Having issues deploying this on Openshift.
When attempt to deploy this image, I get the following error:

2019.03.08 21:16:55 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
Exception in thread "main" java.nio.file.AccessDeniedException: /opt/sonarqube/temp/README.txt

Anyone know how to resolve this issue?
It clearly states that it is a Permission error... but how would one resolve it on Openshift when we are using templates to deploy this?

Here is a portion of my yaml file (openshift template):
>spec:
__template:
____spec:
______- env:
______- name: sonar.jdbc.password
________value: ${POSTGRESQL_PASSWORD}
______- name: sonar.jdbc.url
________value: jdbc:postgresql://postgresql-sonarqube/sonar
______- name: sonar.jdbc.username
________value: sonar
______image: ' '
______volumeMounts:
______- mountPath: /opt/sonarqube/data
________name: sonarqube-data
____volumes:
____- name: sonarqube-data
______persistentVolumeClaim:
________claimName: sonarqube-data

The only way I can think of resolving this (which I would prefer another way if possible) is:
1. Create Dockerfile to change permission
2. Run dockerfile to create image
3. Tag the image
4. Push to a registry somewhere
5. oc new-app <url-to-image-in-registry>

It's a messy workaround.

**Comment by KatoneVi** [comment]
For now, I did the workaround (which I shared above).  It works... but it is ridiculous that I have to perform extra steps for it.

- Create Dockerfile to change permission.
- Run DockerFile (and tag it) to create image: 
e.g.   docker build --tag myNexusUrl:443/<optional-folder-name>/<artifact-name>:<version>
- docker push
- oc import-image mySonarImage myNexusUrl:443/<optional-folder-name>/<artifact-name>:<version> (something like this...  i dont remember fully)
- oc new-app mySonarImage

**Comment by maxrome** [comment]
If you don't want to recreate the Docker file, I resolved relaxing the security constraint for my sonarqube project and forcing the runAsUser.

I added the following code inside the pod spec yaml
```
spec:
   serviceAccountName: sonar-user
   containers:
   - name: sonarqube
      securityContext:
         runAsUser: 999
```

then you have to create the serviceAccont with the following commands inside your project:
```
$ oc create serviceaccount sonar-user
$ oc adm policy add-scc-to-user privileged -z sonar-user
```

You need to do that, because by default, openshift run the entrypoint with a UID in the range of 1000040000 and  1000049999, but in the official sonarqube image, only the sonarqube user with UID=999 can write in that folder.

You can find further details about openshift runAsUser mechanism here: [https://blog.openshift.com/jupyter-on-openshift-part-6-running-as-an-assigned-user-id/](https://blog.openshift.com/jupyter-on-openshift-part-6-running-as-an-assigned-user-id/)

**Comment by KatoneVi** [comment]
> If you don't want to recreate the Docker file, I resolved relaxing the security constraint for my sonarqube project and forcing the runAsUser.
> 
> I added the following code inside the pod spec yaml
> 
> ```
> spec:
>    serviceAccountName: sonar-user
>    containers:
>    - name: sonarqube
>       securityContext:
>          runAsUser: 999
> ```
> then you have to create the serviceAccont with the following commands inside your project:
> 
> ```
> $ oc create serviceaccount sonar-user
> $ oc adm policy add-scc-to-user privileged -z sonar-user
> ```
> You need to do that, because by default, openshift run the entrypoint with a UID in the range of 1000040000 and 1000049999, but in the official sonarqube image, only the sonarqube user with UID=999 can write in that folder.
> 
> You can find further details about openshift runAsUser mechanism here: https://blog.openshift.com/jupyter-on-openshift-part-6-running-as-an-assigned-user-id/

Question for you.
In my YAML file, I have a DeploymentConfig already set.
Should I just create the Pod in there too?

Also, can you show me your full example of the "Pod Section" in your YAML?
I'm having trouble getting mine to work!

Much appreciated!

**Comment by pierre-guillot-sonarsource** [comment]
We don't support openshift as we are not using it internally. If you have a suggestion to fix the issue, feel free to open a PR here detailing the solution, it will be very valuable !

**Comment by pavankjadda** [comment]
I have quick solution for similar issues. 

1. Start a new sonarqube container in local machine 
```
$ docker run -d --name jpavanaryan/sonarqube -p 9000:9000
```
2. Login into container with docker exec command
```
$ docker ps
71605404c389        jpavanaryan/sonarqube   "./bin/run.sh"      5 hours ago         Up 5 hours          0.0.0.0:9000->9000/tcp   sonarqube

$ docker exec -it 71605404c389 bash
```
3. Navigate to **/opt/sonarqube** directory and give all permissions to target user account
```
$ chown -R <username> /opt/sonarqube
```
4. Now, commit the image 
```
$ docker commit 71605404c389 sonarqube
```
5. Import this image into openshift or create a new app with oc commands
```
$ oc new-app  --name=sonarqube  -n cicd jpavanaryan/sonarqube -e \ SONARQUBE_JDBC_USERNAME=<username> -e  \ SONARQUBE_JDBC_PASSWORD=<password> -e \ SONARQUBE_JDBC_URL=<jdbc_url>
```
That's it, everything should work fine and sonarqube must be accessble from openshift console

**Comment by GaryLouisStewart** [comment]
I solved this as I was using the alpine image and the user-id is actually 100 & the group id is 101 it was just a matter of setting this in the security context. the standard (non-alpine linux) image for sonarqube actually uses the user-id 999 & group of 999 so I was also able to get this to work. 

if i used these id's there is no need to go in a chown the dir's and entrypoint files other than in the docker-image and means that it can natively run in kubernetes by applying this with the security context to your sonarqube pods

I know this has been closed but may be worth seeing for future incase anyone runs into this again 👍

**Comment by amineellouze** [comment]
j'ai modifié la version java de 14 à 11 et çà marche bien puisque sonarqube ne supporte pas une version plus que la version 11.
