### ISSUE TITLE
How to setup a production docker-compose?

### ISSUE THREAD

**Issue by culyzhao** [SonarSource/docker-sonarqube#260]
I tried sonarqube:lastest and lts, it works very well by default configuration

_version: "3"
services:
   db:
     image: postgres:10
     restart: always
     container_name: postgres
     ports:
       - "5432:5432"
     environment:
       - POSTGRES_USER=sonar
       - POSTGRES_PASSWORD=sonar
   adminer:
     image: adminer
     restart: always
     ports:
       - 8080:8080
   sonarqube:
     image: sonarqube:lts
     container_name: sonarqube
     ports:
       - "9000:9000"
       - "9092:9092"
     volumes:
       - /etc/localtime:/etc/localtime:ro
       - /opt/postgres/data:/var/lib/postgresql/data
     links:
       - db
     environment:
       - sonar.jdbc.username=sonar
       - sonar.jdbc.password=sonar
       - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
     ulimits:
       nproc: 65535_

but I think this is not enough for production target, all of the plugins downloaded will be lost when the container restart.
In the dockerhub homepage, I can find these sample for persistent volumes

_$ docker run -d --name sonarqube \
    -p 9000:9000 \
    -v /path/to/conf:/opt/sonarqube/conf \
    -v /path/to/data:/opt/sonarqube/data \
    -v /path/to/logs:/opt/sonarqube/logs \
    -v /path/to/extensions:/opt/sonarqube/extensions \
    sonarqube_

when I add volumes setting to docker-compose file, sonarqube can not start nornally.

       _- /opt/sonarqube/conf:/opt/sonarqube/conf
       - /opt/sonarqube/extensions:/opt/sonarqube/extensions
       - /opt/sonarqube/data:/opt/sonarqube/data_

/opt/sonarqube/conf caused sonar.properties not found.
/opt/sonarqube/extensions caused INFO  web[][o.s.s.r.RegisterRules] Disable rule xxxxxx, it seems that all of the plugin is missing and rules are disabled.

I found topic here can install plugins using Dockerfile

_FROM sonarqube:lts

COPY ./sonar-crowd-plugin-2.1.1.jar /opt/sonarqube/extensions/plugins/
COPY ./checkstyle-sonar-plugin-4.18.jar /opt/sonarqube/extensions/plugins/
COPY ./sonar-findbugs-plugin-3.9.3.jar /opt/sonarqube/extensions/plugins/
..._

It is a workaround , when there are updated plugins , I cannot use the marketplace upgrade ti online, I have to rebuild image. This is very inconvenient.

Does this design mean that sonarqube in docker  is for demonstration purposes ?

**Comment by nixel2007** [comment]
Do you know, how docker volume mounting works? When you mount your empty conf directory from Host to container, you overwrite sonar.properties file also. This file is required to start server.

**Comment by cianiandreadev** [comment]
I have a similar error. I didn't bind the setting volume (since I used the evars for the few settings I have) and I didn't even used neither the postgress or other systems. I only have a docker compose with SonarQuebe (for now). 
But after starting it, it stops automatically. This is the output:

```
mypc:sonarqube me$ docker-compose up
Creating network "sonarqube_default" with the default driver
Creating sonarqube_sonarqube_1 ... done
Attaching to sonarqube_sonarqube_1
sonarqube_1  | 2019.05.09 08:29:12 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
sonarqube_1  | 2019.05.09 08:29:12 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
sonarqube_1  | 2019.05.09 08:29:12 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch -Epath.conf=/opt/sonarqube/temp/conf/es
sonarqube_1  | 2019.05.09 08:29:12 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
sonarqube_1  | 2019.05.09 08:29:17 INFO  app[][o.e.p.PluginsService] no modules loaded
sonarqube_1  | 2019.05.09 08:29:17 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
sonarqube_1  | 2019.05.09 08:30:49 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 137
sonarqube_1  | 2019.05.09 08:30:49 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
sonarqube_1  | 2019.05.09 08:30:49 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
sonarqube_sonarqube_1 exited with code 0
```

**Comment by orgrimarr** [comment]
I fix this issue in a weird way..
delete database, app folder then

volumes:
      - ./app/conf:/opt/sonarqube/conf
      - ./app/data:/opt/sonarqube/data
      - ./app/logs:/opt/sonarqube/logs
      - ./app/extensions:/opt/sonarqube/extensions

and i create the app/extensions/downloads folder

**Comment by nixel2007** [comment]
@cianiandreadev check logs. There will be full text of error.

**Comment by pierre-guillot-sonarsource** [comment]
I'm closing this since there has been no update for a while. Please retry with the latest SQ version and create a new issue if needed, with more details and logs.
