### ISSUE TITLE
SonarQube error, while executing mvn sonar:sonar

### ISSUE THREAD

**Issue by gkdba87** [SonarSource/docker-sonarqube#262]
Hi 
we have implemented HTTPS connection  to our Sonar application.
while executing maven goel (sonar:sonar)  iam getting following error. 
![image](https://user-images.githubusercontent.com/22393158/55545708-6303af80-56eb-11e9-9dc5-fd33ca56f180.png)

Any one Please look into this

**Comment by pierre-guillot-sonarsource** [comment]
I'm closing this since there has been no update for a while. Please retry with the latest SQ version and create a new issue if needed.
