### ISSUE TITLE
Unable to create new native thread on Azure Kubernetes 1.14.0

### ISSUE THREAD

**Issue by Zenuka** [SonarSource/docker-sonarqube#265]
I've updated the Azure Kubernetes cluster to v1.14.0 and after that sonarqube doesn't start anymore. I get the following error message:
```
Exception in thread "main" java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:717)
        at org.sonar.process.ProcessEntryPoint.stopAsync(ProcessEntryPoint.java:175)
        at org.sonar.process.ProcessEntryPoint.stop(ProcessEntryPoint.java:159)
        at org.sonar.process.ProcessEntryPoint.launch(ProcessEntryPoint.java:104)
        at org.sonar.server.app.WebServer.main(WebServer.java:91)
```
A full trace log can be found here: https://pastebin.com/ifyej9SS.
I've tried to install sonarqube in a new cluster with version 1.14.0 and I've got the same issue. 
The nodes are `DS2_v2` nodes (2 vcpus, 7 GB memory) so that should suffice. Suggestions are very welcome!

**Comment by DDebray** [comment]
I think this is related on how the kubernetes is managing the containers now. I upgraded our existing kubernetes cluster to 1.14 in aks and have the same issue with java (not sonarqube in particular).

**Comment by cwebbtw** [comment]
We're seeing the same issue here after upgrading our cluster with Jenkins.

**Comment by DDebray** [comment]
1.14 is still in preview stage and should not be used in production. If you take the most recent stable version, the image should run fine.

**Comment by Zenuka** [comment]
> 1.14 is still in preview stage and should not be used in production. If you take the most recent stable version, the image should run fine.

Where can I find this information the next time?

**Comment by thebitguru** [comment]
> > 1.14 is still in preview stage and should not be used in production. If you take the most recent stable version, the image should run fine.
> 
> Where can I find this information the next time?

If you use the Azure Portal, it was listed in the drop down as "1.14 (preview)" along with a note around not using it in production.  I did notice that Microsoft mistakenly released it as GA at one point (as reported [here](https://github.com/Azure/AKS/issues/940)); you could have upgraded at that time.

I am also seeing this with one of my pods that runs another java app (protractor/selenium web driver) on a non-prod 1.14 AKS cluster.  I have not figured out how to fix it yet, though.  I did submit [a new issue in the official AKS repo](https://github.com/Azure/AKS/issues/1051).

**Comment by digeler** [comment]
This sounds like this :
https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20190129-pid-limiting.md#summary

Login into the node where your pod is 
And find the /etc/default/kubelet 
Try increase the max pid then restart kubelet 
See if this make any difference.

**Comment by monaka** [comment]
@digeler Looks BINGO.
I carelessly got this issue on this morning and resolved on this evening (now).
Just modifying `--pod-max-pids=100` to `--pod-max-pids=-1` in `/etc/default/kubelet`.
My trouble was on Keycloak but Sonarqube will be same.

**Comment by simonbrandhof** [comment]
Thanks to all of you of the discussion. Let's close the ticket. It's not specific to the SonarQube image.
