### ISSUE TITLE
Docker container - ENV variables with dots not supported by Azure

### ISSUE THREAD

**Issue by vimfan** [SonarSource/docker-sonarqube#268]
Microsoft Azure does not allow to create Container Instance with environment variables which keys have dots:

"A valid environment variable name must start with alphabetic character or '_', followed by a string of alphanumeric characters or '_' (for example: 'my_name', or 'MY_NAME', or 'MyName')."

You plan to deprecate support for capitalized env variables like SONARQUBE_JDBC_USERNAME according to your documentation here: https://hub.docker.com/_/sonarqube/?tab=description

"Use of the environment variables SONARQUBE_JDBC_USERNAME, SONARQUBE_JDBC_PASSWORD and SONARQUBE_JDBC_URL is deprecated, and will stop working in future releases."

This will be an inconvenience and would make usage of the container more complicated. Please reevaluate the plan to deprecate them.

**Comment by simonbrandhof** [comment]
In that case what would you suggest to support the other properties of `sonar.properties` file?

**Comment by simonbrandhof** [comment]
Using a single env variable `SONARQUBE_OPTS` could be an alternative to declare all the parameters, for instance `SONARQUBE_OPTS="sonar.jdbc.url=xxx;sonar.jdbc.password=yyy;sonar.auth.jwtBase64Hs256Secret=zzz`. Escaping of separators should be carefully handled.
Does that make sense?
