### ISSUE TITLE
Unable to use docker-compose to build sonarqube service with PostgreSQL - Permission issues

### ISSUE THREAD

**Issue by abrousseau001** [SonarSource/docker-sonarqube#275]
My docker compose file is as follows:

~~~~
version:` '3'
services:
  postgres:
    image: "postgres:10"
    container_name: sonarqube_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports: 
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
  sonarqube:
    image: sonarqube:7.7-community
    container_name: sonarqube
    depends_on: 
      - postgres
    restart: unless-stopped
    environment: 
      - sonar.jdbc.username="$POSTGRES_USER"
      - sonar.jdbc.password="$POSTGRES_PASS"
      - sonar.jdbc.url="jdbc:postgresql://${env:POSTGRES_IP}:5432/sonarqube"
    ports:
      - 9000:9000
    volumes:
      - /opt/sonarqube/data:/opt/sonarqube/data
      - /var/log/sonarqube:/opt/sonarqube/logs
  nginx:
    build: ./nginx
    depends_on: 
      - sonarqube
    container_name: sonarqube_nginx
    logging:
      driver: journald
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/private/:/etc/ssl/private/
      - `/var/log/nginx:/var/log/nginx
~~~~

My enivronment file contains the user name, password, database to create, and the ip for the database.

My issue is that any time I try creating the sonarqube service I receive an error from the logger that it is unable to start the sonarqube service as it is unable to invoke a factory method for the rolling file appender.

![image](https://user-images.githubusercontent.com/11802189/59520285-9905a280-8e97-11e9-80f1-59a4068fa94d.png)

I figured out this is a permissions issue using the bind mounting, but how is it intended to allow mounting host to containers so logs are easily accessible and persistent?

**Comment by michal-duda-sonarsource** [comment]
As you've said, it looks like a permission issue with `/var/log/sonarqube` on your host machine. Please try mounting `/opt/sonarqube/logs` to a different directory.
