### ISSUE TITLE
Caused by: java.nio.file.NoSuchFileException: /opt/sonarqube/data/web/deploy/plugins/sonarscala/sonar-scala-plugin-1.5.0.315.jar

### ISSUE THREAD

**Issue by jhonalexander0809** [SonarSource/docker-sonarqube#278]
Please help me.
I have a problem with sonarqube when implementing it in openshift with the official image in docker hub.
version: sonarqube: latest

This is the error.

<pre>
<code>
16:03:07.413 [main] WARN org.sonar.application.config.AppSettingsLoaderImpl - Configuration file not found: /opt/sonarqube/conf/sonar.properties
--
  | 2019.06.19 16:03:08 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
  | 2019.06.19 16:03:08 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
  | 2019.06.19 16:03:08 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch
  | 2019.06.19 16:03:08 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
  | 2019.06.19 16:03:09 INFO  app[][o.e.p.PluginsService] no modules loaded
  | 2019.06.19 16:03:09 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
  | 2019.06.19 16:04:22 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
  | 2019.06.19 16:04:22 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/opt/sonarqube]: /usr/local/openjdk-8/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -cp ./lib/common/*:/opt/sonarqube/lib/jdbc/postgresql/postgresql-42.2.5.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process1734246016324403881properties
  | 2019.06.19 16:04:23 INFO  web[][o.s.p.ProcessEntryPoint] Starting web
  | 2019.06.19 16:04:25 WARN  web[][o.s.p.ProcessEntryPoint] Fail to start web
  | java.lang.IllegalStateException: Fail to create or clean-up directory /opt/sonarqube/data/web/deploy
  | at org.sonar.server.app.TomcatContexts.addStaticDir(TomcatContexts.java:85)
  | at org.sonar.server.app.TomcatContexts.configure(TomcatContexts.java:60)
  | at org.sonar.server.app.EmbeddedTomcat.start(EmbeddedTomcat.java:59)
  | at org.sonar.server.app.WebServer.start(WebServer.java:51)
  | at org.sonar.process.ProcessEntryPoint.launch(ProcessEntryPoint.java:113)
  | at org.sonar.process.ProcessEntryPoint.launch(ProcessEntryPoint.java:100)
  | at org.sonar.server.app.WebServer.main(WebServer.java:91)
  | Caused by: java.nio.file.NoSuchFileException: /opt/sonarqube/data/web/deploy/plugins/sonarscala/sonar-scala-plugin-1.5.0.315.jar
  | at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
  | at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
  | at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
  | at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
  | at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
  | at java.nio.file.Files.delete(Files.java:1126)
  | at org.sonar.core.util.FileUtils$DeleteRecursivelyFileVisitor.visitFile(FileUtils.java:204)
  | at org.sonar.core.util.FileUtils$DeleteRecursivelyFileVisitor.visitFile(FileUtils.java:199)
  | at java.nio.file.Files.walkFileTree(Files.java:2670)
  | at java.nio.file.Files.walkFileTree(Files.java:2742)
  | at org.sonar.core.util.FileUtils.deleteDirectoryImpl(FileUtils.java:159)
  | at org.sonar.core.util.FileUtils.access$100(FileUtils.java:41)
  | at org.sonar.core.util.FileUtils$CleanDirectoryFileVisitor.visitFile(FileUtils.java:183)
  | at org.sonar.core.util.FileUtils$CleanDirectoryFileVisitor.visitFile(FileUtils.java:169)
  | at java.nio.file.Files.walkFileTree(Files.java:2670)
  | at org.sonar.core.util.FileUtils.cleanDirectoryImpl(FileUtils.java:146)
  | at org.sonar.core.util.FileUtils.cleanDirectory(FileUtils.java:86)
  | at org.sonar.server.app.TomcatContexts$Fs.createOrCleanupDir(TomcatContexts.java:124)
  | at org.sonar.server.app.TomcatContexts.addStaticDir(TomcatContexts.java:83)
  | ... 6 common frames omitted
  | 2019.06.19 16:04:25 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
  | 2019.06.19 16:04:25 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
  | 2019.06.19 16:04:25 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143
  | 2019.06.19 16:04:25 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped

</code
</pre>

**Comment by pierre-guillot-sonarsource** [comment]
I'm closing this since there has been no update for a while. Please retry with the latest SQ version and create a new issue if needed, with more details and logs.
