### ISSUE TITLE
Use AdoptOpenJDK image as base instead of OpenJDK image

### ISSUE THREAD

**Issue by michal-duda-sonarsource** [SonarSource/docker-sonarqube#300]
Right now, in our docker images we use Oracle's OpenJDK. The problem with this is docker images for OpenJDK that we use a base for our images are very large. Switching to AdoptOpenJDK would enable us to use alpine (or in some cases alpine-slim) versions of JDK images which are much smaller due to a much smaller system distribution.

**Comment by nixel2007** [comment]
Please consider the fact that alpine images is slower than debian/ubuntu images cause of different libc implementations and other system libs.

We switched from alpine to normal images for SQ cause of perfomance degradation at CE

**Comment by pierre-guillot-sonarsource** [comment]
Thanks for the feedback @nixel2007 , we will make sure to benchmark this 👍

**Comment by gosp** [comment]
I personally wish "adoptopenjdk/openjdk11:alpine-jre" or  "azul/zulu-openjdk-alpine:11-jre" is used to reduce size.

**Comment by gosp** [comment]
Use JRE instead of JDK to reduce size. For example: 

- alpine:  **adoptopenjdk/openjdk11:alpine-jre** or **azul/zulu-openjdk-alpine:11-jre**
- debian:stretch: **adoptopenjdk/openjdk11:debian-jre**

**Comment by lg0killer** [comment]
Just be careful as some of the plugins break when a too lightweight version is being used.

Something like the svg badges depend on libfontmanager and since the current openjdk is the jre-slim, it causes the container to break since it is not included.

**Comment by pierre-guillot-sonarsource** [comment]
@michal-duda-sonarsource can we close this ?

**Comment by michal-duda-sonarsource** [comment]
Closing, since we switched to `openjdk:11-jre-slim`.
