### ISSUE TITLE
Wrong english: ...`reqired`

### ISSUE THREAD

**Issue by guiferpa** [SonarSource/docker-sonarqube#307]
Please ensure your issue adheres to the following guidelines: 

- [x] Please check the problem is not already reported, or a known issue documented in [`develop.md`](develop.md)
- [x] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs

I looked in a error message (https://github.com/SonarSource/docker-sonarqube/blob/master/build-and-run.sh#L37) an wrong english. What do you think about a PR to fixing it?

**Comment by pierre-guillot-sonarsource** [comment]
@guiferpa Thanks for reporting the typo. Yes we definitely accept PR fixing it :)
