### ISSUE TITLE
How can i install openssh-server an run service ssh start as root (Azure app service)?

### ISSUE THREAD

**Issue by allanmoller** [SonarSource/docker-sonarqube#309]
Hey, 

I would like to enable SSH on the Azure app service, without granting the sonarqube user sudo privileges. I can install everything fin, but when i execute run.sh using "USER sonarqube" SSH will not start because of missing privileges, is there any way i can start SSH as root without giving sonarqube sudo permissions?

thx

**Comment by pierre-guillot-sonarsource** [comment]
hello, what do you mean by `SSH will not start` ?
