### ISSUE TITLE
I started sonar with docker-compose, sonar could not connect to PostgreSQL

### ISSUE THREAD

**Issue by lijingchun0** [SonarSource/docker-sonarqube#311]
I use the docker-conpose.yml
[https://github.com/SonarSource/docker-sonarqube/blob/master/recipes/docker-compose-postgres-example.yml](url)

When I started sonar was connected to the default database
`2019.08.30 11:11:50 INFO  ce[][o.s.s.e.EsClientProvider] Connected to local Elasticsearch: [127.0.0.1:9001]
2019.08.30 11:11:50 INFO  ce[][o.sonar.db.Database] Create JDBC data source for jdbc:h2:tcp://127.0.0.1:9092/sonar
2019.08.30 11:11:50 WARN  ce[][o.s.d.DatabaseChecker] H2 database should be used for evaluation purpose only`

![image](https://user-images.githubusercontent.com/26979634/64017878-41eda080-cb5d-11e9-88f1-b16bd4d57d50.png)

**Comment by pierre-guillot-sonarsource** [comment]
hello, the docker compose works fine for me. Can you give us more detail on how you proceed ?
