### ISSUE TITLE
Public Test: sonarqube: waiting for web server to start ... Failed

### ISSUE THREAD

**Issue by cynthia-rempel** [SonarSource/docker-sonarqube#312]
Please include enough details to reproduce the problem: 

the command executed
sudo ./run-public-image-tests.sh

the host platform,
Linux RFA 4.15.0-54-generic #58~16.04.1-Ubuntu SMP Mon Jun 24 13:21:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Linux Mint 18.3
Docker version 18.09.8, build 0dd43dd87f

Please ensure your issue adheres to the following guidelines: 

- [ ] Please check the problem is not already reported, or a known issue documented in [`develop.md`](develop.md)
Nothing in develop.md seemed to indicate these issues to me...

- [ ] ,  error messages or relevant logs

Error messages terminal:

sudo ./run-public-image-tests.sh 
Deleted Containers:
fb707cdcbbb2b5183ba3516991bf677a76eaba191a8d7acb4f7587f27c2cdf3b

Deleted Images:
untagged: sonarqube:latest
untagged: sonarqube@sha256:bf99084b436f41616aac766593d7fbe6852a689965cfee801e8fe9cae24445a9
deleted: sha256:a84a2ad61bb7eb80a98e99e42c75e8d84174a1c2ba3baf8484dc6725f2ac51f8
deleted: sha256:213ad2f3d1c466d022283818843a600934db9841dce2c7a712a187a5ea218d8e
deleted: sha256:7b470949a4ae4de9989b9a53a99224768073dfc3f2bbbabf228369d5d0538586
deleted: sha256:814f2dcabbb42c4d36e59690f4ecc525de799c9534dee1babfa7ea3d98082148
deleted: sha256:c39b24c0e2c8e5c97ebfd25f5b3484a9a7a02df59b4c838df9c272b2360c7a57
deleted: sha256:1c6bdadb316287a819fc09dfd5216400c65fb671bb42b6530ea2022ac612147c
deleted: sha256:f86815412d2ec7d146224ac9402ac887fb88a6955eccf1f9ad305628a4608b11
deleted: sha256:bde1f512a54219e60697d2caafcc3f42617f07d2501cb27470f8a3443f0b8a56
deleted: sha256:d5e73098b8ae5cc89861fbf5422428b3bd050ef554d21bced2db5ef94872788a
deleted: sha256:1c95c77433e8d7bf0f519c9d8c9ca967e2603f0defbf379130d9a841cca2e28e

Total reclaimed space: 479.5MB
Using default tag: latest
latest: Pulling from library/sonarqube
1ab2bdfe9778: Pull complete 
7aaf9a088d61: Pull complete 
b9283b89acb2: Pull complete 
1e2c32308970: Pull complete 
287a2a8975c8: Pull complete 
42bda7a7d50a: Pull complete 
108494ec009a: Pull complete 
5f52660046ca: Pull complete 
2238933a53a8: Pull complete 
Digest: sha256:bf99084b436f41616aac766593d7fbe6852a689965cfee801e8fe9cae24445a9
Status: Downloaded newer image for sonarqube:latest
[info] sonarqube: container started: 4b4df9f9e94f003c98df6576124a03ca3dce13ea8b9c905c2c0813f10cf05047
[info] sonarqube: waiting for web server to start ...
[info] sonarqube: waiting for web server to start ...
[info] sonarqube: waiting for web server to start ...
[info] sonarqube: waiting for web server to start ...
[info] sonarqube: waiting for web server to start ...
[info] sonarqube: waiting for web server to start ...
[info] sonarqube: waiting for web server to start ...
[info] sonarqube: waiting for web server to start ...
[info] sonarqube: waiting for web server to start ...
[info] sonarqube: waiting for web server to start ...
HTTP/1.1 200 
[info] sonarqube: waiting for sonarqube to be ready ...
[info] sonarqube: waiting for sonarqube to be ready ...
[info] sonarqube: waiting for sonarqube to be ready ...
[info] sonarqube: waiting for sonarqube to be ready ...
[info] sonarqube: waiting for sonarqube to be ready ...
[info] sonarqube: waiting for sonarqube to be ready ...
[info] sonarqube: waiting for sonarqube to be ready ...
[info] sonarqube: waiting for sonarqube to be ready ...
[info] sonarqube: waiting for sonarqube to be ready ...
[info] sonarqube: waiting for sonarqube to be ready ...
[warn] sonarqube: could not confirm service started
[info] sonarqube: stopping container: 4b4df9f9e94f003c98df6576124a03ca3dce13ea8b9c905c2c0813f10cf05047
4b4df9f9e94f003c98df6576124a03ca3dce13ea8b9c905c2c0813f10cf05047

sonarqube => failure

Relevant Logs terminal:
sudo journalctl -f
[sudo] password for rfirstaid: 
-- Logs begin at Sun 2019-09-01 07:09:27 PDT. --
Sep 01 07:53:55 RFA sudo[6388]: pam_unix(sudo:session): session closed for user root
Sep 01 07:53:56 RFA ntpd[1673]: Deleting interface #10 docker0, 172.17.0.1#123, interface stats: received=0, sent=0, dropped=0, active_time=64 secs
Sep 01 07:53:56 RFA ntpd[1673]: Deleting interface #11 docker0, fe80::42:80ff:fe54:38d2%4#123, interface stats: received=0, sent=0, dropped=0, active_time=64 secs
Sep 01 07:53:56 RFA ntpd[1673]: Deleting interface #13 vethb149c91, fe80::a02a:c7ff:fe59:57ed%9#123, interface stats: received=0, sent=0, dropped=0, active_time=62 secs
Sep 01 07:53:58 RFA NetworkManager[1207]: <info>  [1567349638.3240] device (docker0): link disconnected (calling deferred action)
Sep 01 07:55:01 RFA CRON[6995]: pam_unix(cron:session): session opened for user root by (uid=0)
Sep 01 07:55:01 RFA CRON[6996]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Sep 01 07:55:01 RFA CRON[6995]: pam_unix(cron:session): session closed for user root
Sep 01 08:01:57 RFA sudo[7154]: rfirstaid : TTY=pts/1 ; PWD=/home/rfirstaid ; USER=root ; COMMAND=/bin/journalctl -f
Sep 01 08:01:57 RFA sudo[7154]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 01 08:02:12 RFA sudo[7159]: rfirstaid : TTY=pts/0 ; PWD=/home/rfirstaid/docker-sonarqube ; USER=root ; COMMAND=./run-public-image-tests.sh --help
Sep 01 08:02:12 RFA sudo[7159]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 01 08:02:13 RFA dockerd[1633]: time="2019-09-01T08:02:13.345667657-07:00" level=warning msg="failed to prune image docker.io/library/sonarqube@sha256:bf99084b436f41616aac766593d7fbe6852a689965cfee801e8fe9cae24445a9: No such image: sonarqube@sha256:bf99084b436f41616aac766593d7fbe6852a689965cfee801e8fe9cae24445a9"
Sep 01 08:02:45 RFA kernel: perf: interrupt took too long (6218 > 6215), lowering kernel.perf_event_max_sample_rate to 32000
Sep 01 08:03:27 RFA systemd-udevd[7308]: Could not generate persistent MAC address for veth49e4636: No such file or directory
Sep 01 08:03:27 RFA systemd-udevd[7309]: Could not generate persistent MAC address for veth4c79717: No such file or directory
Sep 01 08:03:27 RFA NetworkManager[1207]: <warn>  [1567350207.1539] device (veth49e4636): failed to find device 10 'veth49e4636' with udev
Sep 01 08:03:27 RFA kernel: docker0: port 1(veth4c79717) entered blocking state
Sep 01 08:03:27 RFA kernel: docker0: port 1(veth4c79717) entered disabled state
Sep 01 08:03:27 RFA kernel: device veth4c79717 entered promiscuous mode
Sep 01 08:03:27 RFA kernel: IPv6: ADDRCONF(NETDEV_UP): veth4c79717: link is not ready
Sep 01 08:03:27 RFA NetworkManager[1207]: <info>  [1567350207.1589] manager: (veth49e4636): new Veth device (/org/freedesktop/NetworkManager/Devices/11)
Sep 01 08:03:27 RFA NetworkManager[1207]: <warn>  [1567350207.1598] device (veth4c79717): failed to find device 11 'veth4c79717' with udev
Sep 01 08:03:27 RFA NetworkManager[1207]: <info>  [1567350207.1656] manager: (veth4c79717): new Veth device (/org/freedesktop/NetworkManager/Devices/12)
Sep 01 08:03:27 RFA NetworkManager[1207]: <info>  [1567350207.2401] devices added (path: /sys/devices/virtual/net/veth4c79717, iface: veth4c79717)
Sep 01 08:03:27 RFA NetworkManager[1207]: <info>  [1567350207.2402] device added (path: /sys/devices/virtual/net/veth4c79717, iface: veth4c79717): no ifupdown configuration found.
Sep 01 08:03:27 RFA NetworkManager[1207]: <info>  [1567350207.2616] devices added (path: /sys/devices/virtual/net/veth49e4636, iface: veth49e4636)
Sep 01 08:03:27 RFA NetworkManager[1207]: <info>  [1567350207.2617] device added (path: /sys/devices/virtual/net/veth49e4636, iface: veth49e4636): no ifupdown configuration found.
Sep 01 08:03:27 RFA dockerd[1633]: time="2019-09-01T08:03:27.345954974-07:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers: [nameserver 8.8.8.8 nameserver 8.8.4.4]"
Sep 01 08:03:27 RFA dockerd[1633]: time="2019-09-01T08:03:27.346028799-07:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers: [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]"
Sep 01 08:03:27 RFA containerd[1454]: time="2019-09-01T08:03:27.938166518-07:00" level=info msg="shim containerd-shim started" address="/containerd-shim/moby/4b4df9f9e94f003c98df6576124a03ca3dce13ea8b9c905c2c0813f10cf05047/shim.sock" debug=false pid=7351
Sep 01 08:03:28 RFA NetworkManager[1207]: <info>  [1567350208.4863] device (veth49e4636): driver 'veth' does not support carrier detection.
Sep 01 08:03:28 RFA kernel: eth0: renamed from veth49e4636
Sep 01 08:03:28 RFA kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth4c79717: link becomes ready
Sep 01 08:03:28 RFA kernel: docker0: port 1(veth4c79717) entered blocking state
Sep 01 08:03:28 RFA kernel: docker0: port 1(veth4c79717) entered forwarding state
Sep 01 08:03:28 RFA NetworkManager[1207]: <info>  [1567350208.5158] devices removed (path: /sys/devices/virtual/net/veth49e4636, iface: veth49e4636)
Sep 01 08:03:28 RFA NetworkManager[1207]: <info>  [1567350208.5160] device (veth4c79717): link connected
Sep 01 08:03:28 RFA NetworkManager[1207]: <info>  [1567350208.5163] device (docker0): link connected
Sep 01 08:03:29 RFA ntpd[1673]: Listen normally on 14 docker0 172.17.0.1:123
Sep 01 08:03:29 RFA ntpd[1673]: Listen normally on 15 docker0 [fe80::42:80ff:fe54:38d2%4]:123
Sep 01 08:03:29 RFA ntpd[1673]: bind(25) AF_INET6 fe80::fb:84ff:fe8f:7c45%11#123 flags 0x11 failed: Cannot assign requested address
Sep 01 08:03:29 RFA ntpd[1673]: unable to create socket on veth4c79717 (16) for fe80::fb:84ff:fe8f:7c45%11#123
Sep 01 08:03:29 RFA ntpd[1673]: failed to init interface for address fe80::fb:84ff:fe8f:7c45%11
Sep 01 08:03:29 RFA ntpd[1673]: new interface(s) found: waking up resolver
Sep 01 08:03:30 RFA avahi-daemon[1044]: Joining mDNS multicast group on interface veth4c79717.IPv6 with address fe80::fb:84ff:fe8f:7c45.
Sep 01 08:03:30 RFA avahi-daemon[1044]: New relevant interface veth4c79717.IPv6 for mDNS.
Sep 01 08:03:30 RFA avahi-daemon[1044]: Registering new address record for fe80::fb:84ff:fe8f:7c45 on veth4c79717.*.
Sep 01 08:03:31 RFA ntpd[1673]: Listen normally on 17 veth4c79717 [fe80::fb:84ff:fe8f:7c45%11]:123
Sep 01 08:03:31 RFA ntpd[1673]: new interface(s) found: waking up resolver
Sep 01 08:05:02 RFA CRON[7686]: pam_unix(cron:session): session opened for user root by (uid=0)
Sep 01 08:05:02 RFA CRON[7687]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Sep 01 08:05:02 RFA CRON[7686]: pam_unix(cron:session): session closed for user root
Sep 01 08:06:33 RFA dockerd[1633]: time="2019-09-01T08:06:33.294253949-07:00" level=info msg="Container 4b4df9f9e94f003c98df6576124a03ca3dce13ea8b9c905c2c0813f10cf05047 failed to exit within 10 seconds of signal 15 - using the force"
Sep 01 08:06:34 RFA containerd[1454]: time="2019-09-01T08:06:34.224647424-07:00" level=info msg="shim reaped" id=4b4df9f9e94f003c98df6576124a03ca3dce13ea8b9c905c2c0813f10cf05047
Sep 01 08:06:34 RFA dockerd[1633]: time="2019-09-01T08:06:34.233975408-07:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Sep 01 08:06:34 RFA NetworkManager[1207]: <info>  [1567350394.5414] device (veth4c79717): link disconnected
Sep 01 08:06:34 RFA kernel: docker0: port 1(veth4c79717) entered disabled state
Sep 01 08:06:34 RFA kernel: veth49e4636: renamed from eth0
Sep 01 08:06:34 RFA NetworkManager[1207]: <info>  [1567350394.5416] device (docker0): link disconnected (deferring action for 4 seconds)
Sep 01 08:06:34 RFA NetworkManager[1207]: <warn>  [1567350394.5812] device (veth49e4636): failed to find device 10 'veth49e4636' with udev
Sep 01 08:06:34 RFA NetworkManager[1207]: <info>  [1567350394.5890] manager: (veth49e4636): new Veth device (/org/freedesktop/NetworkManager/Devices/13)
Sep 01 08:06:34 RFA NetworkManager[1207]: <info>  [1567350394.6671] devices added (path: /sys/devices/virtual/net/veth49e4636, iface: veth49e4636)
Sep 01 08:06:34 RFA NetworkManager[1207]: <info>  [1567350394.6671] device added (path: /sys/devices/virtual/net/veth49e4636, iface: veth49e4636): no ifupdown configuration found.
Sep 01 08:06:34 RFA kernel: docker0: port 1(veth4c79717) entered disabled state
Sep 01 08:06:34 RFA avahi-daemon[1044]: Interface veth4c79717.IPv6 no longer relevant for mDNS.
Sep 01 08:06:34 RFA avahi-daemon[1044]: Leaving mDNS multicast group on interface veth4c79717.IPv6 with address fe80::fb:84ff:fe8f:7c45.
Sep 01 08:06:34 RFA kernel: device veth4c79717 left promiscuous mode
Sep 01 08:06:34 RFA kernel: docker0: port 1(veth4c79717) entered disabled state
Sep 01 08:06:34 RFA avahi-daemon[1044]: Withdrawing address record for fe80::fb:84ff:fe8f:7c45 on veth4c79717.
Sep 01 08:06:34 RFA NetworkManager[1207]: <info>  [1567350394.7582] devices removed (path: /sys/devices/virtual/net/veth49e4636, iface: veth49e4636)
Sep 01 08:06:34 RFA NetworkManager[1207]: <info>  [1567350394.7600] device (veth49e4636): driver 'veth' does not support carrier detection.
Sep 01 08:06:34 RFA NetworkManager[1207]: <info>  [1567350394.7608] device (veth4c79717): driver 'veth' does not support carrier detection.
Sep 01 08:06:34 RFA NetworkManager[1207]: <info>  [1567350394.8052] devices removed (path: /sys/devices/virtual/net/veth4c79717, iface: veth4c79717)
Sep 01 08:06:35 RFA sudo[7159]: pam_unix(sudo:session): session closed for user root
Sep 01 08:06:36 RFA ntpd[1673]: Deleting interface #14 docker0, 172.17.0.1#123, interface stats: received=0, sent=0, dropped=0, active_time=187 secs
Sep 01 08:06:36 RFA ntpd[1673]: Deleting interface #15 docker0, fe80::42:80ff:fe54:38d2%4#123, interface stats: received=0, sent=0, dropped=0, active_time=187 secs
Sep 01 08:06:36 RFA ntpd[1673]: Deleting interface #17 veth4c79717, fe80::fb:84ff:fe8f:7c45%11#123, interface stats: received=0, sent=0, dropped=0, active_time=185 secs
Sep 01 08:06:38 RFA NetworkManager[1207]: <info>  [1567350398.3219] device (docker0): link disconnected (calling deferred action)

**Comment by cynthia-rempel** [comment]
Thanks for all you do :)

**Comment by cynthia-rempel** [comment]
Trying:
docker-compose -f docker-compose-postgres-example.yml up

Gave me an error:
max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]

So I ran
sudo sysctl -w vm.max_map_count=262144

And that got farther...

But the tests are still failing...

Sep 01 08:29:21 RFA sudo[10096]: rfirstaid : TTY=pts/0 ; PWD=/home/rfirstaid/docker-sonarqube ; USER=root ; COMMAND=./run-public-image-tests.sh
Sep 01 08:29:21 RFA sudo[10096]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 01 08:29:25 RFA dockerd[1633]: time="2019-09-01T08:29:25.627863059-07:00" level=warning msg="failed to prune image docker.io/library/sonarqube@sha256:bf99084b436f41
Sep 01 08:29:27 RFA dockerd[1633]: time="2019-09-01T08:29:27.960966433-07:00" level=warning msg="failed to prune image docker.io/library/postgres@sha256:f766d03bb49c7dd
Sep 01 08:30:39 RFA NetworkManager[1207]: <warn>  [1567351839.5102] device (veth52b8783): failed to find device 21 'veth52b8783' with udev
Sep 01 08:30:39 RFA systemd-udevd[10217]: Could not generate persistent MAC address for veth8c2c879: No such file or directory
Sep 01 08:30:39 RFA systemd-udevd[10216]: Could not generate persistent MAC address for veth52b8783: No such file or directory
Sep 01 08:30:39 RFA NetworkManager[1207]: <info>  [1567351839.5170] manager: (veth52b8783): new Veth device (/org/freedesktop/NetworkManager/Devices/27)
Sep 01 08:30:39 RFA NetworkManager[1207]: <warn>  [1567351839.5180] device (veth8c2c879): failed to find device 22 'veth8c2c879' with udev
Sep 01 08:30:39 RFA NetworkManager[1207]: <info>  [1567351839.5270] manager: (veth8c2c879): new Veth device (/org/freedesktop/NetworkManager/Devices/28)
Sep 01 08:30:39 RFA kernel: docker0: port 1(veth8c2c879) entered blocking state
Sep 01 08:30:39 RFA kernel: docker0: port 1(veth8c2c879) entered disabled state
Sep 01 08:30:39 RFA kernel: device veth8c2c879 entered promiscuous mode
Sep 01 08:30:39 RFA kernel: IPv6: ADDRCONF(NETDEV_UP): veth8c2c879: link is not ready
Sep 01 08:30:39 RFA NetworkManager[1207]: <info>  [1567351839.6109] devices added (path: /sys/devices/virtual/net/veth8c2c879, iface: veth8c2c879)
Sep 01 08:30:39 RFA NetworkManager[1207]: <info>  [1567351839.6110] device added (path: /sys/devices/virtual/net/veth8c2c879, iface: veth8c2c879): no ifupdown configura
Sep 01 08:30:39 RFA NetworkManager[1207]: <info>  [1567351839.6411] devices added (path: /sys/devices/virtual/net/veth52b8783, iface: veth52b8783)
Sep 01 08:30:39 RFA NetworkManager[1207]: <info>  [1567351839.6412] device added (path: /sys/devices/virtual/net/veth52b8783, iface: veth52b8783): no ifupdown configura
Sep 01 08:30:39 RFA dockerd[1633]: time="2019-09-01T08:30:39.796914597-07:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default ex
Sep 01 08:30:39 RFA dockerd[1633]: time="2019-09-01T08:30:39.797926993-07:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers: [nameserver 2001:4860:
Sep 01 08:30:40 RFA containerd[1454]: time="2019-09-01T08:30:40.357747959-07:00" level=info msg="shim containerd-shim started" address="/containerd-shim/moby/8b50857957
Sep 01 08:30:40 RFA kernel: eth0: renamed from veth52b8783
Sep 01 08:30:41 RFA NetworkManager[1207]: <info>  [1567351841.0174] devices removed (path: /sys/devices/virtual/net/veth52b8783, iface: veth52b8783)
Sep 01 08:30:41 RFA kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth8c2c879: link becomes ready
Sep 01 08:30:41 RFA kernel: docker0: port 1(veth8c2c879) entered blocking state
Sep 01 08:30:41 RFA kernel: docker0: port 1(veth8c2c879) entered forwarding state
Sep 01 08:30:41 RFA NetworkManager[1207]: <info>  [1567351841.0176] device (veth52b8783): driver 'veth' does not support carrier detection.
Sep 01 08:30:41 RFA NetworkManager[1207]: <info>  [1567351841.0386] device (veth8c2c879): link connected
Sep 01 08:30:41 RFA NetworkManager[1207]: <info>  [1567351841.0389] device (docker0): link connected
Sep 01 08:30:42 RFA avahi-daemon[1044]: Joining mDNS multicast group on interface veth8c2c879.IPv6 with address fe80::9066:60ff:fe72:ddc5.
Sep 01 08:30:42 RFA avahi-daemon[1044]: New relevant interface veth8c2c879.IPv6 for mDNS.
Sep 01 08:30:42 RFA avahi-daemon[1044]: Registering new address record for fe80::9066:60ff:fe72:ddc5 on veth8c2c879.*.
Sep 01 08:30:43 RFA ntpd[1673]: Listen normally on 26 docker0 172.17.0.1:123
Sep 01 08:30:43 RFA ntpd[1673]: Listen normally on 27 docker0 [fe80::42:80ff:fe54:38d2%4]:123
Sep 01 08:30:43 RFA ntpd[1673]: Listen normally on 28 veth8c2c879 [fe80::9066:60ff:fe72:ddc5%22]:123
Sep 01 08:30:43 RFA ntpd[1673]: new interface(s) found: waking up resolver
Sep 01 08:33:33 RFA dockerd[1633]: time="2019-09-01T08:33:33.971828307-07:00" level=info msg="Container 8b50857957a7410181815eb0fb96cb2c4cbaf748f2647ec1b27273cfd002d392
Sep 01 08:33:34 RFA containerd[1454]: time="2019-09-01T08:33:34.854735494-07:00" level=info msg="shim reaped" id=8b50857957a7410181815eb0fb96cb2c4cbaf748f2647ec1b27273c
Sep 01 08:33:34 RFA dockerd[1633]: time="2019-09-01T08:33:34.863899100-07:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete ty
Sep 01 08:33:35 RFA kernel: veth52b8783: renamed from eth0
Sep 01 08:33:35 RFA NetworkManager[1207]: <warn>  [1567352015.1869] device (veth52b8783): failed to find device 21 'veth52b8783' with udev
Sep 01 08:33:35 RFA kernel: docker0: port 1(veth8c2c879) entered disabled state
Sep 01 08:33:35 RFA NetworkManager[1207]: <info>  [1567352015.1931] manager: (veth52b8783): new Veth device (/org/freedesktop/NetworkManager/Devices/29)
Sep 01 08:33:35 RFA NetworkManager[1207]: <info>  [1567352015.2083] device (veth8c2c879): link disconnected
ep 01 08:33:35 RFA NetworkManager[1207]: <info>  [1567352015.2084] device (docker0): link disconnected (deferring action for 4 seconds)
Sep 01 08:33:35 RFA NetworkManager[1207]: <info>  [1567352015.2563] devices added (path: /sys/devices/virtual/net/veth52b8783, iface: veth52b8783)
Sep 01 08:33:35 RFA NetworkManager[1207]: <info>  [1567352015.2564] device added (path: /sys/devices/virtual/net/veth52b8783, iface: veth52b8783): no ifupdown configura
Sep 01 08:33:35 RFA avahi-daemon[1044]: Interface veth8c2c879.IPv6 no longer relevant for mDNS.
Sep 01 08:33:35 RFA avahi-daemon[1044]: Leaving mDNS multicast group on interface veth8c2c879.IPv6 with address fe80::9066:60ff:fe72:ddc5.
Sep 01 08:33:35 RFA kernel: docker0: port 1(veth8c2c879) entered disabled state
Sep 01 08:33:35 RFA kernel: device veth8c2c879 left promiscuous mode
Sep 01 08:33:35 RFA kernel: docker0: port 1(veth8c2c879) entered disabled state
Sep 01 08:33:35 RFA avahi-daemon[1044]: Withdrawing address record for fe80::9066:60ff:fe72:ddc5 on veth8c2c879.
Sep 01 08:33:35 RFA NetworkManager[1207]: <info>  [1567352015.5097] devices removed (path: /sys/devices/virtual/net/veth52b8783, iface: veth52b8783)
Sep 01 08:33:35 RFA NetworkManager[1207]: <info>  [1567352015.5241] device (veth52b8783): driver 'veth' does not support carrier detection.
Sep 01 08:33:35 RFA NetworkManager[1207]: <info>  [1567352015.5261] device (veth8c2c879): driver 'veth' does not support carrier detection.
Sep 01 08:33:35 RFA NetworkManager[1207]: <info>  [1567352015.5536] devices removed (path: /sys/devices/virtual/net/veth8c2c879, iface: veth8c2c879)
Sep 01 08:33:36 RFA sudo[10096]: pam_unix(sudo:session): session closed for user root
Sep 01 08:33:37 RFA ntpd[1673]: Deleting interface #26 docker0, 172.17.0.1#123, interface stats: received=0, sent=0, dropped=0, active_time=174 secs
Sep 01 08:33:37 RFA ntpd[1673]: Deleting interface #27 docker0, fe80::42:80ff:fe54:38d2%4#123, interface stats: received=0, sent=0, dropped=0, active_time=174 secs
Sep 01 08:33:37 RFA ntpd[1673]: Deleting interface #28 veth8c2c879, fe80::9066:60ff:fe72:ddc5%22#123, interface stats: received=0, sent=0, dropped=0, active_time=174 se
Sep 01 08:33:39 RFA NetworkManager[1207]: <info>  [1567352019.3220] device (docker0): link disconnected (calling deferred action)
Sep 01 08:33:52 RFA sudo[10730]: rfirstaid : TTY=pts/1 ; PWD=/home/rfirstaid/docker-sonarqube/recipes ; USER=root ; COMMAND=/bin/journalctl -f
Sep 01 08:33:52 RFA sudo[10730]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 01 08:34:29 RFA sudo[10730]: pam_unix(sudo:session): session closed for user root
Sep 01 08:34:32 RFA sudo[10739]: rfirstaid : TTY=pts/1 ; PWD=/home/rfirstaid/docker-sonarqube/recipes ; USER=root ; COMMAND=/bin/journalctl -ex
Sep 01 08:34:32 RFA sudo[10739]: pam_unix(sudo:session): session opened for user root by (uid=0)

**Comment by pierre-guillot-sonarsource** [comment]
Hello ! Please explain what you are trying to achieve, and provide the SQ logs :)
