### ISSUE TITLE
Initialize conf and extensions directories with distribution content when empty

### ISSUE THREAD

**Issue by sns-seb** [SonarSource/docker-sonarqube#322]
To persist over time and/or customise SonarQube's configuration and extensions (eg. plugins and Database Drivers), one should mount the directories `conf` and/or `extensions` to Docker volumes or host directories.

Unless created the Docker volumes via the `docker run` command, these directories will be empty.

First of all, SonarQube running on empty `conf` or `extensions` directory will not run well, second of all, there is no convenient way to retrieve the files expected to be in these directories and then customize them.

To work around that, the SonarQube official images should ensure that, when container starts, `conf` and `extensions` directories are populated with Distribution content (in the same you'd find unpacking the SonarQube edition archive) when they are totally empty.

**Comment by 123dev** [comment]
init is there now in community-beta but it fails
https://github.com/SonarSource/docker-sonarqube/issues/366
