### ISSUE TITLE
JDBC settings from sonar.properties are ignored

### ISSUE THREAD

**Issue by sns-seb** [SonarSource/docker-sonarqube#323]
# Observed behavior

When mounting the `conf` directory with a customized `sonar.properties` file which defines the JDBC properties to connect to the database, SonarQube ignores these properties.

# Expected behavior

SonarQube connects to the database I specify by properties in the `sonar.properties` file.

# How to reproduce

(with SQ 8 community built from branch [feature/sl/initialized_read_volumes](https://github.com/SonarSource/docker-sonarqube/tree/feature/sl/initialized_read_volumes))

Create a `conf` directory to mount in SQ container:

```
mkdir -p /tmp/sq/conf
chmod 777 /tmp/sq/conf
```

Start SQ container to get an initialized conf directory. Observe that SQ is running on H2.
```
docker run -p "9000:9000" --name="sq" -v "/tmp/sq/conf:/opt/sonarqube/conf" -d sq8
```

Stop SQ:

```
docker stop sq
```

Add JDBC properties to `sonar.properties`:

```
sudo vi /tmp/sq/conf/sonar.properties
```

Sample jdbc properties, exact values do not matter since they are ignored:

```
sonar.jdbc.username=foo
sonar.jdbc.password=bar
sonar.jdbc.url=jdbc:postgresql://localhost:5432/acme
```

Restart SQ container:

```
docker start sq
```

Connect to SQ and/or check logs, SQ still connect to an H2 database.

# Suspected cause

Entry point script `run.sh` passes env properties to the SonarQube process for JDBC properties `sonar.jdbc.name`, `sonar.jdbc.password` and `sonar.jdbc.url`.

These properties takes precedence over the content of `sonar.properties` *even when empty*.

In the scenario above, `sonar.jdbc.url` is empty because its value is the one of the env variable `SONAR_JDBC_URL`. Even when `SONAR_JDBC_URL` is not set, this defines an empty value to the env property.

An empty `sonar.jdbc.url` is interpreted by SonarQube as "connect to H2".

Note that as a consequence, the same problem applies to property `sonar.web.javaAdditionalOpts`.

**Comment by QkiZMR** [comment]
This bug is still present in 7.9.4-community version
