### ISSUE TITLE
Password exposed when start with env vars

### ISSUE THREAD

**Issue by krebs-GVL** [SonarSource/docker-sonarqube#334]
```
$ docker run -d -e sonar.jdbc.password=secretPassword sonarqube
b84f962f619bbcee5378e0fc140d37253bcfb0efb99e1f08c83f22d04184591d
$ ps aux | grep 'secretPassword'
999        335 50.3  1.6 9041080 266924 ?      Ssl  07:51   0:05 java -jar lib/sonar-application-7.9.1.jar -Dsonar.log.console=true -Dsonar.jdbc.username=sonar -Dsonar.jdbc.password=sonar -Dsonar.jdbc.url= -Dsonar.web.javaAdditionalOpts= -Djava.security.egd=file:/dev/./urandom -Dsonar.jdbc.password=secretPassword
krebs      771  0.0  0.0  21536  1016 pts/6    S+   07:51   0:00 grep secretPassword
```

No special permissions required to extract the postgres password, or any other parameter. Thats why one usually don't pass sensible parameters via command line arguments/opts.

**Comment by pierre-guillot-sonarsource** [comment]
Hi, well, don't. Use a variable environment, or use sonar.properties.

**Comment by pierre-guillot-sonarsource** [comment]
Ah, i see. good point, thanks. we will consider your input to upgrade the doc about that. I think we want to leave this option open for people that want to do that way, but we should not recommend it officially.

**Comment by pierre-guillot-sonarsource** [comment]
Hi, we did upgraded the documentation and now recommend to use the properties file to set theses property. The env variable still work, but as a second choice.
