### ISSUE TITLE
Sonar configuration file is not loaded even if it's present

### ISSUE THREAD

**Issue by RomanCRS** [SonarSource/docker-sonarqube#339]
Hello, everyone,

I'm trying to use version 7.9.1 in the ECS cluster and there is an issue with connection to database using a configuration file. Basically, when I pass username, password and DB URL using environment variables, I'm able to integrate SonarQube with DB. However, when I build an image with a configuration file where username, password and DB URL are stored, SonarQube doesn't load configuration from file. Also, I was trying to upload a configuration file on persistent volume and use it in SonarQube(folder /opt/sonarqube/conf). Unfortunately, nothing has changed. From my point of view, we need some additional options, where we can say - "I would like to load configuration from the file during initial bootstrap" or something like this. 

If you need some additional information, please let me know.

**Comment by pierre-guillot-sonarsource** [comment]
Hello,

If i understand correctly, you are refering to the same issue as #323, fixed with the 8.0 version :)
