### ISSUE TITLE
Give access to sonar.properties

### ISSUE THREAD

**Issue by osechet** [SonarSource/docker-sonarqube#34]
Some plugins reads their configuration from the `sonar.properties` file in the `conf` directory. It could be nice to have an access to that file from the host (i.e. with a volume).

**Comment by andreas-lundgren-storytel** [comment]
Hi!

The mapping to a persisted volume is done at line 13 in recipes.md, "sonarqube_conf:/opt/sonarqube/conf"

If you want to map the conf folder to a specific folder on the host, you can change from a named volume to a path mapped volume according to https://docs.docker.com/compose/compose-file/#volumes-volume-driver.

**Comment by osechet** [comment]
Sorry, my mistake. I made a typo when writing the volume path on the command line and I couldn't make it work. It's now working well.

**Comment by LorenzoBettini** [comment]
@andreas-lundgren-storytel but since the conf directory is not exposed as a volume, mounting locally will not generate any default configuration file, the same for bundled-plugins, it will be created empty

**Comment by LorenzoBettini** [comment]
Sorry, my comment is completely wrong. Locally mounted directories have nothing to do with the volumes defined in the docker compose file. I made confusion.
