### ISSUE TITLE
Container starts but without initial plugins being initialized

### ISSUE THREAD

**Issue by dmpe** [SonarSource/docker-sonarqube#346]
- [x] Please check the problem is not already reported, or a known issue documented in [`develop.md`](develop.md)
----------------------
Hi, 
I am facing an interesting issue where although (binaries and therefore) docker image contains (7.9.1) an initial set of plugins (check even at runtime), when container starts they are not initialized so that SQ can recognized them. Therefore SQ instance is empty, without any plugins.  

I admit to use official stable helm chart and postgres db. However, in chart i do not use any `plugins` setting. I have even tried to do this below but it still does not help. 

```
plugins:
  deleteDefaultPlugins: false
```

Did anybody else face same or similar issue. I can reproduce it in 100% of cases, both on 7.9.1 and 7.9. 
Thanks for any tips

**Comment by pierre-guillot-sonarsource** [comment]
Hello, did you checked the write permission for the extensions folder ? Are other folders ok ? (data, logs, conf)

**Comment by dmpe** [comment]
Thanks for quick answer. 
On my minikube, I use static volumes. Thus, I force sonarqube volume to have `999:999` user and group rights - this allows container (and GUI) actually boot up - like at all so that I can login, etc. 
In log, I see: 

```
o.s.ce.app.CeServer] Compute Engine starting up...
2019.11.08 10:15:59 INFO  ce[][o.e.p.PluginsService] no modules loaded
2019.11.08 10:15:59 INFO  ce[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
2019.11.08 10:15:59 INFO  ce[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
2019.11.08 10:15:59 INFO  ce[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2019.11.08 10:16:01 INFO  ce[][o.s.s.e.EsClientProvider] Connected to local Elasticsearch: [127.0.0.1:9001]
2019.11.08 10:16:01 INFO  ce[][o.sonar.db.Database] Create JDBC data source for jdbc:postgresql://sonarqube-postgresql:5432/sonarqube
2019.11.08 10:16:02 INFO  ce[][o.s.s.p.ServerFileSystemImpl] SonarQube home: /opt/sonarqube
2019.11.08 10:16:03 INFO  ce[][o.s.c.c.CePluginRepository] Load plugins
2019.11.08 10:16:03 INFO  ce[][o.s.c.c.ComputeEngineContainerImpl] Running Community edition
```
app/plugins and app/plugins/tmp are empty. 
app/temp/ and folders within do not contains any plugins as well
app/tmp/ is empty too

**Comment by SF-DK** [comment]
I had this same problem, started the 7.9.1 container as the instructions describe but used bind mounts instead of volumes and my extensions folder never populated with the plugins. I had to start the container using volumes, mount those to another container, and then copy the data over to my bind mounts to get all the default plugins

**Comment by dmpe** [comment]
Apropo: At our work, the issue was volume permissions which had to be adjusted dynamically too, using e.g. busybox.
