### ISSUE TITLE
Sonarqube 8.0 release is not available in Dockerhub

### ISSUE THREAD

**Issue by DanielFran** [SonarSource/docker-sonarqube#348]
Sonarqube 8.0 release is not available in Dockerhub.

Latest available version is 8.0-beta version 
````txt
    7.9.1-community, 7.9-community, latest, lts
    8.0-community-beta, 8-community-beta, community-beta
    8.0-developer-beta, 8-developer-beta, developer-beta
    8.0-enterprise-beta, 8-enterprise-beta, enterprise-beta
````

Please ensure your issue adheres to the following guidelines: 

- [x] Please check the problem is not already reported, or a known issue documented in [`develop.md`](develop.md)
- [x] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs

**Comment by pierre-guillot-sonarsource** [comment]
Well, it is available as a beta image. Which mean it is not recommended for production yet. What is your issue here ?

**Comment by DanielFran** [comment]
@pierre-guillot-sonarsource  I see that final version 8 was released 29 days ago (https://github.com/SonarSource/sonarqube/releases/tag/8.0) and did not find it on dockerhub.

Was tincking that something get wrong...

**Comment by pierre-guillot-sonarsource** [comment]
The docker image is in beta, the SQ it contains is not.

**Comment by jangrewe** [comment]
Is there any ETA on when it will become `latest`, or any specific issues you need help with?

**Comment by pierre-guillot-sonarsource** [comment]
We plan to remove the `beta` flag with SQ 8.1 by the end of the year. If you want to help, try the beta image and give us feedback about issues you got :)

I personally am not really happy with the state of the volume/folder binding, as users can encounter permissions issues. The upgrade procedure is not smooth as well.

**Comment by pierre-guillot-sonarsource** [comment]
As this beta status is normal, i'm closing this. Feel free to test the demo version and give us feedback :)
