### ISSUE TITLE
use `--no-install-recommends` with `apt-get install`

### ISSUE THREAD

**Issue by sns-seb** [SonarSource/docker-sonarqube#349]
This option disables installation of recommended dependencies of the installed packages.

Canonical itself recommends using it (see https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends).

However, given the package we currently do install (`curl` `unzip` `libfreetype6` and `libfontconfig1`), the benefit are not obvious.

However, it's worth trying and confirming.

**Comment by michal-duda-sonarsource** [comment]
With the packages we currently install this does not decrease the size of the image. We will look into making the images smaller in the upcoming version though.
