### ISSUE TITLE
Any plans for LTS alpine?

### ISSUE THREAD

**Issue by alexjurkiewicz** [SonarSource/docker-sonarqube#35]
Hi Sonar, as per title -- do you plan to deploy lts version on Alpine rather than Debian? It's something $work would consider using.

**Comment by Godin** [comment]
Hi @alexjurkiewicz ,
current LTS - is 5.6, and since the moment of its release it is available in alpine variant both in this repo and at hub as `5.6-alpine`.

**Comment by alexjurkiewicz** [comment]
Thanks, sorry to be more clear will you publish a lts-alpine target?

**Comment by Godin** [comment]
@alexjurkiewicz excuse me for the delay - here is PR for this: https://github.com/docker-library/official-images/pull/1939

**Comment by alexjurkiewicz** [comment]
Thanks @Godin ! We're using it locally :)
