### ISSUE TITLE
Bundled Plugins not available/working in 7.9.x

### ISSUE THREAD

**Issue by esune** [SonarSource/docker-sonarqube#355]
In the latest `7.9.x` version of SonarQube the `/opt/sonarqube/lib/bundled-plugins` directory is missing and bundling plugins in for automatic installation in a Docker image doesn't to work anymore.
This used to work fine up to 6.7.7, I haven't tried anything in-between 6.7.7 and 7.9.1.

### How to reproduce
Use the following Dockerfile:
```
FROM sonarqube:lts

RUN mkdir /opt/sonarqube/lib/bundled-plugins

ADD https://github.com/Coveros/zap-sonar-plugin/releases/download/sonar-zap-plugin-1.2.0/sonar-zap-plugin-1.2.0.jar /opt/sonarqube/lib/bundled-plugins
```

Build the image using the following command: `docker build -t sonarqube .` 
Run the new image using `docker run --name sonarqube -p 9000:9000 sonarqube`.

No plugins other than the default ones will be available.

Default plugins also used to ship in the `bundled-plugins` directory, allowing a persistent volume to be mounted  on `/opt/sonarqube/extensions/plugins` without clearing them, however this is not the case anymore (a new sonarqube instance with a volume mounted on the plugins directory results in no pre-installed plugins).

**Comment by michal-duda-sonarsource** [comment]
1. AFAIK `lib/bundled-plugins` has not been used to store plugins for quite a long time, including version 6.7.  SonarQube 6.7 copied the plugins from `lib/bundled-plugins` to `extensions/plugins` on startup for compatibility but this mechanism was dropped in 7.x. So the only way for 7.x to see the plugins is to use and copy to `extensions/plugins` directory.

2.  > a new sonarqube instance with a volume mounted on the plugins directory results in no pre-installed plugins

Can you provide an example on how you mount the volume to the container?

**Comment by esune** [comment]
[This](https://github.com/BCDevOps/sonarqube/blob/master/sonarqube-postgresql-template.yaml#L120-L122) is an example of how I mount I volume (in OpenShift) to the `/opt/sonarqube/extensions/plugins` directory.

The wish is to ship the image with a pre-bundled set of plugins, and let each user install new ones if necessary. The volume is required to both allow the installation of new plugins AND persist the data between pod restarts. A docker volume mounted to the same path would be an example of how to reproduce this locally.

If the plugins are shipped in `/opt/sonarqube/extensions/plugins` it won't be possible to mount a new volume on the directory to allow additional plugins (or even updates to the shipped ones) to be manually installed by the Sonar admins as it will overwrite the existing directory with an empty folder on first start, requiring ALL plugins to be installed manually.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hello @esune ,

a lot has changed in the mean time and 3rd party plugins and the language analyzers are now completely separated from it. feel free to create a thread in our [community forum](https://community.sonarsource.com/) if you are still facing issues with the deployment of new plugins
