### ISSUE TITLE
support aarch64 platform

### ISSUE THREAD

**Issue by congweitao** [SonarSource/docker-sonarqube#359]
Is there any roadmap for supporting aarch64 platform ?

**Comment by pierre-guillot-sonarsource** [comment]
Hi, nothing under our radar for arm. What is the specific use case here ?

**Comment by congweitao** [comment]
We are going to deploy sonarqube on arm64 servers in production, however, we can not compile it successfully. I wonder if there is a solution from the community.

root@osd2 sonarqube-7.9.1]# java -version
openjdk version "11.0.5" 2019-10-15 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.5+10-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.5+10-LTS, mixed mode, sharing)

[root@osd2 sonarqube-7.9.1]# lscpu
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                96
On-line CPU(s) list:   0-95
Thread(s) per core:    1
Core(s) per socket:    48
Socket(s):             2
NUMA node(s):          4
Model:                 0
CPU max MHz:           2600.0000
CPU min MHz:           200.0000
BogoMIPS:              200.00
L1d cache:             64K
L1i cache:             64K
L2 cache:              512K
L3 cache:              49152K
NUMA node0 CPU(s):     0-23
NUMA node1 CPU(s):     24-47
NUMA node2 CPU(s):     48-71
NUMA node3 CPU(s):     72-95
Flags:                 fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop

[root@osd2 sonarqube-7.9.1]# ./gradlew build
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :plugins:compileJava NO-SOURCE
> Task :plugins:processResources NO-SOURCE
> Task :plugins:classes UP-TO-DATE
> Task :plugins:jar UP-TO-DATE
> Task :plugins:assemble UP-TO-DATE
> Task :plugins:licenseMain NO-SOURCE
> Task :plugins:licenseTest NO-SOURCE
> Task :plugins:license UP-TO-DATE
> Task :plugins:compileTestJava NO-SOURCE
> Task :plugins:processTestResources NO-SOURCE
> Task :plugins:testClasses UP-TO-DATE
> Task :plugins:test NO-SOURCE
> Task :plugins:check UP-TO-DATE
> Task :plugins:build UP-TO-DATE
> Task :server:compileJava NO-SOURCE
> Task :server:processResources NO-SOURCE
> Task :server:classes UP-TO-DATE
> Task :server:jar UP-TO-DATE
> Task :server:assemble UP-TO-DATE
> Task :server:licenseMain NO-SOURCE
> Task :server:licenseTest NO-SOURCE
> Task :server:license UP-TO-DATE
> Task :server:compileTestJava NO-SOURCE
> Task :server:processTestResources NO-SOURCE
> Task :server:testClasses UP-TO-DATE
> Task :server:test NO-SOURCE
> Task :server:check UP-TO-DATE
> Task :server:build UP-TO-DATE
> Task :sonar-check-api:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sonar-check-api:compileJava'.
> error: release version 8 not supported

**Comment by nixel2007** [comment]
SonarQube needs java11 to compile and run

**Comment by pierre-guillot-sonarsource** [comment]
Why would you compile it with aarch64 ? Don't you only need an aarch64 JVM to run the zip ?

**Comment by congweitao** [comment]
I run it successfully, thanks!

发自我的 iPhone

在 2020年1月2日，18:15，Pierre Guillot <notifications@github.com<mailto:notifications@github.com>> 写道：


Why would you compile it with aarch64 ? Don't you only need an aarch64 JVM to run the zip ?

**Comment by pierre-guillot-sonarsource** [comment]
Glad you sorted it out :)
