### ISSUE TITLE
can't comtomize sonar.web.context through env variable

### ISSUE THREAD

**Issue by olderzhou** [SonarSource/docker-sonarqube#362]
Please ensure your issue adheres to the following guidelines: 
when i use command "

docker run  --name local-sonarqube  -e sonar.web.context=/sonarqube  -p 8083:9000   -d sonarqube
"  i got  error info like this 
![image](https://user-images.githubusercontent.com/8716969/71436295-c75a1980-2727-11ea-8e59-e5611709bfc7.png)

the point is , when i find this , i want to edit the sonar.web.context through sonar.properties, but i con't do that, because i can't use vi/vim. also i can't use apt-get to install vim, this is so bad.

- [x] Please check the problem is not already reported, or a known issue documented in [`develop.md`](develop.md)
- [x] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs

**Comment by pierre-guillot-sonarsource** [comment]
Hi, could you consider having a prepared sonar.properties file ready on the host, and mount it on the container at startup ?

**Comment by olderzhou** [comment]
I tried that, it was't work for me, when i do that, it's really fixed the context-path issue, but the whole system is down, i can't even generate a token for project analyse. it's redirected to login page again and again, which means the token is invalid. i guess the reason could be proxy, but it is real .

**Comment by charleech** [comment]
I used to face this kind of issue a while ago when placing the *SonarQube* behind the *Apache HTTP*. 

Please refer to the [my old SonarQube Google groups issue](https://groups.google.com/forum/#!topic/sonarqube/TszcMdon4xM)

Hope this may help.

**Comment by michal-duda-sonarsource** [comment]
All the server side properties can be overridden with environment variables starting from SonarQube 8.2 (https://docs.sonarqube.org/latest/setup/environment-variables/) so I'm closing this.

**Comment by kschlesselmann** [comment]
@michal-duda-sonarsource It appears that those environment variables do not work
```
docker run -p 9000:9000 -e SONAR_LOG_LEVEL=TRACE sonarqube
```
as a simple test does nothing for example :-(

Another question: If this feature is going to work will I be able to configure every property (from plugins) via the corresponding env variable?

**Comment by michal-duda-sonarsource** [comment]
@kschlesselmann 
Thanks for reporting, some of the environment variables indeed do not work in current version. I opened a ticket to track this (it also contains a list of properties affected): [SONAR-13272](https://jira.sonarsource.com/browse/SONAR-13272)

Regarding plugin properties: only server properties can currently be overridden by environment variables. Feel free to suggest this feature on the [community forums](https://community.sonarsource.com/c/suggestions/features).

**Comment by Jaff** [comment]
When is this expected to be fixed? I am having to maintain a special version of our startup script to handle this bug.

**Comment by michal-duda-sonarsource** [comment]
We plan to fix it in next version - 8.3.

**Comment by michal-duda-sonarsource** [comment]
Fixed in SonarQube 8.3 image.
