### ISSUE TITLE
Sonarqube Beta no longer validating downloaded artifacts on build

### ISSUE THREAD

**Issue by damianb** [SonarSource/docker-sonarqube#363]
It appears that in the rewrite of the Sonarqube Dockerfiles, the beta images no longer perform any form of validation of the artifacts being downloaded and placed into the Docker image - the only security remaining is that of the use of TLS for the HTTP connection wherein the Sonarqube zip file is downloaded.  

While there is a code path which may provide implicit trust in the event that the image is built with the zip itself locally, the other branch wherein the zip is downloaded is used as a silent failover should the zip not be correctly loaded into the image by the Dockerfile.

A correct fix would be reimplementing GPG verification of any downloaded artifacts.  Yes, GPG is a pain to deal with, but it's far better than the consequences of a successful supply chain attack.  [The docker-library org has some guidance on effective use of fault-tolerant GPG verification here.](https://github.com/docker-library/faq#openpgp--gnupg-keys-and-verification)

**Comment by pierre-guillot-sonarsource** [comment]
Agree. Just a minor detail : there is no execution path where we look for a zip locally : this is only on master, for our own tests. Released Dockefile are on the `branch-8.1` and exclusively download zip. I created a jira ticket to track this down : https://jira.sonarsource.com/browse/SONAR-12889

**Comment by michal-duda-sonarsource** [comment]
We brought back artifact validation in SQ 8.2 images.
