### ISSUE TITLE
https://hub.docker.com/_/sonarqube : SonarQube 8.x first installation : --init parameter invalid?

### ISSUE THREAD

**Issue by traderggl** [SonarSource/docker-sonarqube#364]
The instructions at above location state:

**Initialize SONARQUBE_HOME folder tree with --init. This will initialize the default configuration, copy embedded plugins, and prepare the data folder:

$ docker run --rm \
-v $SONARQUBE_HOME/conf:/opt/sonarqube/conf \
-v $SONARQUBE_HOME/extensions:/opt/sonarqube/extensions \
-v $SONARQUBE_HOME/data:/opt/sonarqube/data \
sonarqube --init**

But looks like --init parameter on last line is invalid? since I get:

**06:11:58.791 [main] WARN org.sonar.application.config.AppSettingsLoaderImpl - Configuration file not found: /opt/sonarqube/conf/sonar.properties
Exception in thread "main" java.lang.IllegalArgumentException: Command-line argument must start with -D, for example -Dsonar.jdbc.username=sonar. Got: --init**

**Comment by pierre-guillot-sonarsource** [comment]
The doc is incorrect. `latest` refer to 7.9X version, which does not use that --init flag. I just opened a PR, this will be corrected soon.

So in short, you need to specify the edition you are using with a `edition-beta` docker tag.
