### ISSUE TITLE
--init steps for developer edition fails

### ISSUE THREAD

**Issue by 123dev** [SonarSource/docker-sonarqube#366]
Please ensure your issue adheres to the following guidelines: 

- [checked] Please check the problem is not already reported, or a known issue documented in [`develop.md`](develop.md)
- [done] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs

From [dockerhub](https://hub.docker.com/_/sonarqube/?tab=description)
Initialize SONARQUBE_HOME folder tree with --init. This will initialize the default configuration, copy embedded plugins, and prepare the data folder:
```
$ docker run --rm \
-v $SONARQUBE_HOME/conf:/opt/sonarqube/conf \
-v $SONARQUBE_HOME/extensions:/opt/sonarqube/extensions \
-v $SONARQUBE_HOME/data:/opt/sonarqube/data \
sonarqube:community-beta --init
```
Fails (Note Step 1 was properly done)
Here's the error:

```
docker run --rm \
> -v $SONARQUBE_HOME/conf:/opt/sonarqube/conf \
> -v $SONARQUBE_HOME/extensions:/opt/sonarqube/extensions \
> -v $SONARQUBE_HOME/data:/opt/sonarqube/data \
> sonarqube:community-beta --init
Unable to find image 'sonarqube:community-beta' locally
community-beta: Pulling from library/sonarqube
8ec398bc0356: Already exists
8e866b095956: Pull complete
cb5d513ad8c4: Pull complete
fab0db7e7659: Pull complete
d5b1c96fce5b: Pull complete
d1d1257d3231: Pull complete
fe05c565fb35: Pull complete
509bc80592f4: Pull complete
a215890cb471: Pull complete
Digest: sha256:150fe29bcacc3845e523c3e5afd6f1283102338485356dcf7bf2095492f0a173
Status: Downloaded newer image for sonarqube:community-beta
cp: cannot create regular file '/opt/sonarqube/conf/./sonar.properties': Permission denied
cp: cannot create regular file '/opt/sonarqube/conf/./wrapper.conf': Permission denied
Failed to initialize content of /opt/sonarqube/conf
cp: cannot create directory '/opt/sonarqube/extensions/./jdbc-driver': Permission denied
cp: cannot create directory '/opt/sonarqube/extensions/./plugins': Permission denied
Failed to initialize content of /opt/sonarqube/extensions
```

**Comment by rvandegrift** [comment]
The image runs as uid/gid 999:999 - you probably need `chown -R 999:999 $SONARQUBE_HOME/*`.

**Comment by michal-duda-sonarsource** [comment]
We recommend using named volumes instead of bind mounts. Also starting from version 8.2 we removed `--init` that was introduced in 8.1 beta images after feedback we received. I'll close this, feel free to create a new issue if there still is an issue.
