### ISSUE TITLE
A way to enable Postgres SSL securely

### ISSUE THREAD

**Issue by cvdsande** [SonarSource/docker-sonarqube#376]
Although it's not well documented, SonarQube supports SSL connections to Postgres databases by modifying the JDBC URL to include &sslmode=require

This is useful in a public cloud setting (where we're most likely to use docker-sonarqube) to connect to a managed database service.

My issue is that the only way to enable SSL is by including the username and password in the JDBC url like this:
```
jdbc:postgresql://1.2.3.4:5432/sonarqube?user=dbuser&password=dbpassword&sslmode=require'
```
That works fine, except the full plain text connection string is then printed out in docker logs, and therefore gets stored on the volume that contains the logs. So by enabling better security, we open a new big hole.

It would be great if we could encrypt the JDBC url in sonar.properties (this is already supported) and then hide the username and password from the log files.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @cvdsande ,

i am rather sure that you can configure the jdbc credentials separate from the connection string, like with 

* SONAR_JDBC_URL
* SONAR_JDBC_USERNAME
* SONAR_JDBC_PASSWORD

if you are facing any issues with this, please report them to our [community forum](https://community.sonarsource.com/) as this impacts the application more than it does the docker images here
