### ISSUE TITLE
Merged Snyk action requires authenticated account.

### ISSUE THREAD

**Issue by konstruktoid** [SonarSource/docker-sonarqube#385]
https://github.com/SonarSource/docker-sonarqube/pull/378 causes forked repositories to fail since `snyk` requires an authenticated account.

https://github.com/konstruktoid/docker-sonarqube/runs/532105491?check_suite_focus=true#step:6:9

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @konstruktoid ,

yeah this is a valid concern but there is currently no traction of moving away from snyk. maybe we will migrate to trivy in the future to ease this but as of now a external PR is validated by a sonarsourcer that will make sure that the QA passes if the PR qualifies for a merge
