### ISSUE TITLE
extensions_save is no more used in 8.2 Docker

### ISSUE THREAD

**Issue by gjabouley-invn** [SonarSource/docker-sonarqube#391]
Hello

Thanks for your work on those SonarQube docker images, so handy!

Any reason why the mechanism to populate /extensions folder at container startup from the folder /extensions_save [has been removed from the run.sh script in 8.2](https://github.com/SonarSource/docker-sonarqube/pull/371/commits/fafc0619afcf1ba8929142207baf1251d81d9152)?

We were relying on this behavior to provide a dedicated image with bundled plugins in /extensions_save that got properly deployed at startup into /extensions (which is a host mountpoint).

**Comment by michal-duda-sonarsource** [comment]
Hi,
You can find rationale for the change here: https://jira.sonarsource.com/browse/MMF-1881. The mechanism of copying extensions has changed but still exists if you use [volumes](https://docs.docker.com/storage/volumes/) and not [bind mounts](https://docs.docker.com/storage/bind-mounts/). If you use a docker volume for SonarQube `extensions` directory, the volume will be initialized with all bundled plugins. On the other hand if you use bind mounts, you have to prepare the host directory yourself and set appropriate permissions on it.

After this change you still should be able to extend the image and copy your non-default plugins to `/opt/sonarqube/extensions/plugins` directory in the image and that would make the volume initialized with everything you need. Of course that won't work when using bind mounts (just as it won't work currently for the default plugins).

**Comment by gjabouley-invn** [comment]
Indeed we were using bind mount + running SonarQube image with specific user id mapping host user. This does not work well when mixing bind mount and Docker volume because of permissions.

One **big** advantage of using bind mount instead of volume is that you can store application data on a dedicated host partition. Using Docker volume will use by default /var/lib/docker path...

Also i see there is a change for 8.3 which will properly support running the image with any user id, doing a large chown during startup 👍

**Comment by gjabouley-invn** [comment]
@michal-duda-sonarsource quick question, what is the point of persisting /data folder, which contains basically ElasticSearch data that can be recreated?

**Comment by pierre-guillot-sonarsource** [comment]
Recreating elasticsearch indexes can take hours on a huge database

**Comment by tobias-trabelsi-sonarsource** [comment]
I think there is nothing left to do in this thread to i will go ahead and close it :)
