### ISSUE TITLE
Mechanism to publish sonar.properties in jdbc store

### ISSUE THREAD

**Issue by rverma-jm** [SonarSource/docker-sonarqube#392]
When we run sonarqube using docker, 1 way of providing sonarqube's configuration is using sonar.properties.

I found that when mount pass sonar.properties from docker, sonar does load the properties. Unfortunately they are not reflected in UI, since sonar only shows values from db.

Wondering if we can do an initialisation script which load something like sonar.extraProperties and load them to db.

**Comment by michal-duda-sonarsource** [comment]
Thanks for reporting @rverma-jm. Indeed changes in `sonar.properties` are not reflected in the UI and it might be a bit misleading. This is also the case when you use environment variables to set the server side settings in 8.2. @christophelevis any opinion on this?

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @rverma-jm ,

this thread is rather old and there have been internal discussions about that. as of now we want to move in the direction that only configurations that do not persist in the database should be valid for `sonar.properties`. you can find more information in [SONAR-11818](https://jira.sonarsource.com/browse/SONAR-11818)
