### ISSUE TITLE
During Docker build on version 8.2 the process is interrupted due to missing  references

### ISSUE THREAD

**Issue by Cadames** [SonarSource/docker-sonarqube#394]
+ apk update
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.11/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.70f61090.tar.gz: No such file or directory
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.11/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.ca2fea5b.tar.gz: No such file or directory
2 errors; 17 distinct packages available

The command '/bin/sh -c set -ex     && apk update     && apk upgrade     && apk add --no-cache --update gnupg unzip curl     && for server in $(shuf -e ha.pool.sks-keyservers.net                             hkp://p80.pool.sks-keyservers.net:80                             keyserver.ubuntu.com                             hkp://keyserver.ubuntu.com:80                             pgp.mit.edu) ; do         gpg --batch --keyserver "$server" --recv-keys F1182E81C792928921DBCAB4CFCA4A29D26468DE && break || : ;     done     && mkdir --parents /opt     && cd /opt     && curl --fail --location --output sonarqube.zip --silent --show-error  "$SONARQUBE_ZIP_URL"     && curl --fail --location --output sonarqube.zip.asc --silent --show-error  "${SONARQUBE_ZIP_URL}.asc"     && gpg --batch --verify sonarqube.zip.asc sonarqube.zip     && unzip -q sonarqube.zip     && mv "sonarqube-${SONARQUBE_VERSION}" sonarqube     && rm sonarqube.zip*     && rm -rf $SONARQUBE_HOME/bin/*     && chmod -R 777 "${SQ_DATA_DIR}" "${SQ_EXTENSIONS_DIR}" "${SQ_LOGS_DIR}" "${SQ_TEMP_DIR}"' returned a non-zero code: 2
 ▸    Error: docker build exited with Error: 2

**Comment by michal-duda-sonarsource** [comment]
Are you building the image locally with `docker build ...`? If so, can you check if `docker build -network=host ...` improves the situation?

**Comment by Cadames** [comment]
With the added network=host I am still getting the error

+ apk update
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.11/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.70f61090.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.11/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.ca2fea5b.tar.gz: No such file or directory

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @Cadames ,

this seems like a network error on your system and not directly related to our docker images. we updated a bunch of stuff in the mean time, so please open a new issue if you still can not build the images or even better create a thread in our [community forum](https://community.sonarsource.com/)
