### ISSUE TITLE
error while creating sonarqube docker-container with postgresql database

### ISSUE THREAD

**Issue by RamanaChowdam** [SonarSource/docker-sonarqube#397]
i am written a docker-compose file for creating sonarqube with postgresql
please find log files are attached below

version: "3.3"
services:
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    restart: always
    depends_on:
      - db
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_logs:/opt/sonarqube/logs
  db:
    image: postgres
    container_name: postgres
    restart: always
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

~                      
![Screenshot from 2020-04-15 23-05-27](https://user-images.githubusercontent.com/60684784/79369208-36c17680-7f6e-11ea-8e57-e7dc014fc734.png)
![Screenshot from 2020-04-15 23-05-32](https://user-images.githubusercontent.com/60684784/79369214-388b3a00-7f6e-11ea-8d8a-55791655f82c.png)
![Screenshot from 2020-04-15 23-05-57](https://user-images.githubusercontent.com/60684784/79369220-3923d080-7f6e-11ea-897b-716a7d7d9610.png)

**Comment by charleech** [comment]
Regarding to the picture attached, I understand that it is about the permission of the `/opt/sonarqube/data` inside the docker which is configured via `./sonarqube_data:/opt/sonarqube/data`

Please refer to my answer at the issue [Container fails because ./logs/es.log](https://github.com/SonarSource/docker-sonarqube/issues/340#issuecomment-548188342) and I hope that it may help.

**Comment by michal-duda-sonarsource** [comment]
Indeed, if you use bind mounts, you need to take care of setting permissions and initializing host directory yourself. As an alternative you can use docker volumes which will handle both things for you. Have a look at this [example docker-compose.yml file](https://github.com/SonarSource/docker-sonarqube/blob/master/example-compose-files/sq-with-postgres/docker-compose.yml).
