### ISSUE TITLE
Redirection issue on /users endpoint

### ISSUE THREAD

**Issue by lazam** [SonarSource/docker-sonarqube#398]
Please ensure your issue adheres to the following guidelines: 

- [x] Please check the problem is not already reported, or a known issue documented in [`develop.md`](develop.md)
- [x] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs

- Sonarqube version: Docker-CE 8.2

The issue occurs when I'm trying to update a user or create a user when **SONAR_WEB_CONTEXT_ENV** is enabled. It automatically redirects to a login page for new session. When running it without **SONAR_WEB_CONTEXT_ENV**, it works fine.

Below is the logs from Nginx in front of Sonarqube: 

> 172.16.0.100 - - [20/Apr/2020:06:18:15 +0000] "POST /sonartest/api/users/create HTTP/1.1" 401 - "https://xxxxxxx/sonartest/admin/users" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36" "xxXXXmB+xHuD5cTAAA6"`

>172.16.0.100 - - [20/Apr/2020:06:18:16 +0000] "GET /sonartest/api/users/identity_providers HTTP/1.1" 200 24 "https://xxxxx/sonartest/sessions/new?return_to=%2Fsonartest%2Fadmin%2Fusers" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36" "XxxxXXnmB+xHuD5cTAAA7"

**Comment by michal-duda-sonarsource** [comment]
**SONAR_WEB_CONTEXT_ENV**? Don't you mean **SONAR_WEB_CONTEXT**?

**Comment by lazam** [comment]
Here's the env variable that we're using:

>   SONARQUBE_JDBC_USERNAME
  SONARQUBE_JDBC_PASSWORD
  SONARQUBE_JDBC_URL
  SONAR_WEB_SSO_ENABLE: "true"
  SONAR_WEB_SSO_LOGINHEADER
  SONAR_WEB_SSO_NAMEHEADER
  SONAR_WEB_SSO_EMAILHEADER
  SONAR_WEB_SYSTEMPASSCODE

And we include this following lines in the config file:

> sonar.web.context=/sonartest
sonar.forceAuthentication=true


Upon investigating, our SSO works properly and I only encounter the issue when adding **sonar.web.context** in the config file.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @lazam ,

this thread is rather old and seems more related to sonarqube and not that much to the docker images. if you are still facing issues, please open a thread in our [community forum](https://community.sonarsource.com/) about that.
