### ISSUE TITLE
Provide a sonarqube enterprise LTS tag

### ISSUE THREAD

**Issue by hibbert** [SonarSource/docker-sonarqube#399]
I can see that you now provide a sonarqube enterprise image but this only seems to be version 8.2 which is not the LTS. Please could you provide an LTS tag for the enterprise image?

**Comment by pierre-guillot-sonarsource** [comment]
Hi, we adapted some things in SonarQube in order to run smoothly on docker with the 8.x series. So there is no 7.9 official docker image, and we cannot build them, that won't work properly. Either you wait for the 8 LTS (early 2021), or you go with the 8.2 version and upgrade frequently.
