### ISSUE TITLE
latest-alpine target

### ISSUE THREAD

**Issue by nixel2007** [SonarSource/docker-sonarqube#40]
Hi!

In our company we try to use alpine-based containers as much as possible.

Currently there are 5 targets in docker-library:
* latest
* lts
* 5.6.1
* lts-alpine
* 5.6.1-alpine

So, if i want to user latest alpine image, i need to specify 5.6.1-alpine target and update it manually every sonar-release.

Could you add a new latest-alpine target, please?

Thank you!

**Comment by Godin** [comment]
@nixel2007 PR for Docker Hub created - https://github.com/docker-library/official-images/pull/1998

**Comment by Godin** [comment]
@nixel2007 PR has been merged, name of a tag is `alpine` for the reasons explained in https://github.com/docker-library/official-images/pull/1998#issuecomment-236731807 , and it is available in Docker Hub

Enjoy!

**Comment by nixel2007** [comment]
Thanks!
