### ISSUE TITLE
creating sonarqube project automatically

### ISSUE THREAD

**Issue by RamanaChowdam** [SonarSource/docker-sonarqube#400]
Please ensure your issue adheres to the following guidelines: 

- [x] Please check the problem is not already reported, or a known issue documented in [`develop.md`](develop.md)
- [x] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs
on how to create sonarqube project automatically for the ci/cd process.i don't want to create project by manually going to UI .is there any scripts are available for the creation process

**Comment by michal-duda-sonarsource** [comment]
I'm not aware of any scripts that exist that do that but SonarQube exposes a Web API that could be used to provision a project. If you want to have a look, the Web API docs are embedded in SonarQube UI (`/web_api`). 

As this is not really Docker related subject, please feel free to suggest this feature on the [community forum](https://community.sonarsource.com/c/suggestions/features).
