### ISSUE TITLE
8.2 -> 8.3 migration and permissions on volumes

### ISSUE THREAD

**Issue by MeyerNils** [SonarSource/docker-sonarqube#407]
I had a sonarqube 8.2-community docker container running with suggested volumes. During my update to 8.3-community the content of the volumes could not be accessed any more, as 8.3 alpines sonarqube user and group have other IDs since the 8.2 openjdk:11-jre-slim sonarqube user and group

Did I miss something important here, should this be somehow changed or at least documented?

**Comment by michal-duda-sonarsource** [comment]
@MeyerNils Can you please post your configuration or details on how you are running the image? 

We indeed changed the UID and GID of the `sonarqube` user defined in the image (because of the previous UID and GIT conflicts with some OS-es)  but with some of the changes in the entrypoint script this shouldn't impact the existing setup.

After the changes you should be able to run the image with any UID and GID you want using `--user` flag (or alternative way depending on what sort of setup you have) or with the default `sonarqube` user with UID=1000, GID=1000.

**Comment by MeyerNils** [comment]
@michal-duda-sonarsource, thanks for quick your reply. I'm using it with my own image build on top of your images and encountered this on one of my systems. Tried to reproduce this by using your images directly but could not. I'll give it another try with some simplified custom images on top during the next days.

**Comment by MeyerNils** [comment]
I can reproduce using my different versions of my Dockerfile from VCS, but need to simplify them to allow easier understanding.

**Comment by MeyerNils** [comment]
I can reproduce it - it's related to changing users in later build steps. I started with a Dockerfile looking like this
```Dockerfile
FROM sonarqube:8.2-community                                                                                                                                                                            
USER root
# Do something as root, e.g. import certificates to connect via ldaps
USER sonarqube
```
I built the image and start a container based on this with a `testvolume`
```bash
$ docker build .
...
Successfully built ad17e26b07d4
$ docker run --name sonarqubetest --rm -p 9000:9000 -v testvolume:/opt/sonarqube/data ad17e26b07d4
```
Server ist starting up correctly. I stopped (and automatically removed due to --rm flag) the container and adjusted Dockerfile to point to 8.3
```Dockerfile
FROM sonarqube:8.3-community                                                                                                                                                                            
USER root
# Do something as root, e.g. import certificates to connect via ldaps
USER sonarqube
```
Building and starting again
```bash
$ docker build .
...
Successfully built 67254901eaee
$ docker run --name sonarqubetest --rm -p 9000:9000 -v testvolume:/opt/sonarqube/data 67254901eaee
....
Caused by: java.nio.file.AccessDeniedException: /opt/sonarqube/data/es6/nodes/0/node.lock
...
2020.05.08 20:34:28 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 1
2020.05.08 20:34:28 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
2020.05.08 20:34:28 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
```
The full stack trace can be found in [sonarqube_8.3_startup_log.txt](https://github.com/SonarSource/docker-sonarqube/files/4601545/sonarqube_8.3_startup_log.txt)

Should I do something in a different way or is this a scenario you need to consider?

**Comment by michal-duda-sonarsource** [comment]
Can you removing both `USER` instructions in your Dockerfile and keeping everything else the same?

**Comment by MeyerNils** [comment]
Can't remove the USER instructions for my 8.2 image (some activities in between are failing due to missing permissions) but can do so for my 8.3 image. If I do so, my problem disappeared.

Thanks you very much!

Can you share the reason why with me? I guess, due to the changed OS user handling in your alpine based image?

**Comment by michal-duda-sonarsource** [comment]
This is not due to OS changes, it's due to removing USER instruction from the Dockerfile and switching to using [su-exec](https://github.com/ncopa/su-exec) to step down from root in 8.3.

**Comment by MeyerNils** [comment]
Thanks @michal-duda-sonarsource, understood the changes and why things are working now with your suggested change.
