### ISSUE TITLE
Curl removed in 8.3

### ISSUE THREAD

**Issue by pascalberger** [SonarSource/docker-sonarqube#409]
With version 8.3 of the images curl is no longer available (because of https://github.com/SonarSource/docker-sonarqube/commit/db5225f43c0d29e5aca482681aebc382cc4eb28d). curl is required for implementing a healthcheck. Is it possible to add curl back into the image? Or is it required to build custom images on top for implementing a healthcheck?

**Comment by tobias-trabelsi-sonarsource** [comment]
Hey @pascalberger ,
official docker images [can not have healthchecks](https://github.com/docker-library/faq#healthcheck), so curl is a dependencie that we do not realy need in this image. maybe you can make use of wget like in [this example](https://github.com/docker-library/healthcheck/tree/master/sonarqube) ?
Greetings

**Comment by tobias-trabelsi-sonarsource** [comment]
i'll consider this resolved as there is no response within a few month :sweat_smile:
