### ISSUE TITLE
7.9 LTS-<version> Images?

### ISSUE THREAD

**Issue by dbeezt** [SonarSource/docker-sonarqube#412]
Just wanted to check on the availability of specific versions for the LTS image? I'm hoping to utilise the latest version of LTS SonarQube, which has led me to look at '7.9.3-community', '7.9-community', and 'lts' on [Docker Hub](https://hub.docker.com/_/sonarqube/) but I'm a bit puzzled as there's no greater depth of detail for the 'lts' image despite there being four downloadable versions for the lts installer located here: https://www.sonarqube.org/downloads/.

Apologies if this would be an issue better raised in the forums, but figured I should go right to the source.

Thanks.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @dbeezt ,
i hope i understand your question correctly, please elaborate if this is not the case.

as you have already noticed there are some tags for the LTS version on the docker hub if you want to have a specific patch release as for example 7.9.1 you can. the image with the tag `lts` points to the latest lts release (you can see it [here](https://hub.docker.com/layers/sonarqube/library/sonarqube/lts/images/sha256-cb05827804e633bb7eabcecd06e755cdb0b7cc9a4fd0c78bbef592bf84096dcf?context=explore) ), while the tag `7.9-community` points to the latest release of 7.9, which is the current LTS.

Hope that answers your question and in general we take a closer look at the community forum, so if you have any question feel free to ask them there. i will close the issue for now 

have a good day
