### ISSUE TITLE
No more bash nor gcc 9.1

### ISSUE THREAD

**Issue by ggciteo** [SonarSource/docker-sonarqube#413]
Hi,
I juste downloaded the files for version 8 developer edition.
And it fails because gcc-libs does not exists anymore at the given url, and bash is not present in alpine

I got this in the webapp log the of docker image i'm using :
2020-06-11T22:48:52.975685234Z env: can't execute 'bash': No such file or directory

**Comment by ggciteo** [comment]
My bad...
It's that f* crlf problem...

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @ggciteo 
happens to the best of us ;D 

i will close the issue as it seems you already found a solution
