### ISSUE TITLE
Init Email configuration from env var

### ISSUE THREAD

**Issue by madmath03** [SonarSource/docker-sonarqube#416]
Would be nice to setup Email configuration from environment variables (like `email.* `):

From:
https://github.com/SonarSource/docker-sonarqube/blob/27217fb0cfcd9469571eff710eae434a92a26f72/8/enterprise/run.sh#L17-L27

To:
```java
if [[ "$envvar_key" =~ sonar.* ]] || [[ "$envvar_key" =~ ldap.* ]] || [[ "$envvar_key" =~ email.* ]]; then 
```

Thread: https://community.sonarsource.com/t/init-email-configuration-from-env-var-with-docker/27608

Will probably send a PR for that.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @madmath03 ,

as stated in the PR you submitted we will be working on a proper solution in due time with the work connected to [SONAR-11818](https://jira.sonarsource.com/browse/SONAR-11818 )
