### ISSUE TITLE
After restarting the Sonarqube, getting 'Too many open files in system' error

### ISSUE THREAD

**Issue by navinprasadk** [SonarSource/docker-sonarqube#419]
I have installed sonarqube 8.2 using docker-compose. Using it for more than a month. After restarting the sonarqube, I can't able to access it. When I checked the logs, it is showing that  

> Caused by: java.nio.file.FileSystemException: /opt/sonarqube/data/es6/nodes/0/indices/4W1V8Ex8Q2aFbNK_lGm84w/2/translog/translog-463.ckp: Too many open files in system

I have executed the below commands also, still it is not working

> sysctl -w vm.max_map_count=262144
> sysctl -w fs.file-max=65536
> ulimit -n 65536
> ulimit -u 4096

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @navinprasadk ,

we are not monitoring the issues here that closely. if you require help i would suggest you take a look at our [community forum](https://community.sonarsource.com/) next time (:
for this specific problem i would suggest you try to reboot the host system or if this is not possible you increase the limit even further then the one that is recommended from our side

Have a good day
