### ISSUE TITLE
Add environment variable to remove version from application home page

### ISSUE THREAD

**Issue by jessejbordenctr** [SonarSource/docker-sonarqube#421]
Please ensure your issue adheres to the following guidelines: 

- [x] Please check the problem is not already reported, or a known issue documented in [`develop.md`](develop.md)
- [x] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs

For security reasons, add an environment variable to allow removing the version and build info from the home page of the sonarqube application.

Relevant part of code in UI to make conditional:
https://github.com/SonarSource/sonarqube/blob/3f6f5496277c76c2498fd245a112931d19830497/server/sonar-web/src/main/js/app/components/GlobalFooter.tsx

```
 {!hideLoggedInInfo && sonarqubeVersion && (

          <li className="page-footer-menu-item">

            {translateWithParameters('footer.version_x', sonarqubeVersion)}

          </li>

        )}
```

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @jessejbordenctr ,

this seems like a feature request. please make your voice heard in our [community forum](https://community.sonarsource.com/c/suggestions/features/14), so that PMs can have a look at it :)
