### ISSUE TITLE
Default plugins missing sonar-java-plugin

### ISSUE THREAD

**Issue by Jaff** [SonarSource/docker-sonarqube#422]
When starting up a fresh instance of SonarQube 8.4.1-developer (or -enterprise) the plugins directory is empty and must be manually populated. Unfortunately, the Marketplace selection of available plugins is missing sonar-java-plugin. This previously was available in earlier versions (currently running 8.3.1-developer.)

**Comment by william00179** [comment]
I am also having this issue on 8-community. 

I have had to manually download plugins and install them. I'm only seeing 79 plugins listed of the ~150+ available online.

**Comment by narsla** [comment]
I experenced the same this on 8.4.2 comunity edition. Only a few plugins and the Java plugin is not available.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi there,

have you read our [documentation](https://docs.sonarqube.org/latest/setup/install-server/#header-3) about using sonarqube with docker? currently you have to create a named volume and copy the bundled plugins in there but this will probably change with the next release (with the resolvement of [this ticket here](https://jira.sonarsource.com/browse/MMF-2042) to be more precise).

also note that we are not really monitoring the github issues. you will get faster feedback on issues like this in the [community forum](https://community.sonarsource.com/)

**Comment by tobias-trabelsi-sonarsource** [comment]
closing after 2 weeks of silence
