### ISSUE TITLE
Options set trough sonar.properties file not being shown active in the UI

### ISSUE THREAD

**Issue by ricardojdsilva87** [SonarSource/docker-sonarqube#424]
Hello,

I've encountered a strange issue, I'm using the following helm chart to deploy sonarqube.
https://github.com/helm/charts/tree/master/stable/sonarqube
This is the registry:
https://hub.docker.com/_/sonarqube

We are using v8.4.1-developer and we know that the sonar.properties file is being correctly set, because for example if we set sonar.auth.github.apiUrl to a wrong URL, after deploying the login via GHE stops working.

We noticed this "bug" on the UI after trying to apply sonar.auth.github.groupsSync for example and the button was not active, so we thought we were doing something wrong, but the feature worked with no problem, even tough the button appears inactive.

![image](https://user-images.githubusercontent.com/12953702/91591172-66d54900-e954-11ea-95ed-1766d0048557.png)

The same happens for example with the clientID and the clientsecret that are set but not shown on the UI.

It's not a critical "bug" since everything seems to be working, but can lead to some confusion when trying to set these options.

Thanks for the help

**Comment by daviddyball** [comment]
Can confirm this on `8.6-community` too. None of the options I set in `sonar.properties` or via environment variables are set in the admin UI

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @ricardojdsilva87 and @daviddyball ,

this is a known issue that will hopefully go away with [SONAR-11818](https://jira.sonarsource.com/browse/SONAR-11818). these settings should not be set via `sonar.properties` or environment variables as they persist in the database and as such should only be set in the UI.

**Comment by ricardojdsilva87** [comment]
Hello @tobias-trabelsi-sonarsource thanks for the clarification.
Just to let you know why we are using this it's because we have a few different versions of sonarqube instances running, with the helm chart and  a config file it makes it easy for us to spin up a new instance and also make sure if something is changed by mistake in the settings we can quickly fix it. 
It was just a visual helper seeing the setting changed on the UI after applying the settings, although everything worked with no issues.
Thanks again!
