### ISSUE TITLE
sonarqube7.9.1-community cannot connect to kube-network

### ISSUE THREAD

**Issue by jae-work** [SonarSource/docker-sonarqube#427]
**Issue**
While trying to move from Sonarqube 7.1 container to 7.9.1 it is unable to connect to the database pod. 

The sonarqube7.9 pod is only able to use the H2 database and cannot resolve the hostname of the database. when exec-ing into the pod i am unable to use standard tools like ping, however i also cannot curl the db pod nor google.com, getting a could not resolve hostname response.

The Sonarqube7.1 pod definition is almost identical though with slightly different environment variables and is working correctly.

Both pod's spec include:

item | 7.1|7.9
---|---|---
volume mount | data, extensions | data, extensions, logs
environment vars|ES_JAVA_OPTS<br>sonar.search.javaAdditionalOpts<br>SONARQUBE_JDBC_USERNAME<br>SONARQUBE_JDBC_PASSWORD<br>SONARQUBE_JDBC_URL|SONAR_SEARCH_JAVAOPTS<br>SONAR_JDBC_USERNAME<br>SONARQUBE_JDBC_URL<br>SONAR_JDBC_PASSWORD
port| TCP/9000 | TCP/9000

some of the Env variables appear to have changed names and they do not help the issue except that i can load a H2 version to test with.

ymls below
[psql-postgres.yml.txt](https://github.com/SonarSource/docker-sonarqube/files/5272728/psql-postgres.yml.txt)
[psql-storage.yml.txt](https://github.com/SonarSource/docker-sonarqube/files/5272729/psql-storage.yml.txt)
[psql-svc.yml.txt](https://github.com/SonarSource/docker-sonarqube/files/5272730/psql-svc.yml.txt)
[sonar71-sonar.yml.txt](https://github.com/SonarSource/docker-sonarqube/files/5272731/sonar71-sonar.yml.txt)
[sonar71-storage.yml.txt](https://github.com/SonarSource/docker-sonarqube/files/5272732/sonar71-storage.yml.txt)
[sonar71-svc.yml.txt](https://github.com/SonarSource/docker-sonarqube/files/5272733/sonar71-svc.yml.txt)
[sonar79-sonar.yml.txt](https://github.com/SonarSource/docker-sonarqube/files/5272734/sonar79-sonar.yml.txt)
[sonar79-storage.yml.txt](https://github.com/SonarSource/docker-sonarqube/files/5272735/sonar79-storage.yml.txt)
[sonar79-svc.yml.txt](https://github.com/SonarSource/docker-sonarqube/files/5272736/sonar79-svc.yml.txt)

**logs**
[web.log](https://github.com/SonarSource/docker-sonarqube/files/5272743/web.log)
[sonar.log](https://github.com/SonarSource/docker-sonarqube/files/5272745/sonar.log)

**infrastructure**
Azure Kubernetes Service, 
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"1c93c592501dbc0c14e23b5ea2be8f6ea947a3a5", GitTreeState:"clean", BuildDate:"2020-08-25T01:56:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
thanks 
---

- [x] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs
- [x] Please check the problem is not already reported, or a known issue documented in [`develop.md`](develop.md)

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @jae-work ,

sonarqube 7.9.1 is EOL. you should upgrade to our latest LTS release which is as of now 8.9.1 and with that you might be interested in [our helm chart](https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube) and our documentation [how to run sonarqube on k8s](https://docs.sonarqube.org/latest/setup/sonarqube-on-kubernetes/).

if you need additional information/help feel free to create a thread in our [community forum](https://community.sonarsource.com/)
