### ISSUE TITLE
Error scanner   in project with openjdk  14 new feature records

### ISSUE THREAD

**Issue by wesleyosantos91** [SonarSource/docker-sonarqube#428]
Please ensure your issue adheres to the following guidelines: 

- [ X ] Please check the problem is not already reported, or a known issue documented in [`develop.md`](develop.md)
- [ X ] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs
help me i used openjdk 14 in my project, and return error in scanner sonar image sonarqube:8.4.2-community.
logger error in down:

[ERROR] Unable to parse source file : 'src/main/java/io/wesleyosantos91/springsandbox/model/response/ResponsePessoa.java'
[ERROR] Parse error at line 8 column 0: Syntax error on tokens, ClassHeader expected instead
[ERROR] Unable to parse source file : 'src/main/java/io/wesleyosantos91/springsandbox/model/request/RequestPostPessoa.java'
[ERROR] Parse error at line 10 column 7: Syntax error on token "record", @ expected

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @wesleyosantos91  ,

i think you are talking about a scanner and not the server component of sonarqube, so this is the wrong repository. for support please create a post in our [community forum](https://community.sonarsource.com/)
