### ISSUE TITLE
Configuration file not found: /opt/sonarqube/conf/sonar.properties

### ISSUE THREAD

**Issue by lpzcarlos** [SonarSource/docker-sonarqube#433]
when I install Sonarqube 7.9.x o 8.x in kubernetes, I always get an initial error, which can cause the pod to not be created correctly.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @lpzcarlos ,
this seems to be a problem with your deployment. The path exists in the docker images, so you either: 

- overwrite the `conf` folder with something else
- start the container with permissions that denies access to the properties file

you can also configure sonarqube 8.x completely via [environment variables](https://docs.sonarqube.org/latest/setup/environment-variables/) btw

also please note that sonarqube is not yet supported to be deployed on kubernetes (while i know that some people are successfully running sq on k8s thou) and that you will get faster answers in our [community forum](https://community.sonarsource.com/) for questions like this :)
