### ISSUE TITLE
sonar-scaner-cli:latest image unable to reach localhost:9000  gitlab ci

### ISSUE THREAD

**Issue by krishna0536** [SonarSource/docker-sonarqube#438]
sonar.sourceEncoding=UTF-8
sonar.scm.disabled=true
sonar.projectKey=projectkey
sonar.projectName=projectname
sonar.projectVersion=1
sonar.host.url=http://localhost:9000

**Comment by nixel2007** [comment]
Local host points to container, not your host. Check docker docs about network.

**Comment by krishna0536** [comment]
stages:
  - sonarscaner

sonarqube-check:
    stage: sonarscaner
    tags:
        - dockerrunner
    allow_failure: True
    image:
        name: sonarsource/sonar-scanner-cli:latest
        entrypoint: [""]
    variables:
        GIT_DEPTH: 0
    script:
        - sonar-scanner -X -Dproject.settings=./sonar-scanner.properties -Dsonar.qualitygate.wait=true

**Comment by krishna0536** [comment]
tha above file it -gitlab-ci.yml file

**Comment by krishna0536** [comment]
above file is .gitlab-ci-yml file

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @krishna0536 ,

i assume that your initial post are your `sonar.properties`, so the answer from @nixel2007 is the one that you are looking for. 
> Local host points to container, not your host. Check docker docs about network.

if you have any other questions or need help regarding your configuration, please feel free to create a post in our [community forum](https://community.sonarsource.com/) as github issues are not the right place for support :)
