### ISSUE TITLE
sonarqube losing pull-request settings

### ISSUE THREAD

**Issue by Jaff** [SonarSource/docker-sonarqube#444]
Please ensure your issue adheres to the following guidelines: 

- [x ] Please check the problem is not already reported, or a known issue documented in [`develop.md`](develop.md)
I've encountered this in several projects, and witnessed it again today. I set pull-request properties in the UI, api.github.com, organization/repository slug, later run analysis and it complains about missing properties for PR decoration, and I see they are missing. I think there needs to be a way to set these properties when invoking analysis, like sonar.host.url, etc. Often when I setup analysis for a new project, I am adding it on a branch, for later merge to master. I invoke the CI for the project, where I include basic settings (sonar.projectKey, sonar.projectName, etc.) But when I go to the analysis page, there is nothing available for default master branch, and inevitably a warning about missing PR decoration settings for the branch newly added. I can only set the properties on the master page.
Unfortunately, this is non-repeatable, making a test case problematic.

**Comment by Jaff** [comment]
According to the logs, Pull Request decoration was successful:
```
2020.11.10 01:26:51 INFO  ce[AXWvwz1rB8_USamMJmPB][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Webhooks | globalWebhooks=0 | projectWebhooks=0 | status=SUCCESS | time=2ms
2020.11.10 01:26:51 INFO  ce[AXWvwz1rB8_USamMJmPB][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Pull Request decoration | status=SUCCESS | time=5ms

```
 but analysis still shows warning: "Unable to decorate the pull request. Please configure the pull request properties in the project administration."
Viewing properties, all looks good

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @Jaff ,
this looks rather unrelated to our docker image and more to sonarqube in general. do you mind creating a new thread in our [community forum](https://community.sonarsource.com/)? makes it easier to track and more people might be able to help you there

**Comment by tobias-trabelsi-sonarsource** [comment]
Closing this as there was no additional response after 25 days. If you are still facing this issue, feel free to create a new thread in our forum :)
