### ISSUE TITLE
worker《id》 found no pending task (including indexation task). Disabling indexation task lookup for this worker until next SonarQube restart.

### ISSUE THREAD

**Issue by lijinhai255** [SonarSource/docker-sonarqube#447]
Please ensure your issue adheres to the following guidelines: 

This repository is used for technical issues only. For general Support like questions, please create a new Thread in our [Community Forum](https://community.sonarsource.com/)

- [ ] Please check the problem is not already reported, or a known issue documented in [`develop.md`](develop.md)
- [ ] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @lijinhai255 ,
this looks like a upgrade message (so migrating from one version to another) and is expected. as stated in the issue template, please create a post in our [Community Forum](https://community.sonarsource.com/) for general support questions
