### ISSUE TITLE
Dockerfile for v8 community has permissions issues in entrypoint

### ISSUE THREAD

**Issue by alfabravoteam** [SonarSource/docker-sonarqube#450]
If the current Dockerfile is used, there's an error on permissions when trying to run the newly created image. The image cannot be ran in its current status.

By adding: 
```
RUN chmod +x ${SONARQUBE_HOME}/bin/run.sh 
RUN chmod +x ${SONARQUBE_HOME}/bin/sonar.sh
```

Right after `COPY --chown`, the image runs as expected.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @alfabravoteam ,
where are you building the image on? the scripts do have the right permission flag in this git repository already and file permissions are preserved in git, so the only way to remove them is to build on a filesystem that does not have file permissions (NTFS for example).

```
stat 8/community/sonar.sh
File: 8/community/sonar.sh
Size: 110       	Blocks: 8          IO Block: 4096   regular file
Device: fe00h/65024d	Inode: 1984073     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/ttrabelsi)   Gid: ( 1000/ttrabelsi)

stat 8/community/run.sh
File: 8/community/run.sh
Size: 2121      	Blocks: 8          IO Block: 4096   regular file
Device: fe00h/65024d	Inode: 1984072     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/ttrabelsi)   Gid: ( 1000/ttrabelsi)

```

**Comment by alfabravoteam** [comment]
Hm, indeed might have travaled from a NTFS partition to somewhere in the linux VM where I was working. THanks for helping out and sorry for the noise. Was afraid this might require a change in the dockerfile :)
