### ISSUE TITLE
Fail to get bootstrap index from server: Expected URL scheme 'http' or 'https' but no colon was found

### ISSUE THREAD

**Issue by AllenJol** [SonarSource/docker-sonarqube#451]
when I want to use sonarqube-community-branch-plugin whith sonarqube:8.5.1-community，but i got a problem about: Fail to get bootstrap index from server: Expected URL scheme 'http' or 'https' but no colon was found

I've go to google to search some solution，but i haven't go any answer,so I want to someone can help me,thank you very much。

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @AllenJol  ,

when do you see this message?
It seems to be related to the plugin that you want to use rather than the docker image of sonarqube. i would advise you to open an issue on the [github repo](https://github.com/mc1arke/sonarqube-community-branch-plugin) of this plugin.

**Comment by AllenJol** [comment]
I  agree with your,and i think it is also the problem about plugin

**Comment by AllenJol** [comment]
it seems that i should config https to sonar?

**Comment by tobias-trabelsi-sonarsource** [comment]
You could try to set the base URL (Administration -> Configuration -> General -> Server base URL), but i am not familiar with the plugin. could still be worth a shot :shrug:

**Comment by tobias-trabelsi-sonarsource** [comment]
With this i would go ahead and close this issue, as it is not related to the docker image. If you have further questions, feel free to check out our [community forum](https://community.sonarsource.com/) :)
