### ISSUE TITLE
modify the value of uid/gid in dockerfile

### ISSUE THREAD

**Issue by mayou33** [SonarSource/docker-sonarqube#456]
It is recommended to modify the value of uid/gid in dockerfile.
 There are many software dockerfile , uid/gid is set to 1000 .
 
 For example, uid/gid is set to 9000  in dockerfile.
 ----
     && addgroup -S -g 9000 sonarqube \
    && adduser -S -D -u 9000 -G sonarqube sonarqube \
 -----

In my docker hosts,
-----
groupadd -r -g 9000 sonarqube && useradd -u 9000 -r -g 9000 -s /sbin/nologin  sonarqube
mkdir -p /data/sonarqube/{data,extensions,logs.temp}
chown -R  sonarqube:sonarqube /data/sonarqube/
-----

modify docker compose.yml
---------------------
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/sonarqube/data:/opt/sonarqube/data
      - /data/sonarqube/extensions:/opt/sonarqube/extensions
      - /data/sonarqube/logs:/opt/sonarqube/logs
      - /data/sonarqube/temp:/opt/sonarqube/temp
-------------------------------------

**Comment by tobias-trabelsi-sonarsource** [comment]
hi @mayou33 

this is very common when working with docker as the /etc/passwd, /etc/shadow and /etc/group files are handling uid/gid name mapping and can have different content depending on the location of these files (container host, container, other server). you are always free to start sonarqube as another none root user, like this

```bash
docker run -d --name sonarqube -u 1002 -p 9000:9000 sonarqube:9.0-community
```

please note that you don't have to create a new user on the docker host if you want to use bind mounts. we recommend using named volumes in our documentation anyway but if you want to stick with bind mounts you can set the file permissions also to a specific uid/gid without the need of creating a new user:

```bash
chown -R 9000:9000 /data/sonarqube/

```

if you have additional questions or need help, feel free to start a thread in our [community forum](https://community.sonarsource.com/)
