### ISSUE TITLE
Unable to pull image on MacBook Air with M1 chip

### ISSUE THREAD

**Issue by ikmrgrv** [SonarSource/docker-sonarqube#460]
Please ensure your issue adheres to the following guidelines: 

This repository is used for technical issues only. For general Support like questions, please create a new Thread in our [Community Forum](https://community.sonarsource.com/)

- [ ] Please check the problem is not already reported, or a known issue documented in [`develop.md`](develop.md)
- [ ] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs

**Comment by malena-ebert-sonarsource** [comment]
Hello @ikmrgrv,

the M1 chip is an `arm` based one. Currently we are supporting the `amd64` architecture only.
If you have further questions, please go to our [Community Forum](https://community.sonarsource.com/).

**Comment by sud007** [comment]
But this is huge issue for the M1 owners :( what are the timelines for this resolution?

**Comment by yuvarajvindium** [comment]
Any plans to or progress on M1 chip support?

**Comment by metasmile** [comment]
so with arm64 images, can we use it with M1?
