### ISSUE TITLE
SonarQube v8.7.0 not published

### ISSUE THREAD

**Issue by stevehipwell** [SonarSource/docker-sonarqube#465]
The latest SonarQube v8.7.0 hasn't been published to Docker Hub yet, is there a problem or is this expected?

**Comment by malena-ebert-sonarsource** [comment]
Hi @stevehipwell,

the image is in the review phase of Docker Hub.
You can track the PR here: https://github.com/docker-library/official-images/pull/9631

**Comment by stevehipwell** [comment]
Thanks @malena-ebert-sonarsource, I'll follow that PR.
