### ISSUE TITLE
docker image sonarqube uid "1000" same with jenkins uid 

### ISSUE THREAD

**Issue by bparinas** [SonarSource/docker-sonarqube#472]
i encountered a uid conflict with sonarqube and jenkins docker image when i used the docker-compose.

sonarqube image layer:
addgroup -S **-g 1000** sonarqube;     adduser -S -D **-u 1000** -G sonarqube sonarqube; 

jenkins image layer (uid=1000,gid=1000):
ARG uid=1000
ARG gid=1000
addgroup -g ${gid} ${group}   && adduser -h "$JENKINS_HOME" -u ${uid} -G ${group} -s /bin/bash -D ${user}

sonarqube container used my jenkins local account uid 1000 for the mounted volume:
$ ls -l /data/sonar/
drwxr-xr-x 2 root    root    4096 Feb 27 07:05 sonarqube_bundled-plugins
drwxr-xr-x 2 root    root    4096 Feb 27 07:05 sonarqube_conf
drwx------ 4 **jenkins jenkins** 4096 Feb 27 09:10 sonarqube_data
drwx------ 3 **jenkins jenkins** 4096 Feb 27 09:10 sonarqube_extensions

appreciate any help. tnx

**Comment by tobias-trabelsi-sonarsource** [comment]
hi @bparinas ,

this is very common when working with docker as the `/etc/passwd`, `/etc/shadow` and `/etc/group` files are handling uid/gid name mapping and can have different content depending on the location of these files (container host, container, other server). you are always free to start sonarqube as another none root user, like this

```bash
docker run -d --name sonarqube -u 1002 -p 9000:9000 sonarqube:9.0-community
```

if you have additional questions or need help, feel free to start a thread in our [community forum](https://community.sonarsource.com/)
