### ISSUE TITLE
Support for arm64v8 architectures (eg Apple M1)

### ISSUE THREAD

**Issue by akafred** [SonarSource/docker-sonarqube#475]
Pulling the image on MacBook Pro with an Apple M1 processor fails with the following message: 

> no matching manifest for linux/arm64/v8 in the manifest list entries

I would love it if you consider cross-building the image for arm64v8.

**Comment by malena-ebert-sonarsource** [comment]
Hi @akafred,

currently we only support amd64.
Please create a feature request in the [Community Forum](https://community.sonarsource.com/).

**Comment by akafred** [comment]
Ok, I'll look for some other tool to use ...

**Comment by mwz** [comment]
Hi @akafred, I've adapted the 8.7.1 community image for arm64 for local development purposes. It seems to work fine for me, but I've not tested it extensively. Feel free to use it if it helps you.

You can find it here:
 - DockerHub - https://hub.docker.com/repository/docker/mwizner/sonarqube
 - GitHub - https://github.com/sonar-scala/docker-sonarqube/blob/arm64/8/community/arm64.Dockerfile

**Comment by vogler** [comment]
The official [Dockerfile](https://github.com/SonarSource/docker-sonarqube/tree/eac4db682da9c06fb183fead6d77606b2994a10c/9/community) now builds fine on Apple M1.

However, I need to restart the container twice for SonarQube to start - before it either hangs on `Waiting for Elasticsearch` or `Launch process[WEB_SERVER]`. On Windows I don't have this problem (built the same image). I don't see how that should have to do with the architecture though. Can someone reproduce this with Intel macOS?

**Comment by michaelsauter** [comment]
@vogler Yes, I see the same behaviour, except that restarting the container twice does not reliably fix the issue :/
