### ISSUE TITLE
Docker-Compose Example is wrong

### ISSUE THREAD

**Issue by 123dev** [SonarSource/docker-sonarqube#476]
The docker-compose example provided here
https://docs.sonarqube.org/latest/setup/install-server/#
Does not work
![image](https://user-images.githubusercontent.com/13109154/113011536-e2e07b00-9147-11eb-99d6-01ba6f045f60.png)

The correct environment format is using the equal `=` sign
example:
`- SONAR_JDBC_USERNAME=sonar`

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @123dev ,

no this is valid yaml syntax that is supported by the [compose spec](https://github.com/compose-spec/compose-spec). the `=` notation is only valid for `.env` files, but not for env declarations in compose itself. see the [docker documentation](https://docs.docker.com/compose/environment-variables/) for more information
