### ISSUE TITLE
Using OpenJDK from Alpine repository

### ISSUE THREAD

**Issue by winterheart** [SonarSource/docker-sonarqube#478]
Hello.

I have struggled with selfsigned ssl certificates on Sonarqube 8, and found that new docker images uses OpenJDK tarballs instead of just `apk add openjdk11` command. So now I forced to customize original image to run additional commands to properly deploy SSL certificates instead of just adding them as files via -v option.

Is there a some reason to install custom openjdk tarball instead installing system package provided by Alpine? As I can see, Alpine has recent OpenJDK 11.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @winterheart 

sorry for the delay. the reason for this is that we want to use a java implementation that was linked against glibc while still using alpine for the rest. the openjdk11 package from alpine is linked against musllibc.
as for your problem regarding certificates; why can you not just mount a custom trust store with -v ? nothing should stop you from doing this, you just have to pay attention to the target

```
docker run -d -p 9000:9000 --name sonarqube-test -v /path/to/keystore:/opt/java/openjdk/lib/security/cacerts:ro sonarqube:8.8-community
```

**Comment by winterheart** [comment]
Hi @tobias-trabelsi-sonarsource 

Well, that may be as workaround, since I relies on pre-generated cacerts on host side... I think that would be great to add hooks to regenerate cacerts on each start given on mapped source CA certs like -v /path/to/CA.crt:/usr/local/share/ca-certificates/CA.crt and run `update-ca-certificates` equivalent of AdoptOpenJDK.

**Comment by tobias-trabelsi-sonarsource** [comment]
how often do you need to do this kind of operation in a containerized environment? 
usually you should only need to do this once when working with a private PKI or a self signed certificate somewhere. i have the feeling that a alteration to the filesystem of the container deserves a new images alone in order to version this correctly if this is a regular operation in your organisation.

`update-ca-certificates` comes from a different package btw. it is just a dependency of `openjdk11`.

**Comment by winterheart** [comment]
Well, I do this each time when update sonarqube container version. In first place I was asked about system openjdk11 meaning that with it comes `java-cacerts` package which allows to update OpenJDK CA store by just issuing `update-ca-certificates`, so after binding PEM certs `update-ca-certificates` on start would update CA stores evrywhere without workarounds.

**Comment by tobias-trabelsi-sonarsource** [comment]
sorry for being a bit pushy here but i don't think that introducing a quality of live tool would justify this specially if you would still need to mount your certificates into the container none the less. 

one thing that you could do if you really want to benefit from the docker hosts trust store is use the java trust store of the docker host and mount this one into the container. you can trigger the regeneration of the java key store from the host and the mount point should not change afterwards. you would need to restart sonarqube anyway whenever you want to take the changes from a keystore into consideration.

if you want to discuss this further i would like to welcome you to our [community forum](https://community.sonarsource.com/) to better track the conversation
