### ISSUE TITLE
SonarQube Docker image full version tags aren't present for 8.8.0

### ISSUE THREAD

**Issue by stevehipwell** [SonarSource/docker-sonarqube#479]
There isn't a full version tag for `8.8.0` available at [Docker Hub](https://hub.docker.com/_/sonarqube?tab=tags&page=1&ordering=last_updated&name=8.8.0); just the `8.8` tags.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @stevehipwell 
thanks for the report. the missing tag is now available as well :)

**Comment by stevehipwell** [comment]
Thanks @tobias-trabelsi-sonarsource
