### ISSUE TITLE
"bin/run.sh": permission denied

### ISSUE THREAD

**Issue by maxr-sg** [SonarSource/docker-sonarqube#486]
Please ensure your issue adheres to the following guidelines: 

This repository is used for technical issues only. For general Support like questions, please create a new Thread in our [Community Forum](https://community.sonarsource.com/)

- [x] Please check the problem is not already reported, or a known issue documented in [`develop.md`](develop.md)
- [x] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs

Deploying SonarQube Enterprise on ECS Fargate. I am using the dockerfile, run.sh, and sonar.sh provided on this github repository. During the deployment I get this error code `"bin/run.sh": permission denied` any ideas? I did my research before posting the issue.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @maxr-sg 
you are most probably missing a `chmod +x` somewhere in your Dockerfile. the bash scripts in this git repository already have the executable flag, but when you just copy paste the content of these files, you are not including these filepermission flags.

you should get rid of your error with adjusting the provided Dockerfile like this 

```
...
COPY --chown=sonarqube:sonarqube run.sh sonar.sh ${SONARQUBE_HOME}/bin/
RUN chmod +x ${SONARQUBE_HOME}/bin/*.sh
WORKDIR ${SONARQUBE_HOME}
EXPOSE 9000
ENTRYPOINT ["bin/run.sh"]
CMD ["bin/sonar.sh"]
```

feel free to re open this issue if you still encounter this problem. if you need additional help, please create a topic in our community forum so more people can have a look
