### ISSUE TITLE
Sonarqube is not showing Msbuild analysis 

### ISSUE THREAD

**Issue by samkhamk** [SonarSource/docker-sonarqube#488]
Hello Team,

we are having sonarqube 7.9.3 community edition & sonar scanner for msbuild .net 5.2.1, our jenkins is has linux agent

our Jenkins build gets successful but we are not seeing any results on sonarqube dashboard ,

sonarqube logs :----------
2021.06.08 14:29:50 INFO ce[AXnrmZmrViTuBNQnmTsV][o.s.c.t.CeWorkerImpl] Executed task | project=project:vek-orabr | type=REPORT | id=AXnrmZmrViTuBNQnmTsV | submitter=s2-service-account | status=SUCCESS | time=6230ms

jenkins job :-----------
$dotnet_home begin /key:“project:vek-orabr” /d:sonar.login=“e0602b05c77f7616e6de” /d:sonar.host.url=https://example.com/sonarqube /d:sonar.verbose=true /d:sonar.cs.opencover.reportsPaths=“test/*/coverage.opencover.xml”

$dotnet_home build VEK.Orchestrator.sln
DOTNET_CLI_TELEMETRY_OPTOUT=1
dotnet --info
dotnet publish
cd VEK.Orabrr.Api/bin/Debug/net5.0/publish/
echo git rev-parse --short HEAD >> version.txt
zip -r …/…/…/…/…/VEK-Orabr.zip *

$dotnet_home end
what we need to check to get result on sonarqube dashboard, since jenkins builds are getting completed but no analysis on SQ dashboard, please guide us,

Regards,
Sam

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @samkhamk ,

this seems unrelated to our docker images. please open a thread at our [community forum](https://community.sonarsource.com/), so more people can have a look at your problem
