### ISSUE TITLE
SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true has no effect with Azure ARM Template environment

### ISSUE THREAD

**Issue by samsonfr** [SonarSource/docker-sonarqube#489]
I tried to add this to my ARM template (attached) :
 
{
  "name": "SONAR_ES_BOOTSTRAP_CHECKS_DISABLE",
  "value": "true"
}        

It deploys successfully and I see the variable in container properties (Azure Container Instance).

But it seems to be completely ignored by SonarQube when starting :
 
2021.06.03 12:12:37 INFO  es[][o.e.t.TransportService] publish_address {127.0.0.1:45289}, bound_addresses {127.0.0.1:45289}
2021.06.03 12:12:38 INFO  es[][o.e.b.BootstrapChecks] explicitly enforcing bootstrap checks
ERROR: [1] bootstrap checks failed. You must address the points described in the following [1] lines before starting Elasticsearch.
bootstrap check failure [1] of [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
ERROR: Elasticsearch did not exit normally - check the logs at /opt/sonarqube/logs/sonarqube.log
2021.06.03 12:12:38 INFO  es[][o.e.n.Node] stopping ...
2021.06.03 12:12:38 INFO  es[][o.e.n.Node] stopped
2021.06.03 12:12:38 INFO  es[][o.e.n.Node] closing ...
2021.06.03 12:12:39 INFO  es[][o.e.n.Node] closed
2021.06.03 12:12:39 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 78
2021.06.03 12:12:39 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
2021.06.03 12:12:39 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
 
I had to modify the official Docker image file in order to make it work as described here:
https://github.com/ShubhamGargCTH/SonarQubeAzureAppService/

That would be so great to be able to use official images with Azure Container Instance!

Frederick

[dockeraciofficial.json.txt](https://github.com/SonarSource/docker-sonarqube/files/6625672/dockeraciofficial.json.txt)

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @samsonfr ,

it seems like you are struck with a known bug that is tracked via [SONAR-13997](https://jira.sonarsource.com/browse/SONAR-13997).

you can work around this with defining `-Dsonar.es.bootstrap.checks.disable=true` as a command argument

**Comment by tobias-trabelsi-sonarsource** [comment]
if you need additional help, feel free to open a thread at our [community forum](https://community.sonarsource.com/)
