### ISSUE TITLE
The web application start problem

### ISSUE THREAD

**Issue by sysboss** [SonarSource/docker-sonarqube#49]
My SonarQube container failing to start. Using :latest image with very basic settings.
```
....
 "image": "sonarqube:latest",
...
"portMappings": [
        {
          "hostPort": 9000,
          "containerPort": 9000,
          "protocol": "tcp"
        }],
...
 "environment": [
        {
          "name": "SONARQUBE_JDBC_PASSWORD",
          "value": "passsssword_here"
        },
        {
          "name": "SONARQUBE_JDBC_URL",
          "value": "jdbc:mysql://my_instance.rds.amazonaws.com:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true"
        },
        {
          "name": "SONARQUBE_JDBC_USERNAME",
          "value": "sonar"
        }
      ],
```

It worked well as I run it first time a month ago. After restarting the container I get:

2016.10.05 08:19:33 WARN  web[o.a.c.l.WebappClassLoaderBase] The web application [ROOT] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)

No other ERROR or WARN messages... Database is accessible manually using same credentials. Full logs is attached [log.txt](https://github.com/SonarSource/docker-sonarqube/files/510483/log.txt)
Please advice.

**Comment by Godin** [comment]
@sysboss as I see from the provided log:
```
2016.10.05 08:19:12 INFO  app[o.s.p.m.Monitor] Process[web] is stopping
...
2016.10.05 08:19:34 INFO  app[o.s.p.m.Monitor] Process[web] is up
```
i.e. stop of application is requested from the outside of the application even before full start. So the main question here - how do you (re)start container? Problem lies somewhere there.

> with very basic settings

Settings for what? There are soo many tools to manage Docker containers...

**Comment by sysboss** [comment]
I manage containers in AWS EC2. You were right that stop request is coming from the outside.
It was triggered by ELB (load balancer) which was misconfigured.

I discovered that SonarQube container migrated to other host in other availability zone for which LoadBalancer is not configured to route traffic to.
Adding the right availability zones fixed the issue.

Thanks for your quick response.

**Comment by Godin** [comment]
@sysboss you're welcome.
