### ISSUE TITLE
When mysql container is up, sonarqube container will down.

### ISSUE THREAD

**Issue by oknixus** [SonarSource/docker-sonarqube#491]
If sonarqube startup without mysql container running, it works.
But when mysql is up and running, sonarqube will down.
Why not both containers sonarqube and mysql together?
This is the logs:
```
2021.06.11 10:11:04 INFO  ce[][o.s.c.c.CePluginRepository] Load plugins
2021.06.11 10:11:05 INFO  ce[][o.s.c.c.ComputeEngineContainerImpl] Running Community edition
2021.06.11 10:11:06 INFO  ce[][o.s.ce.app.CeServer] Compute Engine is operational
2021.06.11 10:11:06 INFO  app[][o.s.a.SchedulerImpl] Process[ce] is up
2021.06.11 10:11:06 INFO  app[][o.s.a.SchedulerImpl] SonarQube is up
2021.06.11 10:56:31 INFO  es[][o.e.m.j.JvmGcMonitorService] [gc][2758] overhead, spent [333ms] collecting in the last [1s]
2021.06.11 11:30:49 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 137
2021.06.11 11:30:49 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
2021.06.11 11:30:49 INFO  ce[][o.s.p.ProcessEntryPoint] Hard stopping process
2021.06.11 11:30:49 INFO  ce[][o.s.ce.app.CeServer] Compute Engine is stopping...
2021.06.11 11:30:49 INFO  ce[][o.s.c.t.CeProcessingSchedulerImpl] Hard stopping workers...
2021.06.11 11:30:49 WARN  ce[][o.s.c.c.CeCleaningExecutorServiceImpl] Termination of pool CeCleaningExecutorServiceImpl failed
java.lang.InterruptedException: null
    at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor.awaitTermination(Unknown Source)
    at java.base/java.util.concurrent.Executors$DelegatedExecutorService.awaitTermination(Unknown Source)
    at org.sonar.server.util.AbstractStoppableExecutorService.stop(AbstractStoppableExecutorService.java:52)
    at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.stop(StartableCloseableSafeLifecyleStrategy.java:50)
    at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.stop(AbstractInjectionFactory.java:88)
    at org.picocontainer.behaviors.AbstractBehavior.stop(AbstractBehavior.java:179)
    at org.picocontainer.behaviors.Stored$RealComponentLifecycle.stop(Stored.java:141)
    at org.picocontainer.behaviors.Stored.stop(Stored.java:118)
    at org.picocontainer.DefaultPicoContainer.stopAdapters(DefaultPicoContainer.java:1048)
    at org.picocontainer.DefaultPicoContainer.stop(DefaultPicoContainer.java:803)
    at org.sonar.core.platform.ComponentContainer.stopComponents(ComponentContainer.java:166)
    at java.base/java.lang.Iterable.forEach(Unknown Source)
    at org.sonar.core.platform.ComponentContainer.stopChildren(ComponentContainer.java:181)
    at org.sonar.core.platform.ComponentContainer.stopComponents(ComponentContainer.java:164)
    at java.base/java.lang.Iterable.forEach(Unknown Source)
    at org.sonar.core.platform.ComponentContainer.stopChildren(ComponentContainer.java:181)
    at org.sonar.core.platform.ComponentContainer.stopComponents(ComponentContainer.java:164)
    at java.base/java.lang.Iterable.forEach(Unknown Source)
    at org.sonar.core.platform.ComponentContainer.stopChildren(ComponentContainer.java:181)
    at org.sonar.core.platform.ComponentContainer.stopComponents(ComponentContainer.java:164)
    at org.sonar.ce.container.ComputeEngineContainerImpl.stop(ComputeEngineContainerImpl.java:267)
    at org.sonar.ce.ComputeEngineImpl.shutdown(ComputeEngineImpl.java:72)
    at org.sonar.ce.app.CeServer$CeMainThread.attemptShutdown(CeServer.java:184)
    at org.sonar.ce.app.CeServer$CeMainThread.run(CeServer.java:152)
2021.06.11 11:30:49 INFO  ce[][o.s.ce.app.CeServer] Compute Engine is stopped
2021.06.11 11:30:49 INFO  app[][o.s.a.SchedulerImpl] Process[ce] is stopped
2021.06.11 11:30:50 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process
2021.06.11 11:30:50 INFO  web[][o.s.s.n.NotificationDaemon] Notification service stopped
2021.06.11 11:30:50 INFO  web[][o.s.s.p.d.EmbeddedDatabase] Embedded database stopped
2021.06.11 11:30:50 INFO  app[][o.s.a.SchedulerImpl] Process[web] is stopped
2021.06.11 11:30:50 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
```

**Comment by oknixus** [comment]
> If sonarqube startup without mysql container running, it works.
> But when mysql is up and running, sonarqube will down.
> Why not both containers sonarqube and mysql together?
> This is the logs:
> 
> ```
> 2021.06.11 10:11:04 INFO  ce[][o.s.c.c.CePluginRepository] Load plugins
> 2021.06.11 10:11:05 INFO  ce[][o.s.c.c.ComputeEngineContainerImpl] Running Community edition
> 2021.06.11 10:11:06 INFO  ce[][o.s.ce.app.CeServer] Compute Engine is operational
> 2021.06.11 10:11:06 INFO  app[][o.s.a.SchedulerImpl] Process[ce] is up
> 2021.06.11 10:11:06 INFO  app[][o.s.a.SchedulerImpl] SonarQube is up
> 2021.06.11 10:56:31 INFO  es[][o.e.m.j.JvmGcMonitorService] [gc][2758] overhead, spent [333ms] collecting in the last [1s]
> 2021.06.11 11:30:49 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 137
> 2021.06.11 11:30:49 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
> 2021.06.11 11:30:49 INFO  ce[][o.s.p.ProcessEntryPoint] Hard stopping process
> 2021.06.11 11:30:49 INFO  ce[][o.s.ce.app.CeServer] Compute Engine is stopping...
> 2021.06.11 11:30:49 INFO  ce[][o.s.c.t.CeProcessingSchedulerImpl] Hard stopping workers...
> 2021.06.11 11:30:49 WARN  ce[][o.s.c.c.CeCleaningExecutorServiceImpl] Termination of pool CeCleaningExecutorServiceImpl failed
> java.lang.InterruptedException: null
>     at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
>     at java.base/java.util.concurrent.ThreadPoolExecutor.awaitTermination(Unknown Source)
>     at java.base/java.util.concurrent.Executors$DelegatedExecutorService.awaitTermination(Unknown Source)
>     at org.sonar.server.util.AbstractStoppableExecutorService.stop(AbstractStoppableExecutorService.java:52)
>     at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.stop(StartableCloseableSafeLifecyleStrategy.java:50)
>     at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.stop(AbstractInjectionFactory.java:88)
>     at org.picocontainer.behaviors.AbstractBehavior.stop(AbstractBehavior.java:179)
>     at org.picocontainer.behaviors.Stored$RealComponentLifecycle.stop(Stored.java:141)
>     at org.picocontainer.behaviors.Stored.stop(Stored.java:118)
>     at org.picocontainer.DefaultPicoContainer.stopAdapters(DefaultPicoContainer.java:1048)
>     at org.picocontainer.DefaultPicoContainer.stop(DefaultPicoContainer.java:803)
>     at org.sonar.core.platform.ComponentContainer.stopComponents(ComponentContainer.java:166)
>     at java.base/java.lang.Iterable.forEach(Unknown Source)
>     at org.sonar.core.platform.ComponentContainer.stopChildren(ComponentContainer.java:181)
>     at org.sonar.core.platform.ComponentContainer.stopComponents(ComponentContainer.java:164)
>     at java.base/java.lang.Iterable.forEach(Unknown Source)
>     at org.sonar.core.platform.ComponentContainer.stopChildren(ComponentContainer.java:181)
>     at org.sonar.core.platform.ComponentContainer.stopComponents(ComponentContainer.java:164)
>     at java.base/java.lang.Iterable.forEach(Unknown Source)
>     at org.sonar.core.platform.ComponentContainer.stopChildren(ComponentContainer.java:181)
>     at org.sonar.core.platform.ComponentContainer.stopComponents(ComponentContainer.java:164)
>     at org.sonar.ce.container.ComputeEngineContainerImpl.stop(ComputeEngineContainerImpl.java:267)
>     at org.sonar.ce.ComputeEngineImpl.shutdown(ComputeEngineImpl.java:72)
>     at org.sonar.ce.app.CeServer$CeMainThread.attemptShutdown(CeServer.java:184)
>     at org.sonar.ce.app.CeServer$CeMainThread.run(CeServer.java:152)
> 2021.06.11 11:30:49 INFO  ce[][o.s.ce.app.CeServer] Compute Engine is stopped
> 2021.06.11 11:30:49 INFO  app[][o.s.a.SchedulerImpl] Process[ce] is stopped
> 2021.06.11 11:30:50 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process
> 2021.06.11 11:30:50 INFO  web[][o.s.s.n.NotificationDaemon] Notification service stopped
> 2021.06.11 11:30:50 INFO  web[][o.s.s.p.d.EmbeddedDatabase] Embedded database stopped
> 2021.06.11 11:30:50 INFO  app[][o.s.a.SchedulerImpl] Process[web] is stopped
> 2021.06.11 11:30:50 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
> ```

[The complete logs](https://gist.github.com/oknixus/dfe82b406f6f090269710f92ba08ca93)

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @oknixus ,

mysql is no longer supported since SQ 7.9. please migrate to postgresql/mssql or oracle db as stated in our [requirements](https://docs.sonarqube.org/latest/requirements/requirements/)

**Comment by oknixus** [comment]
> Hi @oknixus ,
> 
> mysql is no longer supported since SQ 7.9. please migrate to postgresql/mssql or oracle db as stated in our [requirements](https://docs.sonarqube.org/latest/requirements/requirements/)

I do not need mysql, and the sq does not connect to mysql. 
Just running mysql, the sonarqube container will being stop.

**Comment by nixel2007** [comment]
> 2021.06.11 11:30:49 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 137

Check your es logs.

**Comment by oknixus** [comment]
Thanks. It has been solved.
The problem was caused by the memory limit in docker preferences;
