### ISSUE TITLE
How to add jdbc sonar.properties to a running container manually and restart

### ISSUE THREAD

**Issue by girish20021993** [SonarSource/docker-sonarqube#496]
Is there any way I add my sonar.properties file from the dockerfile externally in which I have added jdbc postgres db creds.
The way I am implementing is directly creating the container in server from AWS through jenkins shell script ?

Or

Can you help me how to update the sonar.properties from the running container and restart it?

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi again @girish20021993 ,

for docker we usually recommend using [environment variables](https://docs.sonarqube.org/latest/setup/environment-variables/). if you need to stick to a `sonar.properties` file, you probably want to mount the file in your container during startup, like 

```bash
docker run -d -p 9000:9000 -v /path/to/your/sonar.properties:/opt/sonarqube/conf/sonar.properties:ro sonarqube
```

maybe [this part of our docs](https://docs.sonarqube.org/latest/setup/install-server/#header-4) will help you to get started. 
Also as this is more general support and not a technical issue with the docker images of sonarqube, please create a thread in the [community forum](https://community.sonarsource.com/) :smiley:
