### ISSUE TITLE
I am updating 9.0.0.45539 community dockerfile but not able to run the sonarcube.

### ISSUE THREAD

**Issue by girish20021993** [SonarSource/docker-sonarqube#500]
I am trying to edit the docker file : https://github.com/SonarSource/docker-sonarqube/blob/master/9/community/Dockerfile

In line #120: curl --fail --location --output sonarqube.zip --silent --show-error "${SONARQUBE_ZIP_URL}"; \
Changing to : curl --fail --location --output sonarqube.zip --silent --show-error "https://bitbucket.org/bmdevelopers/sonarqube-alpha/raw/b523baa46644e7e0f62e41f01966eec5f330b8ef/sonarqube-9.0.0.45539.zip"; \

Reason to add this is I have updated sonar.properties in my app and dumped that to bitbucket public repo.
Hence I want to run this but below I can see the errors like:
"[0m[91mgpg: BAD signature from "SonarSource S.A. <infra@sonarsource.com>" [unknown]"
and other steps from the dockerfile are skipped.

**Comment by tobias-trabelsi-sonarsource** [comment]
well yeah if the zip is not signed by sonarsource the verification failes. if you want to build your own docker image you need to remove the signature check as well.

regarding your intention: there is no need to modify the Dockerfile if you just want to configure sonarqube. we support configuration via [environment variables](https://docs.sonarqube.org/latest/setup/environment-variables/) or, if you want to stick to a configuration via `sonar.properties` you can mount this file from the docker host into the container with `docker run -d -v /path/to/your/sonar.properties:/opt/sonarqube/conf/sonar.properties:ro -p 9000:9000 sonarqube:9-community`. if you only want to extend the image you can also inherent from our images in your own Dockerfile like this:

```Dockerfile
FROM sonarqube:9-community

COPY --chown=sonarqube:sonarqube sonar.properties /opt/sonarqube/conf/sonar.properties
...
```

hope that helps and if you have any further questions, feel free to create a post in our [community forum](https://community.sonarsource.com/) :)

**Comment by girish20021993** [comment]
Thanks for that @tobias-trabelsi-sonarsource 
Is there any link that how to configure via environment variables apart from https://docs.sonarqube.org/latest/setup/environment-variables/
