### ISSUE TITLE
How to setup environment variables in configuration

### ISSUE THREAD

**Issue by girish20021993** [SonarSource/docker-sonarqube#501]
This is in reply I am updating 9.0.0.45539 community dockerfile but am not able to run the sonarcube. #500 

I want to set environment variables through configuration.
Can someone help how to setup environment variables through this: https://docs.sonarqube.org/latest/setup/environment-variables/

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @girish20021993 ,

what you are looking for is basic docker usage i guess.

```bash
docker run -d --name sonarqube \
    -p 9000:9000 \
    -e SONAR_JDBC_URL=... \
    -e SONAR_JDBC_USERNAME=... \
    -e SONAR_JDBC_PASSWORD=... \
    sonarqube:9 
```

again i encourage you to check out our [documentation](https://docs.sonarqube.org/latest/setup/install-server/#header-4) and ask for general help in our [community forum](https://community.sonarsource.com/) as the issue tracker here is really just for technical issues with the docker images

**Comment by girish20021993** [comment]
I want to add those to a container which is already up and using port #9000.   
So when I try this it says port 9000 already in use.

**Comment by tobias-trabelsi-sonarsource** [comment]
i don't think this is supported by docker. runtime and persistence should be separated so there should be no need to "edit" a running docker container.
This was requested and discussed over by the docker folks [here](https://github.com/moby/moby/issues/8838) and [here](https://github.com/moby/moby/issues/7561). you will need to stop your running container and create a new one or hack yourself around this (there are hints in the threads i linked).

anyway this has nothing to do with sonarqube :sweat_smile:

**Comment by girish20021993** [comment]
Thanks for that conclusion.
Last one:
Can I pass the environment variables while building my image.
docker build --build-arg some_variable_name=a_value

and run this.
Will this work?

**Comment by tobias-trabelsi-sonarsource** [comment]
Nope `--build-arg` parameters are only available at build time and not at runtime
