### ISSUE TITLE
SonarQube Setup for iOS on Windows

### ISSUE THREAD

**Issue by ajayreddy07** [SonarSource/docker-sonarqube#510]
I have been Working on setup Sonarqube for iOS and getting zero bugs,vulnerabilities in my local machine. Is there any possibility that I can setup sonarqube for iOS on windows?
Please help with this!!

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @ajayreddy07 ,

please create a new thread in our [community forum](https://community.sonarsource.com/). This question is not related to the sonarqube docker images
