### ISSUE TITLE
Cannot start sonarqube after placing the Chinese package in version 9.2, and the web page is always loading

### ISSUE THREAD

**Issue by zhang-devil** [SonarSource/docker-sonarqube#518]
Place sonar-l10n-zh-plugin-9.2.jar in sonarqube
Execute StartSonar.bat
Open the browser and enter localhost:9000
The page is always loading, unable to enter the system

**Comment by nixel2007** [comment]
Confirm problem with ru 9.0 plugin.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @nixel2007 and @zhang-devil ,

this problem is not related to our docker images. please open a new thread in our community forum and describe the issue with as much information as possible to give us a chance to reproduce this
