### ISSUE TITLE
Sonarqube swam configuration

### ISSUE THREAD

**Issue by maurucao** [SonarSource/docker-sonarqube#52]
Hi all,

I am trying to create a sonarqube server in a docker swarm cluster to have a more automated availability.

According to documentation to have a sonarqube server in a cluster(http://docs.sonarqube.org/display/SONAR/How+To+Implement+an+Active-Passive+Cluster) I should sync some directories before start the backup instance, considering the database has it own cluster solution and balance.

To do this I must be able to expose the data in the $SONAR_HOME/conf, $SONAR_HOME/extensions and $SONAR_HOME/data to any new container in case of failure of the current container. I was planning to use NFS to sonarqube folders and I am not considering here the avaliability of NFS server. Below is an example of the service create command thinking that we will only have 1 container running at any:

192.168.1.1 is a postgresql server
192.168.1.2 is a NFS server

docker service create --name sonarqube \
    -p 9000:9000 -p 9092:9092 \
    -e SONARQUBE_JDBC_USERNAME=sonar \
    -e SONARQUBE_JDBC_PASSWORD=sonar \
    -e SONARQUBE_JDBC_URL=jdbc:postgresql://192.168.1.1/sonar \
    --mount type=volume,volume-opt=type=nfs,volume-opt=o=addr=192.168.1.2,ro=false,volume-opt=device=:/var/nfs/sonarqube/extensions,source=sonarplugins,target=/opt/sonarqube/extensions \
    --mount type=volume,volume-opt=type=nfs,volume-opt=o=addr=192.168.1.2,ro=false,volume-opt=device=:/var/nfs/sonarqube/conf,source=sonarplugins,target=/opt/sonarqube/conf \
    --mount type=volume,volume-opt=type=nfs,volume-opt=o=addr=192.168.1.2,ro=false,volume-opt=device=:/var/nfs/sonarqube/data,source=sonarplugins,target=/opt/sonarqube/data \
    --replicas 1 sonarqube:alpine

Do you think this is a good solution?

**Comment by hgomez-sonarsource** [comment]
documentation your mention, is about active/passive cluster whereas swarm is more about active/active.
As of today (SQ 6.1), there is no 'automatic' way to have active/active cluster
