### ISSUE TITLE
Update to the latest more secure jdk 

### ISSUE THREAD

**Issue by stoyankanev** [SonarSource/docker-sonarqube#528]
Please ensure your issue adheres to the following guidelines: 

This repository is used for technical issues only. For general Support like questions, please create a new Thread in our [Community Forum](https://community.sonarsource.com/)

- [x] Please check the problem is not already reported, or a known issue documented in [`develop.md`](develop.md)
- [x] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs

Could you please update the used jdk [AdoptOpenJDK-11.0.11+9](https://github.com/SonarSource/docker-sonarqube/blob/master/8/community/Dockerfile#L54) to the latest [AdoptOpenJDK-11.0.13+8 ](https://adoptium.net/?variant=openjdk11) or newer major version that contains needed security fixes?
Best Regards, Stoyan

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @stoyankanev ,

i guess you are referring to the LTS version of sonarqube? in the latest version we already replaced adoptopenjdk with the alpine maintained version of openjdk (see #502 ).

**Comment by stoyankanev** [comment]
Hi @tobias-trabelsi-sonarsource,
Yes, I am referring to the LTS version 8.9.x.
