### ISSUE TITLE
8.9.6 Community Edition Docker Image Contains World Writable Files

### ISSUE THREAD

**Issue by shinn16** [SonarSource/docker-sonarqube#534]
During a recent security audit, the following files were identified as having world-writable file permissions for my team's SonarQube instance:

-  /opt/sonarqube/data/README.txt; 
-  /opt/sonarqube/extensions/jdbc-driver/oracle/README.txt; 
-  /opt/sonarqube/extensions/plugins/README.txt; 
-  /opt/sonarqube/logs/README.txt; 
-  /opt/sonarqube/temp/README.txt;
-  /opt/sonarqube/web/images/saml.png; 
-  /opt/sonarqube/web/js/164.m.c7e2da10.chunk.js.map;
-  /opt/sonarqube/web/js/239.1640013891161.chunk.js; 
-  /opt/sonarqube/web/js/74.1640013891161.chunk.js.map;

The current permissions from the sonarqube:8.9.6-community image for the aforementioned files are:
```shell
====================================
/opt/sonarqube/data/README.txt
-rwxrwxrwx 1 vagrant vagrant 115 Dec 20 15:12 /var/lib/docker/overlay2/9baf413618d7ba7764c08529482dd5b247a47cb36d79315ae245b628400696ed/diff/opt/sonarqube/data/README.txt
====================================
====================================
/opt/sonarqube/extensions/jdbc-driver/oracle/README.txt
-rwxrwxrwx 1 vagrant vagrant 249 Dec 20 15:12 /var/lib/docker/overlay2/9baf413618d7ba7764c08529482dd5b247a47cb36d79315ae245b628400696ed/diff/opt/sonarqube/extensions/jdbc-driver/oracle/README.txt
====================================
====================================
/opt/sonarqube/extensions/plugins/README.txt
-rwxrwxrwx 1 vagrant vagrant 737 Dec 20 15:12 /var/lib/docker/overlay2/9baf413618d7ba7764c08529482dd5b247a47cb36d79315ae245b628400696ed/diff/opt/sonarqube/extensions/plugins/README.txt
====================================
====================================
/opt/sonarqube/logs/README.txt
-rwxrwxrwx 1 vagrant vagrant 88 Dec 20 15:12 /var/lib/docker/overlay2/9baf413618d7ba7764c08529482dd5b247a47cb36d79315ae245b628400696ed/diff/opt/sonarqube/logs/README.txt
====================================
====================================
/opt/sonarqube/temp/README.txt
-rwxrwxrwx 1 vagrant vagrant 93 Dec 20 15:12 /var/lib/docker/overlay2/9baf413618d7ba7764c08529482dd5b247a47cb36d79315ae245b628400696ed/diff/opt/sonarqube/temp/README.txt
====================================
====================================
/opt/sonarqube/web/images/saml.png
-rw-rw-rw- 1 vagrant vagrant 15683 Dec 20 15:31 /var/lib/docker/overlay2/9baf413618d7ba7764c08529482dd5b247a47cb36d79315ae245b628400696ed/diff/opt/sonarqube/web/images/saml.png
====================================
====================================
/opt/sonarqube/web/js/164.m.c7e2da10.chunk.js.map
-rw-rw-rw- 1 vagrant vagrant 6499 Dec 20 15:31 /var/lib/docker/overlay2/9baf413618d7ba7764c08529482dd5b247a47cb36d79315ae245b628400696ed/diff/opt/sonarqube/web/js/164.m.c7e2da10.chunk.js.map
====================================
====================================
/opt/sonarqube/web/js/239.1640013891161.chunk.js
-rw-rw-rw- 1 vagrant vagrant 1822 Dec 20 15:31 /var/lib/docker/overlay2/9baf413618d7ba7764c08529482dd5b247a47cb36d79315ae245b628400696ed/diff/opt/sonarqube/web/js/239.1640013891161.chunk.js
====================================
====================================
/opt/sonarqube/web/js/74.1640013891161.chunk.js.map
-rw-rw-rw- 1 vagrant vagrant 3589 Dec 20 15:31 /var/lib/docker/overlay2/9baf413618d7ba7764c08529482dd5b247a47cb36d79315ae245b628400696ed/diff/opt/sonarqube/web/js/74.1640013891161.chunk.js.map
====================================
```

In order to comply with our security standards, I was required to modify the container image and remove the world-writable permissions to stay in alignment with the Principle of Least Privilege. The following permissions were applied:
|octal|file|
------|---------------------------------------------------|
|775|/opt/sonarqube/data/README.txt|
|775|/opt/sonarqube/extensions/jdbc-driver/oracle/README.txt|
|775|/opt/sonarqube/extensions/plugins/README.txt|
|775|/opt/sonarqube/logs/README.txt|
|775|/opt/sonarqube/temp/README.txt|
|664|/opt/sonarqube/web/images/saml.png|
|664|/opt/sonarqube/web/js/164.m.c7e2da10.chunk.js.map|
|664|/opt/sonarqube/web/js/239.1640013891161.chunk.js|
|664|/opt/sonarqube/web/js/74.1640013891161.chunk.js.map|

Granted, these files appear to present little security concern, however, leaving the current permissions as is does violate security best practices.

Please note that when applying the new permissions, they should be applied before the files are copied over to the docker image to prevent the permissions from still being present in one of the overlay filesystem layers

**Comment by tobias-trabelsi-sonarsource** [comment]
thanks for reporting this. can you share how you start this image? the 777 permissions should be removed from the [entrypoint script](https://github.com/SonarSource/docker-sonarqube/blob/master/8/community/run.sh#L24).

The 666 permissions are indeed not intended and i have created [SONAR-15986](https://jira.sonarsource.com/browse/SONAR-15986) to track this.

**Comment by tobias-trabelsi-sonarsource** [comment]
Which is intended behavior. SonarQube also starts as root and drops the permissions at runtime to ensure users can instantiate this image with arbitrary `-u` values. 
During instantiation of a OCI image a new top layer will be created anyway and all other layers are read only, so if you are looking for an argument to make an exception or adapt the rules of your scanning software; here it is :smile:
