### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by idreesVenD** [SonarSource/docker-sonarqube#546]
Is there a way to add CORS support in the docker image?

**Comment by mritd** [comment]
**First of all , it's easy to support multiple platforms.**

Docker image multi-platform support first depends on whether the base image supports it; then it depends on whether the application supports it.

1. Alpine 3.14.6 used by sonarqube9 already supports multiple platforms.
2. Sonarqube is written in java, and only depends on JVM at runtime.

So we can use docker's buildx plugin to build docker images with multi-platform support.

> For how to use buildx, please refer to the official docker documentation

```sh
~/g/d/9/community ❯❯❯ docker buildx build --platform linux/amd64,linux/arm64 -o type=image,push=true -t mritd/sonarqube .
```
<img width="1503" alt="image" src="https://user-images.githubusercontent.com/13043245/168846236-1c277adf-aabc-4310-8e64-5f22a9231233.png">

<img width="782" alt="image" src="https://user-images.githubusercontent.com/13043245/168846103-1ffadbda-6688-4184-a9b2-a685972e2232.png">

@Godin  Can the official support multiple platforms?

This way we don't need to build the docker image ourselves.

**Comment by jCOTINEAU** [comment]
hello @idreesVenD and @mritd, thanks a lot for taking the time to participate in the community.

Regarding multi-platform, it is an ongoing work as alpine and jvm does not work well together on arm64 ( multiple runtime issue due tu musl libc and glibc ). It should be released with the new upcoming LTS and SonarQube 9.9

For @idreesVenD question was it about CORS as cross origin resources ? 

If yes there is a community post [here](https://community.sonarsource.com/t/how-to-enable-cors-in-sonar-server/24481/5) explaning how to do so.

Please let me know if this answer the issue.

**Comment by mritd** [comment]
It may be a digression: Although using alpine for JVM applications can reduce the size of the docker image, it seems that the loss outweighs the gain due to muslc compatibility issues. Personally, I think the base image based on debian is better, such as eclipse-temurin.

**Comment by jCOTINEAU** [comment]
We do agree mritd, we made a huge test/discovery phase to find the best image, and we also agreed on eclipse-temurin for various reason.

Regarding the size, the increase is not that huge, 344 => 399 seems to be reasonable for the gain.
