### ISSUE TITLE
Critical CVE found in dependency 3.15:freetype:2.11.1-r2

### ISSUE THREAD

**Issue by DinaAbdelkhalek** [SonarSource/docker-sonarqube#575]
A critical vulnerability revealed on our SonarQube Docker image in one of the dependencies of alpine image 3.15 "3.15:freetype:2.11.1-r2". The freetype version used is 2.11.1-r2 and the vulnerability is mitigated in version 2.12.1, which is only compatible with alpine image 3.16, could you please update the base image to alpine 3.16 in the coming versions.

vulnerability description: 
FreeType contains an integer overflow condition in the cf2_interpT2CharString() function in psaux/psintrp.c that is triggered when handling subroutine '19' in PostScript fonts. This may allow a context-dependent attacker to cause an out-of-bounds write, resulting in a denial of service or potentially allowing the execution of arbitrary code.

The CVE details can be found [here](http://git.savannah.gnu.org/cgit/freetype/freetype2.git/commit/?id=034e5dbf92ea3a7ea7c9322e47a3a50ff23f7b55)

freetype compatibly versions:
https://repology.org/project/freetype/versions

**Comment by carminevassallo** [comment]
Dear @DinaAbdelkhalek,

thanks for raising this issue. We typically evaluate bug reports that are submitted through our [community forum](https://community.sonarsource.com/) and we invite you to do so.

Given that a few months passed and a few releases were made in the meantime, is this issue still relevant? 

Please also notice that a new SonarQube LTS version has been released! You can pull it from `sonarqube:9.9.0-<EDITION>`.
