### ISSUE TITLE
Missing image & PR for v9.7.1

### ISSUE THREAD

**Issue by stevehipwell** [SonarSource/docker-sonarqube#577]
Please ensure your issue adheres to the following guidelines: 

This repository is used for technical issues only. For general Support like questions, please create a new Thread in our [Community Forum](https://community.sonarsource.com/)

- [x] Please check the problem is not already reported, or a known issue documented in [`develop.md`](develop.md)
- [x] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs

It looks like we're missing a PR to release v9.7.1?

**Comment by jCOTINEAU** [comment]
Hello @stevehipwell thanks a lot for pointing this.

Could you @matteo-mara-sonarsource look at it, as if i remember correctly you were the one doing the release ?

Thanks a lot in advance !

**Comment by jCOTINEAU** [comment]
Thanks a lot for the quick answer.
Shouldn't that be available as a github release with a specific tag also ?

**Comment by jCOTINEAU** [comment]
Release as been done [here](https://github.com/SonarSource/docker-sonarqube/releases/tag/9.7.1)

Closing that issue, and assessing that some more might be missing.

Thanks a lot everyone
