### ISSUE TITLE
sonarqube containter fail to start, could not find java in ES_JAVA_HOME

### ISSUE THREAD

**Issue by artemu78** [SonarSource/docker-sonarqube#590]
Can't run the container.

Trying to run the docker container
`docker run -d --name sonarqube -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true -p 9000:9000 sonarqube:latest`

It exits immediately
```
my@my_comp:~$ docker run -d --name sonarqube -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true -p 9000:9000 sonarqube:latest
78844546e804d9750416d1b6f130111ef87cf74b10f59ecc6fc30ac5f24b35da
me@my_comp:~$ 
```

Logs say `could not find java in ES_JAVA_HOME`
```
me@my_comp:~$ docker logs -f sonarqube
Dropping Privileges
2022.12.19 20:50:07 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2022.12.19 20:50:07 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on [HTTP: 127.0.0.1:9001, TCP: 127.0.0.1:40253]
2022.12.19 20:50:07 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[ELASTICSEARCH] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch
could not find java in ES_JAVA_HOME at /usr/lib/jvm/java-11-openjdk/bin/java
2022.12.19 20:50:07 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [ElasticSearch]: 1
2022.12.19 20:50:07 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2022.12.19 20:50:07 INFO  app[][o.s.a.SchedulerImpl] Process[ElasticSearch] is stopped
2022.12.19 20:50:07 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
```

Ubuntu 20.04.5 LTS, Intel® Core™ i7-2760QM CPU @ 2.40GHz × 8, Laptop Lenovo W520
Docker version 19.03.11, build 42e35e61f3

Any thoughts?

**Comment by noraab** [comment]
I experienced the same on Docker version `20.10.2, build 2291f61` while it worked on Docker version `20.10.22, build 3a2c30b` using `sonarqube:8.9-community` which actually points to `sonarqube:8.9.10-community` at the time of writing this.

When I use `sonarqube:8.9.9-community` instead, everything works fine again.

I guess there is any incompatibility between with the new base image used in `latest` and older Docker daemon versions.

**Comment by mohammedkary** [comment]
same Problem, if i want to use sonarqube:9-community or sonarqube:8.9-community
i had to use sonarqube:8.9.9-community too.

**Comment by jCOTINEAU** [comment]
Dear @artemu78 ,

thanks for raising this issue. It as been reported by many people and we will update the documentation regarding the incompatibility between old docker engines and our SonarQube image.

We typically evaluate bug reports that are submitted through our [community forum](https://community.sonarsource.com/) and we invite you to do so.

Given that a few months passed and a few releases were made in the meantime, is this issue still relevant?

Please also notice that a new SonarQube LTS version has been released! You can pull it from `sonarqube:9.9.0-<EDITION>`.

**Comment by volphy** [comment]
I think I have the same issue as in https://github.com/SonarSource/docker-sonarqube/issues/506

**Comment by jCOTINEAU** [comment]
Hello @volphy, thanks a lot for taking the time to participate in the community.

I would like to emphasize that elasticsearch in docker require kernel level parameter to be set ( see [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-prod-prerequisites) )

When using `SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true` you remove the checks that ensure the prerequisites are done, which can lead to errors as in your logs.

Could you share the reason why you need such config to be done ?

Also glad to hear that your issue is covered by #506, does the conversation there solve your problem ?

**Comment by volphy** [comment]
Thanks for asking.

Yes, it helped.

Though I find it quite confusing that running one Docker container at a given time (two other containers stopped) requires 'Virtual disk limit: 184 GB'.

Maybe it is related to my environment:
- OS: macOS Ventura 13.2.1
- Docker Engine: 20.10.23
- Docker Desktop: 4.17.0
