### ISSUE TITLE
when to upgrade OS to alpine 3.16 ?

### ISSUE THREAD

**Issue by KylanZhang** [SonarSource/docker-sonarqube#597]
As alpine 3.14 will retired on May 1st, when to upgrade OS to 3.16?

**Comment by jCOTINEAU** [comment]
Hello @KylanZhang, Thanks a lot for asking.

SonarQube 9.9 will be out soon, and with it comes a new base image ( eclise-temurin JDK based on debian )

Hope that answer your question, regards.
