### ISSUE TITLE
Latest docker image fails to start (entrypoint not found)

### ISSUE THREAD

**Issue by dib0** [SonarSource/docker-sonarqube#602]
Hi,

Yesterday I've upgraded to the latest LTS of the official SonarQube image in the docker registry. I update once a week. Since the update I can't start the container, I get the following error:
/opt/sonarqube/docker/entrypoint.sh: line 13: /opt/sonarqube/bin/sonar.sh: No such file or directory

To make sure I've tested the :latest, :lts and the latest community images. But they all fail with the same error. Did I do something wrong or has something changed in the last official image build?

If you need more information, please let me know. If I can test something, please let me know! :-)

**Comment by jCOTINEAU** [comment]
Hello @dib0 , yes the base image of our SonarQube docker image changed, that plus some improvement.

I am sorry to ear that it impacted you, it should be transparent for most users.

Can you give me some details on how you are running that image ? 

Is it with docker composer / helm / or plain docker ? 

Anyway the sonar.sh no longer exist in our image, so at first glance that error could appear if you have custom _volumes_ talking about that path, or if you are building _your own image_ on top of the SonarQube one, or if you specify by yourself _entrypoint_ and _commands_

I would be very happy solving that issue together !

**Comment by dib0** [comment]
Hi @jCOTINEAU ,

Thank you for your reply.

I use plain docker (on a synology NAS). No docker compose or custom build image. I have custom volumes/local storage for logs, data and extensions.

The environment variable SONARQUBE_HOME is set to /opt/sonarqube by a previous version of the image, I haven't changed the value.

So my first thought was that the location changed and I needed to change this environment variable. But after checking these two:
https://github.com/SonarSource/docker-sonarqube/blob/master/9/community/Dockerfile
https://github.com/SonarSource/docker-sonarqube/blob/master/example-compose-files/sq-with-postgres/docker-compose.yml
I didn't find any difference, so that when I decided to create this issue.

I'm using the image from the docker hub with basically only the volumes mapped and a connection to a postgress database. Hope this helps!

**Comment by jCOTINEAU** [comment]
Ho that is a strange case.

Could you try to run a new SonarQube instance and see if you end up having the same issue ? to assess if the problem is on the upgrade part, or if lays somewhere else.

The line 13 of the entrypoint contains `exec "$@"` and having your error

```/opt/sonarqube/docker/entrypoint.sh: line 13: /opt/sonarqube/bin/sonar.sh: No such file or directory```

That could imply that `/opt/sonarqube/bin/sonar.sh` is passed as argument of the docker command.

And that `/opt/sonarqube/bin/sonar.sh` is what was executed on the previous docker images, but it does not exist anymore.

Could you have some reference to that in your config ? Can you paste your docker run command if that is possible ?

**Comment by dib0** [comment]
Thank you. Starting a new/clean container managed to lead me to the right path. Apparently Synology keeps the entrypoint in a configuration. I did an export removed the entry point en imported is. Now it starts.

After changing the environment variables to the "new" ones the database upgrade worked and it's back up and running! Thanks again!

**Comment by jCOTINEAU** [comment]
@dib0 thanks a lot for the feedback and the tests done, it is very valuable to us as it might happen for some other people on different technology.

Happy that it is resolved !

**Comment by dib0** [comment]
@jCOTINEAU Thank you! Thanks for the help! 

Other people that possibly run into the same problem are indeed part of the reason why I post issues on Github! :+1:

**Comment by cskarapapas** [comment]
Same issue here.

I just cloned the repo and then both for 9 and 10, developer and community versions I did the following,

First used ` docker build -t localsonar .`
```
$ docker build -t localsonar .
#0 building with "default" instance using docker driver

#1 [internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 2.73kB 0.0s done
#2 DONE 0.1s

#3 [internal] load metadata for docker.io/library/eclipse-temurin:17-jre-jammy
#3 DONE 1.3s

#4 [1/4] FROM docker.io/library/eclipse-temurin:17-jre-jammy@sha256:cafe19b793d3c300ad0ab5b75a491b98b7dcacfae5f0be655ced2eb590b835c7
#4 DONE 0.0s

#5 [internal] load build context
#5 transferring context: 35B done
#5 DONE 0.0s

#6 [2/4] RUN set -eux;     groupadd --system --gid 1000 sonarqube;     useradd --system --uid 1000 --gid sonarqube sonarqube;     apt-get update;     apt-get --no-install-recommends -y install         bash         curl         fonts-dejavu         gnupg         unzip;     echo "networkaddress.cache.ttl=5" >> "/opt/java/openjdk/conf/security/java.security";     sed --in-place --expression="s?securerandom.source=file:/dev/random?securerandom.source=file:/dev/urandom?g" "/opt/java/openjdk/conf/security/java.security";     for server in $(shuf -e hkps://keys.openpgp.org                             hkps://keyserver.ubuntu.com) ; do         gpg --batch --keyserver "${server}" --recv-keys 679F1EE92B19609DE816FDE81DB198F93525EC1A && break || : ;     done;     mkdir --parents /opt;     cd /opt;     curl --fail --location --output sonarqube.zip --silent --show-error "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.9.6.92038.zip";     curl --fail --location --output sonarqube.zip.asc --silent --show-error "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.9.6.92038.zip.asc";     gpg --batch --verify sonarqube.zip.asc sonarqube.zip;     unzip -q sonarqube.zip;     mv "sonarqube-9.9.6.92038" sonarqube;     rm sonarqube.zip*;     rm -rf /opt/sonarqube/bin/*;     ln -s "/opt/sonarqube/lib/sonar-application-9.9.6.92038.jar" "/opt/sonarqube/lib/sonarqube.jar";     chmod -R 555 /opt/sonarqube;     chmod -R ugo+wrX "/opt/sonarqube/data" "/opt/sonarqube/extensions" "/opt/sonarqube/logs" "/opt/sonarqube/temp";     apt-get remove -y gnupg unzip curl;     rm -rf /var/lib/apt/lists/*;
#6 CACHED

#7 [3/4] COPY entrypoint.sh /opt/sonarqube/docker/
#7 CACHED

#8 [4/4] WORKDIR /opt/sonarqube
#8 CACHED

#9 exporting to image
#9 exporting layers done
#9 writing image sha256:6d8fe195c71a864a257486917bd045e65d3d5ad50b7227bf7618bba15a7d20cb done
#9 naming to docker.io/library/localsonar 0.0s done
#9 DONE 0.0s

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview
```

Then checked the image is created
```
$ docker images
REPOSITORY                                                              TAG               IMAGE ID       CREATED          SIZE
localsonar                                                              latest            6d8fe195c71a   16 minutes ago   605MB
```

Then once I try to run it, I get the same error, it also occurs when I try to do the process from Docker desktop
```
$ docker run -p 9000:9000 localsonar
exec /opt/sonarqube/docker/entrypoint.sh: no such file or directory
```
