### ISSUE TITLE
docker image of sonarqube is not running with mysql db configuration

### ISSUE THREAD

**Issue by harish-kumar-garg** [SonarSource/docker-sonarqube#61]
I am trying to run docker image of sonarqube with mysql db by below dockercommand:
sudo docker run -d --name hg-sonarqube \
    -p 9000:9000 \
    -e SONARQUBE_JDBC_USERNAME='sonar' \
    -e SONARQUBE_JDBC_PASSWORD='sonar' \
    -e SONARQUBE_JDBC_URL='jdbc:mysql://localhost:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance' \
    sonarqube

But container is not running due to error:

2016.12.28 11:20:11 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:mysql://localhost:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance
2016.12.28 11:20:11 ERROR web[][o.a.c.c.C.[.[.[/]] Exception sending context initialized event to listener instance of class org.sonar.server.platform.web.PlatformServletContextListener
java.lang.IllegalStateException: Can not connect to database. Please check connectivity and settings (see the properties prefixed by 'sonar.jdbc.').
    at org.sonar.db.DefaultDatabase.checkConnection(DefaultDatabase.java:108)

MySQL service is running and sonar database already created. I used command to create database and give privileges in Ubuntu-14.04.

echo "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'welcome123'; flush privileges;" | mysql -u root -pwelcome123

echo "CREATE DATABASE sonar CHARACTER SET utf8 COLLATE utf8_general_ci; CREATE USER 'sonar' IDENTIFIED BY 'sonar';GRANT ALL PRIVILEGES ON sonar.* TO 'sonar'@'%' IDENTIFIED BY 'sonar'; GRANT ALL ON sonar.* TO 'sonar'@'localhost' IDENTIFIED BY 'sonar'; flush privileges;" | mysql -u root -pwelcome123

**Comment by Godin** [comment]
As stated in error message - `Please check connectivity and settings`. I'm pretty sure that `localhost:3306` isn't correct address, because it specifies host inside of SonarQube container, while your database is most likely not.

**Comment by harish-kumar-garg** [comment]
Yes you are right. Now it is working, Thanks for your guidance.
