### ISSUE TITLE
Update documentation for 10.0 about SECCOMP filter

### ISSUE THREAD

**Issue by konopka** [SonarSource/docker-sonarqube#619]
Documentation at https://docs.sonarqube.org/latest/requirements/prerequisites-and-overview/#header-4 in section "seccomp filter"
still states that it is possible to turn this off for the bundled elasticsearch.

However that is not true anymore, because bundled elasticsearch has been updated from 7.xx to 8.xx where this setting has been removed:
https://github.com/elastic/elasticsearch/pull/72848

I suggest updating the docs with a notice that kernel with SECCOMP enabled is now required.

ref: #614

**Comment by jCOTINEAU** [comment]
Hello @konopka, our official doc has been updated, mentioning that the seccomp filter is now required.
