### ISSUE TITLE
sonarqube token dissappears almost immediately on AWS ec2, 

### ISSUE THREAD

**Issue by hesblac** [SonarSource/docker-sonarqube#627]
this is the problem: 

whenever I set up Sonarqube on AWS either through docker or typical installation, I realize I can't use the token, as when I tried getting the token, it shows and disappears.
but if I install it on my local, it's accessible,
so I think it's not my computer.
please I need help.

**Comment by jCOTINEAU** [comment]
hello @hesblac, when you say typical installation do you mean zip ? if yes that means it is not related to docker itself.

Could you please fill a ticket at our [community forums](community.sonarsource.com) ?

**Comment by hesblac** [comment]
okay... will do just that. thanks .. i hope I see someone to help on these

**Comment by jCOTINEAU** [comment]
Hello again @hesblac, have your problem been resolved ?
