### ISSUE TITLE
SonarQube 10.2 does not start with postgres 15.4 

### ISSUE THREAD

**Issue by quartex** [SonarSource/docker-sonarqube#639]
Hi.,
I'm using sonarqube 10.2 community with postgres 15.2 and all work well.
Today I tried to upgrade to  postgres 15.4 and sonar does not start.
I see the log in postgres and I found this
2023-09-11 05:39:14.680 UTC [21] ERROR:  mergejoin input data is out of order
2023-09-11 05:39:14.680 UTC [21] STATEMENT:  select

            rdi.uuid as "rdi_uuid",
            rdi.rule_uuid as "rdi_ruleUuid",
            rdi.software_quality as "rdi_softwareQuality",
            rdi.severity as "rdi_severity",

            rds.content as "rds_content",
            rds.uuid as "rds_uuid",
            rds.kee as "rds_kee",
            rds.context_key as "rds_contextKey",
            rds.context_display_name as "rds_contextDisplayName",

            r.uuid as "r_uuid",

            r.plugin_rule_key as "ruleKey",
            r.plugin_name as "repositoryKey",
            r.description_format as "descriptionFormat",
            r.status,
            r.name,
            r.plugin_config_key as "configKey",
            r.priority as "severity",
            r.is_template as "isTemplate",
            r.is_external as "isExternal",
            r.is_ad_hoc as "isAdHoc",
            r.language as "language",
            r.template_uuid as "templateUuid",
            r.def_remediation_function as "defRemediationFunction",
            r.def_remediation_gap_mult as "defRemediationGapMultiplier",
            r.def_remediation_base_effort as "defRemediationBaseEffort",
            r.gap_description as "gapDescription",
            r.system_tags as "systemTagsField",
            r.security_standards as "securityStandardsField",
            r.rule_type as "type",
            r.plugin_key as "pluginKey",
            r.scope,
            r.created_at as "createdAt",
            r.updated_at as "updatedAt",
            r.note_data as "noteData",
            r.note_user_uuid as "noteUserUuid",
            r.note_created_at as "noteCreatedAt",
            r.note_updated_at as "noteUpdatedAt",
            r.remediation_function as "remediationFunction",
            r.remediation_gap_mult as "remediationGapMultiplier",
            r.remediation_base_effort as "remediationBaseEffort",
            r.tags as "tagsField",
            r.ad_hoc_name as "adHocName",
            r.ad_hoc_description as "adHocDescription",
            r.ad_hoc_severity as "adHocSeverity",
            r.ad_hoc_type as "adHocType",
            r.education_principles as "educationPrinciplesField",
            r.clean_code_attribute as "cleanCodeAttribute"
            from
              rules r
            left outer join rule_desc_sections rds on
              rds.rule_uuid = r.uuid
            left outer join rules_default_impacts rdi on
              rdi.rule_uuid = r.uuid

            order by r.uuid

THen I return to use the version 15.2
Thanks

**Comment by davividal** [comment]
Hi @quartex. Thank you for reporting this.
Sorry for the delayed response.

We value the input from the users, so we have a dedicated forum for it. To improve the way we handle these requests (e.g., new features or bugs), you are encouraged to create a new thread in our [forum](https://community.sonarsource.com/c/sq/10).

About your issue: it seems to me very similar to [this](https://community.sonarsource.com/t/failed-to-migrate-database-after-migrate-to-9-5/64701/3) other one. Did you go through our [PostgreSQL cleanup](https://docs.sonarsource.com/sonarqube/latest/setup-and-upgrade/upgrade-the-server/upgrade-guide/#postgresql-cleanup) recommendations after your upgrade?

**Comment by jCOTINEAU** [comment]
Hello @quartex, following Davi's message i will proceed by closing this issue.

If this is still a need do not hesitate to go on the linked forum, this will tremendously ease the triaging process.
