### ISSUE TITLE
Missing linux/amd64 for version 10.2.1-xxx

### ISSUE THREAD

**Issue by dabio** [SonarSource/docker-sonarqube#645]
Hi,

the latest version on docker.io is missing the arch `linux/amd64` for all tags with `10.2.1-xxx`. Could you please add this arch and push to docker hub? Thanks.

**Comment by jCOTINEAU** [comment]
Hello @dabio, thanks a lot for participating in the community.

While searching the docker hub with 10.2.1 I see the arch being [here](https://hub.docker.com/_/sonarqube/tags?page=1&name=10.2.1)

Is your issue still happening ?

**Comment by dabio** [comment]
@jCOTINEAU,

thanks for asking. The missing architecture is now present. I'll close this.
