### ISSUE TITLE
Docker image cant run due to java issue

### ISSUE THREAD

**Issue by donovan361** [SonarSource/docker-sonarqube#655]
I have encountered an error `Exception in thread "main" java.lang.ClassFormatError: Incompatible magic value 0 in class file sun/net/www/protocol/jar/JarURLConnection`.

Below is the screenshot of the docker bash:
![image](https://github.com/SonarSource/docker-sonarqube/assets/97430708/c17dee54-e35a-4d70-b481-496f3c7cd2f4)

The command I use to run is from the quick demo guide `docker run -d --name sonarqube -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true -p 9000:9000 sonarqube:latest`. I also pulled the image before running the previous command with `docker pull sonarqube`. 

Appreciate the help!

**Comment by jCOTINEAU** [comment]
Hello @donovan361 thanks a lot for taking the time to participate in the community.

I guess it is a screenshot from docker desktop ? if yes can you provide the architecture and os ? 

I will ask some help on java expertise as this specific error from the default command does not ring a bell to me.

**Comment by donovan361** [comment]
Actually its alright already, i just ran the comment to bind to port 9000 only, and left out the rest of the docker options. Thanks!
