### ISSUE TITLE
gid=0 will violate future Pod Security Standards Restricted Profile

### ISSUE THREAD

**Issue by jonasrutishauser** [SonarSource/docker-sonarqube#673]
Please ensure your issue adheres to the following guidelines: 

This repository is used for technical issues only. For general Support like questions, please create a new Thread in our [Community Forum](https://community.sonarsource.com/)

- [x] Please check the problem is not already reported, or a known issue documented in [`develop.md`](develop.md)
- [x] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs

According to https://github.com/kubernetes/kubernetes/issues/118987#issuecomment-1884864735 setting the gid=0 will no longer be allowed in kubernetes.
Therefore the change https://github.com/SonarSource/docker-sonarqube/commit/8e556d6ac42832b1e1049a442b6cf8e3583d6330 triggers a new security issue.

**Comment by jCOTINEAU** [comment]
Hello @jonasrutishauser thanks a lot for taking the time to participate in the community.

This is very interesting, we have actually been following gid 0 principle to be compatible with Openshift and more specifically with anyUserID setups (see https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html Support Arbitrary User IDs)

Do you have clues towards what setup in terms of permissions in the Dockerfile should be set by now to allow any UID setup ?

**Comment by jonasrutishauser** [comment]
I just found a solution which should work at the moment (no change needed in the docker image).
As there is no `runAsNonRootGroup` at the moment, it is enough to not set the group explicitly and only set the `fsGroup` to something which is not `0`.
This means the chart can be configured like the following:
```yaml
securityContext:
  fsGroup: 1000
containerSecurityContext:
  runAsGroup: null
initContainers:
  securityContext:
    runAsGroup: null
```
Eventually this could be reflected in the official chart such that is not needed to remove some values.

**Comment by jCOTINEAU** [comment]
Unfortunately, inside the Docker image we do set some permissions on file (some read only, some writeable) and we use the groupId to make sure that any user ID can be picked.

If we go to runAsGroup: null and fsGroup: any, then it means that from the docker filesystem point of vue we will have to rely on allowing read only for everyone and write for everyone.

While this looks okay to me in a container context from a security point of vue (we were in this situation for a bit) it looks like industry standards (openshift) are not going in this direction

**Comment by leobr29** [comment]
Hi @jCOTINEAU,

Some production environment already ban the use of uid or gid = 0 to run a container.

Why do not use a gid != 0 as it was the case before ? I was already able to manage Arbitrary User IDs with this kind of command :

docker run -u 9999:9999 --group-add 1000 sonarqube

Best,
Leo.
