### ISSUE TITLE
Resolve vulnerabilities in docker images

### ISSUE THREAD

**Issue by othomann** [SonarSource/docker-sonarqube#686]
Hi,

from https://hub.docker.com/layers/library/sonarqube/lts-community/images/sha256-a05a6ffb12f12058671fd24316faab24b238543502a4d631cd3908700ef2f796?context=repo&tab=vulnerabilities, I can see that the latest images in docker hub contains quite a few vulnerabilities (2 critical, 11 high etc.).
Do you have any plans to fix them ? Some of the packages have fixable versions to resolve them according to docker hub.
Thanks.

**Comment by carminevassallo** [comment]
Hi @othomann,

thanks for raising this issue.

Could you please post your question in our [community forum](https://community.sonarsource.com/)? It will then get triaged to the right team :)

**Comment by othomann** [comment]
@carminevassallo hi, in what forum specifically should I post the message ? Thanks.

**Comment by carminevassallo** [comment]
Hi again @othomann,

I was referring to this [community forum](https://community.sonarsource.com/). Do you have access to the link?

**Comment by othomann** [comment]
yes, but I mean what forum  ? I was about to post a new topic in `Product Manager for a Day topics` under sonarqube category. Is this the right place ?

Thanks.

**Comment by othomann** [comment]
I posted https://community.sonarsource.com/t/resolve-vulnerabilities-in-docker-images/115223
