### ISSUE TITLE
Include necessary port bind on documentation

### ISSUE THREAD

**Issue by felipementel** [SonarSource/docker-sonarqube#692]
Many people don't know what the default sonarqube port is that we should use to do port binding in order to open the local sonarqube page when creating a container. (Port 9000)

Therefore, I believe that making this information explicit on the docker hub page would add great value to users.

For example, this command: docker container run --name sonarqube-community -p 9044:9000 sonarqube:10.5.1-community
If necessary, I can make changes to the page that is published: https://hub.docker.com/_/sonarqube

**Comment by jCOTINEAU** [comment]
Hello @felipementel, thanks a lot for taking the time to participate in the community.

This would be a very good example, but we usually try not to have split documentation. everything should be added [here](https://docs.sonarsource.com/sonarqube/latest/setup-and-upgrade/install-the-server/installing-sonarqube-from-docker/)

Nonetheless, this is the basic use case, so it could be worth putting here. I will ask the documentation team internally what they think.

**Comment by felipementel** [comment]
> Hello @felipementel, thanks a lot for taking the time to participate in the community.
> 
> This would be a very good example, but we usually try not to have split documentation. everything should be added [here](https://docs.sonarsource.com/sonarqube/latest/setup-and-upgrade/install-the-server/installing-sonarqube-from-docker/)
> 
> Nonetheless, this is the basic use case, so it could be worth putting here. I will ask the documentation team internally what they think.

Thanks for your response.

Yes, I understand that the complete documentation is in the link you shared, but there is nothing about port binding in the docker hub documentation.

Several tools have easier examples in the docker hub documentation and more specific examples within the product documentation.

As a consumer of the product, I believe it is of great value to have basic examples on the Docker page, including the reason that with the example that exists, there is no way to access the sonarqube through the browser;

I teach many people how to use the tool and I believe that having this simple example can help students and enthusiasts

**Comment by felipementel** [comment]
@jCOTINEAU any update?

**Comment by jCOTINEAU** [comment]
The documentation ticket has been created and will be dealt with, I don't have a specific timebox.

In the meantime if you want to participate in the community you can propose changes here https://github.com/docker-library/docs/blob/master/sonarqube/content.md and assign me as a reviewer, I will bridge with our documentation team.

**Comment by jCOTINEAU** [comment]
Hello @felipementel i will close this issue as the ticket has been created, I still don't have an ETA but thanks again for raising and participating in improving our product

**Comment by felipementel** [comment]
Hello @jCOTINEAU,

I create a pull request at the documentation on hub.docker.com.
[https://github.com/docker-library/docs/pull/2486](url)

**Comment by jCOTINEAU** [comment]
@felipementel just saw that, thanks again for your contribution. i virtually approved but the final button click is still from docker guys
