### ISSUE TITLE
com.docker.hyperkit 300%+ CPU Usage

### ISSUE THREAD

**Issue by Na3blis** [SonarSource/docker-sonarqube#78]
I just setup sonarqube with docker-compose and postgres. Below is my compose file

```version: '2'

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data

    ports:
      - 5432:5432
    networks:
      - dev
    environment:
      - POSTGRES_PASSWORD=*****
      - POSTGRES_USER=mbi
    restart: always

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ports:
      - 9000:9000
    networks:
      - dev
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=*****
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/mbi
    depends_on:
      - "postgres"
    restart: always

networks:
  dev:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
```

I haven't even done anything other than create the image. It starts up, and I can load localhost:9000. However, I left, and when I came back, my computer was running like crazy. I looked at activity monitor and saw that com.docker.hyperkit was at over 300% CPU. I ran docker stop sonarqube, and within a minute, it dropped down to < 5%. 
After a few minutes of it hanging at < 5% I started sonarqube again, and it immediately went up to 150% CPU usage. It sometimes drops a little below 100, but is mostly between 150-360% CPU.

Since I had not really done anything yet, I removed the container, and recreated it, and had the same problem. I am running Docker 17.03.1-ce-mac5 (16048). I am on Sierra, 10.12.5 Beta (16F43c).

**Comment by Godin** [comment]
On a search by "com.docker.hyperkit cpu" Google shows https://github.com/docker/for-mac/issues/1094 that suggest to increase memory for Docker and also mentions some patches for Docker itself. Hence unrelated to this repository.
