### ISSUE TITLE
Provide standard way to define proxy

### ISSUE THREAD

**Issue by md42** [SonarSource/docker-sonarqube#79]
Hi,
Is there a parameter to define the proxy being used by sonar in combination with docker?

Right now i am setting a proxy in the sonar.properties via Dockerfile like this (which isn't working)
`RUN echo "" >> /opt/sonarqube/conf/sonar.properties #newLine before we add some properties
RUN echo "http.proxyHost=http://MY_PROXY_URL" >> /opt/sonarqube/conf/sonar.properties
RUN echo "http.proxyPort=MY_PROXY_PORT" >> /opt/sonarqube/conf/sonar.properties`

So it is being added at the end of the standard sonar.properties file

And I can see the proxy in the http://MY_SONAR_INSTALLATION/system screen. Nevertheless i cannot see any plugins under http://MY_SONAR_INSTALLATION/updatecenter/available so I assume sonar is started in the base image before i am adding the property file. Adding the same entrypoint again at the end of my dockerfile didn't help.

I am glad for any feedback

**Comment by md42** [comment]
Just realized I have to omit the protocol http:// that way it works just fine :)
Nevertheless a standard way to define the proxy via ENV variable (a la jdbc connection in dockerfile) would be nice

**Comment by Godin** [comment]
Properties mentioned in https://github.com/SonarSource/sonarqube/blob/5.6.6/sonar-application/src/main/assembly/conf/sonar.properties can be passed as following
```
docker run -d sonarqube -Dhttp.proxyHost=myproxy
```
and equivalent of this in a docker-compose notation:
```
version: "2"

services:
  sonarqube:
    image: sonarqube
    command: -Dhttp.proxyHost=myproxy
```
