### ISSUE TITLE
only set env ,but mount conf volume is invalid

### ISSUE THREAD

**Issue by txiaocao** [SonarSource/docker-sonarqube#88]
i want use database by mysql
but i set 
-v /dev/sonar/conf:/opt/sonarqube/conf 
and configure sonar.jdbc.url 
but the sonar still use h2 database

only use -e SONARQUBE_JDBC_URL="jdbc:mysql://mysql.sonar.mtime-dev.com:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false" \
is okay..

**Comment by Godin** [comment]
Execution of

```
docker run -it --rm --name sonarqube \
  -e SONARQUBE_JDBC_URL="jdbc:mysql://mysql.sonar.mtime-dev.com:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false" \
  -p 9000:9000 sonarqube:5.6.6-alpine
```

shows to me that MySQL will be used:
```
2017.06.09 10:42:58 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:mysql://mysql.sonar.mtime-dev.com:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
```

**Comment by txiaocao** [comment]
I use env can run...
but i want use sonar/conf/sonar.properties file.. to mount the container.
the way more readable and configured is easy

**Comment by Godin** [comment]
@txiaocao then you need to change `run.sh` because value specified in it takes precedence over `conf/sonar.properties` - https://github.com/SonarSource/docker-sonarqube/blob/master/5.6.6-alpine/run.sh#L13

**Comment by txiaocao** [comment]
Thanks for your feedback
