### ISSUE TITLE
Container runs as root

### ISSUE THREAD

**Issue by javixeneize** [SonarSource/docker-sonarqube#89]
Hi

The container that is created with Sonarqube runs as root. I would need it to be running with a different user

To do that, i have created in my dockerfile a new user

from sonarqube:alpine
COPY . /home/javi
WORKDIR /home/javi
RUN useradd -ms /bin/bash -u 1001 javi
USER 1001

But the container still runs as root

How can i run it as a non root user?

**Comment by Godin** [comment]
Addition of a user is definitely not enough. You need to change the way application starts - see https://github.com/SonarSource/docker-sonarqube/blob/c0cae340838f57fb2af7b6441daaf3d2987a4d34/5.6.6-alpine/Dockerfile#L38
And probably permissions for files inside container.

**Comment by javixeneize** [comment]
I have done a bit of progress. I am modifying the permissions for the jar,
and also running the specific run.sh inside sonarqube/bin

RUN chmod 777 /opt/sonarqube/lib/sonar-application-6.4.jar
ENTRYPOINT ["/opt/sonarqube/bin/run.sh"]

But still having a permission error -- Error: Unable to access jarfile
lib/sonar-application-6.4.jar


Any idea?

Thanks
