### ISSUE TITLE
Image rebuild fails

### ISSUE THREAD

**Issue by f-fly2** [SonarSource/docker-sonarqube#90]
Hi

I am trying to rebuild the sonarqube 6.4 image to amend it (i want to run it with a lesser privileged user), but i am having an error when building it

What i am doing is creating a dockerfile that contains exactly what is in your git (https://github.com/SonarSource/docker-sonarqube/blob/master/6.4/Dockerfile)

But, i am having an error in the last step, when copying the run.sh file

Step 7 : COPY run.sh $SONARQUBE_HOME/bin/
lstat run.sh: no such file or directory

Any idea what could be the problem?

Thanks

**Comment by Godin** [comment]
You don't have [`run.sh`](https://github.com/SonarSource/docker-sonarqube/blob/master/6.4/run.sh) file.
