### ISSUE TITLE
Is there a version of Sonarqube docker that I can run on Windows 2016

### ISSUE THREAD

**Issue by Geekays** [SonarSource/docker-sonarqube#91]
Is there a version of Sonarqube docker that I can run on Windows 2016?

**Comment by Godin** [comment]
If you are asking about image that is based on https://hub.docker.com/r/microsoft/windowsservercore/ , then as you case see in this repository (github.com/SonarSource/docker-sonarqube) and in Docker Hub (https://hub.docker.com/_/sonarqube/) there is no such image.
However even on Windows you can run containers that are based on Ubuntu - https://docs.docker.com/docker-for-windows/

**Comment by dredav** [comment]
> However even on Windows you can run containers that are based on Ubuntu - https://docs.docker.com/docker-for-windows/
But thats only working with Docker For Windows Server CE and not with Docker For Windows Server EE

**Comment by Godin** [comment]
@dredav quoting https://blog.docker.com/2017/09/preview-linux-containers-on-windows/ :
> Running **Docker Linux containers on Windows**...
> Be sure to install Docker for Windows (Windows 10) or **Docker Enterprise Edition**...

In any case answer on question "is there in this repository a Dockerfile that is based on image such as microsoft/windowsservercore/" remains the same - no, there is no such. Feel free to create your own.
