### ISSUE TITLE
Provide standard way to install plugins

### ISSUE THREAD

**Issue by tobilarscheid** [SonarSource/docker-sonarqube#93]
Hi everyone,

I think this image should have a standard way to install required sonar plugins, maybe by passing them in as a list or something like this.

Regards,

Tobi

**Comment by jkblume** [comment]
this would be nice

**Comment by madnight** [comment]
Sonarqube should provide a plugin manager. For instance, both zsh and vim have many different plugin managers available, e.g. https://github.com/zplug/zplug for zsh or https://github.com/junegunn/vim-plug for vim.

**Comment by tobilarscheid** [comment]
Hi @jkblume @madnight please have a look at #94 and let me know what you think!

**Comment by Godin** [comment]
Closing this for the reasons described in #94
